### ISSUE TITLE
High level architecture design

### ISSUE THREAD

**Issue by liurenjie1024** [infinyon/fluvio#1]
Any high level architecuture desing? I'm interested in contributing this, but it seems there's not enough information about this.

**Comment by sehz** [comment]
Hi, 

Yes, we will be adding more technical documents, including arch overview.  Please be patient.

**Comment by sehz** [comment]
We have updated the arc document.  This has not been pushed to fluvio.io but you can render locally: https://github.com/infinyon/fluvio-website.
