### ISSUE TITLE
Document cluster behavior when produced data exceeds storage limit

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1006]
Fluvio Cloud specifies a 1GB storage limit, but does not describe the behavior of the system when it exceeds the limit. I think we should add documentation that describes the expected behavior when this occurs. For example should it:

- Refuse the newly-produced records and send an error response to the client?
- Roll the logs and drop the oldest records?

It seems to me like either of these options may be desirable, so we should make it configurable, though we should open a different issue for that. For this issue, we should identify the default behavior and figure out how and where to document it.

**Comment by tjtelan** [comment]
We may have the stability to test this behavior in CI now
