### ISSUE TITLE
[Bug]: Client hangs for really large offset values

### ISSUE THREAD

**Issue by avinassh** [infinyon/fluvio#1007]
**What happened**

I tried to create a `stream` with a large offset value, but it just hangs

**Expected behavior**
well, I expected a stream

**Describe the setup**
- I am using Fluvio Cloud
- version info: 

```shell 
Fluvio CLI           : 0.7.3
Fluvio CLI SHA256    : 557cc7d2bea9f4e38c62ac9752c603e7a48779ee9c34e61c1bbc77a1789a727a
Fluvio Platform      : 0.7.3 (cloud)
Git Commit           : 895c07f66347d089c2b85a9df28ed1a4b71f3cb3
OS Details           : Darwin 10.15.7 (kernel 19.6.0)
=== Plugin Versions ===
Fluvio Cloud CLI (fluvio-cloud) : 0.1.5
```

**How to reproduce it (as minimally and precisely as possible)**
run this sample rust code:

```rust
use fluvio::{Offset, FluvioError};
use fluvio_future::task::run_block_on;
use fluvio_future::io::StreamExt;

async fn consume() -> Result<(), FluvioError> {
    let consumer = fluvio::consumer("gogogo", 0).await?;
    // this offset works
    let offset = Offset::beginning();
    // but this just hangs
    let offset = Offset::from_beginning(u32::MAX);
    let mut stream = consumer.stream(offset).await?;
    // this never gets printed
    eprintln!("got a stream");
    while let Some(Ok(record)) = stream.next().await {
        let key = record.key().map(|key| String::from_utf8_lossy(key).to_string());
        let value = String::from_utf8_lossy(record.value()).to_string();
        println!("Got record: key={:?}, value={}", key, value);
    }
    Ok(())
}

fn main() {
    run_block_on(consume());
}
```

**Environment (please complete the following information):**
OS: OSX 10.15.7
Rust: 1.51.0 (2fd73fabe 2021-03-23)

**Comment by sehz** [comment]
Thanks for report

**Comment by nicholastmosher** [comment]
Thanks for filing this @avinassh! The consumer and offset APIs definitely need some love, this will be good to polish up 👍 

I think the expected behavior here should be that the `.stream()` call just return an error right away. We'll probably want a new `FluvioError` variant for this

**Comment by ajhunyady** [comment]
@nicholastmosher not sure that it should return an error. It seems to me this is just another way to get Offset::from_end.

**Comment by ajhunyady** [comment]
As @sehz stated, we need a better way to express location & ranges in the stream. I would argue that `offset` only look-up is insufficient. Based on what I heard from various users, they need a `time-based` look-up. If we decide to change this API, we should look into extending it with time-based ranges.

**Comment by sehz** [comment]
Yes, we need flexible and general way to search and filter events.

**Comment by nicholastmosher** [comment]
This should be closed by https://github.com/infinyon/fluvio/pull/1442

**Comment by sehz** [comment]
@morenol confirm this behavior is fixed
