### ISSUE TITLE
Remove/replace SplitStream

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#1032]
Currently `InnerFlvSocket<S>` is a `TCPStream` and it needs to just have references to a `Box<dyn NetStream>` or such for the `sink` and `stream` attributes.

The underlying issue is [`SplitSink`](https://github.com/infinyon/fluvio/blob/828bcc7dff7f8403103a263ea8da43eab825801a/src/socket/src/sink.rs#L36)

Let's make `InnerFlvSocket` look like this:
```rust
pub struct InnerFlvSocket {
    sink: InnerFlvSink<Box<dyn NetStream>>,
    stream: InnerFlvStream<Box<dyn NetStream>>,
    stale: bool,
}
```

**Comment by nicholastmosher** [comment]
This change is needed for wasm compatibility, right? What is it about `SplitSink` that makes it unusable for this?

**Comment by sehz** [comment]
Depends on: https://github.com/infinyon/future-aio/pull/56.

Use new dy trait `Connection` to allow us to plug-in any connection that satisfy condition including WASM, TLS, etc.

**Comment by sehz** [comment]
Done
