### ISSUE TITLE
Smart Stream Filter Doc

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#1035]
Document:
* Writing Smart Smart Stream Filter
* Running Filter

Blocked on:

- New Records API https://github.com/infinyon/fluvio/pull/1088
- SmartStream Filter API https://github.com/infinyon/fluvio/pull/1051

**Comment by ajhunyady** [comment]
Need to restructure `Fluvio Docs` and add a `Smart Stream` section.

**Comment by nicholastmosher** [comment]
Closed by https://github.com/infinyon/fluvio-website/pull/86
