### ISSUE TITLE
Add Windows to CI

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#1039]
Github actions offers 2 types of Windows runners. Only one of them has WSL (v1, but I'm not sure what the limitations are at this point)

https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md

I'm not sure what the shape of this initial solution will look like.
- Will the codebase compile in Windows?
- Will a server run in Windows runner in CI?
- Do I need a separate test for using the Linux binary in WSL?

**Comment by sehz** [comment]
Fluvio does't have to compile nor run in Windows.  Just have to run in WSL

**Comment by tjtelan** [comment]
Resolved by #1295
