### ISSUE TITLE
Fluvio upgrade recommendation should not suggest prerelease

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1053]
The CLI has an upgrade suggestion feature that is currently only triggered when running the `fluvio install` command. As of right now, it incorrectly suggests the very latest release that may be upgraded to, even if it is a prerelease.

```
💡 An update to Fluvio is available!
💡     Run 'fluvio update' to install v0.8.2+eeaa19e19eb754c3d58e445469f1655da5a2d2de of Fluvio
```

We should make sure that this only suggests more recent release versions

**Comment by sehz** [comment]
@nicholastmosher this issue can be closed?

**Comment by nicholastmosher** [comment]
I think this is fixed... we'll know for sure when we start putting out prereleases for 0.8.3 if this pops up again. I'm going to close it for now
