### ISSUE TITLE
ApiVersion response starts with 4 extra bytes

### ISSUE THREAD

**Issue by nacardin** [infinyon/fluvio#1075]
Example code https://github.com/nacardin/fluvio/blob/20818f8f502473c80e01349008c1115c40bebd76/src/spu/src/liveness_check.rs

**Comment by simlay** [comment]
To reproduce part of this bug, append this to the end of [`dataplane-protocolsrc/versions.rs`](https://github.com/infinyon/fluvio/blob/master/src/dataplane-protocol/src/versions.rs)
```rust
#[cfg(test)]
mod broke_decoding {

    use super::*;
    use fluvio_protocol::api::ResponseMessage;
    use std::io::Cursor;
    #[test]
    fn test_response_decoding() {
        let input_msg = ResponseMessage {
            correlation_id: 1,
            response: ApiVersionsResponse {
                error_code: ErrorCode::None,
                api_keys: vec![
                    ApiVersionKey {
                        api_key: 1001,
                        min_version: 0,
                        max_version: 0,
                    },
                    ApiVersionKey {
                        api_key: 1002,
                        min_version: 1,
                        max_version: 1,
                    },
                    ApiVersionKey {
                        api_key: 1003,
                        min_version: 0,
                        max_version: 0,
                    },
                    ApiVersionKey {
                        api_key: 1004,
                        min_version: 0,
                        max_version: 0,
                    },
                    ],
                    platform_version: PlatformVersion(
                        String::from("0.8.2"),
                    ),
            },
        };
        let bytes = input_msg.as_bytes(0);
        assert!(bytes.is_ok());
        let bytes = bytes.unwrap();
        println!("ENCODED BYTES ARE: {:?}", bytes.to_vec());

        // Logs from sc
        let bytes_from_sc_logs : Vec<u8> = vec![0, 0, 0, 41, 0, 0, 0, 1, 0, 0, 0, 0, 0, 4, 3, 233, 0, 0, 0, 0, 3, 234, 0, 1, 0, 1, 3, 235, 0, 0, 0, 0, 3, 236, 0, 0, 0, 0, 0, 5, 48, 46, 56, 46, 50];
        assert_eq!(bytes, bytes_from_sc_logs);

        // logs from echo example on host
        let bytes_from_tcp_stream_logs : Vec<u8> = vec![                      0, 0, 0, 1, 0, 0, 0, 0, 0, 4, 3, 233, 0, 0, 0, 0, 3, 234, 0, 1, 0, 1, 3, 235, 0, 0, 0, 0, 3, 236, 0, 0, 0, 0, 0, 5, 48, 46, 56, 46, 50];
        println!("DECODED BYTES ARE: {:?}", bytes_from_tcp_stream_logs);
        //assert_eq!(bytes, from_logs);


        let decoded_from_tcp_logs = ResponseMessage::<ApiVersionsResponse>::decode_from(&mut Cursor::new(bytes_from_tcp_stream_logs), 0);
        //let err = response.err();
        //println!("RESPONSE: {:?}", err);
        //assert!(err.is_none());
        assert!(decoded_from_tcp_logs.is_ok());
        let response = decoded_from_tcp_logs.unwrap();
        println!("RESPONSE: {:#?}", response);
        println!("input_msg: {:#?}", input_msg);
        // ResponseMessage doesn't derive PartialEq so you can't do this assertion.
        // assert_eq!(response, input_msg);
        /*
        */
        let response = ResponseMessage::<ApiVersionsResponse>::decode_from(&mut Cursor::new(bytes_from_sc_logs), 0);
        // This should pass but does not.
        assert!(response.is_ok());
    }
}

```
Basically, the last `assert` should be okay as it's decoding the `sc_logs` which also match that of the encoding on the `input_msg`. It's unclear why the TCPStream removes the first four bytes.

**Comment by morenol** [comment]
> Basically, the last `assert` should be okay as it's decoding the `sc_logs` which also match that of the encoding on the `input_msg`. It's unclear why the TCPStream removes the first four bytes.

As far as I understand that last assert should not pass. The first 4 bytes of bytes_from_sc_logs are the [length of ResponseMessage\<ApiVersionsResponse\>.](https://github.com/infinyon/fluvio/blob/e72b67bac332d4060e2eb01de3923094a0b3db71/src/protocol/fluvio-protocol-api/src/response.rs#L105) The decoder [implementation](https://github.com/infinyon/fluvio/blob/e72b67bac332d4060e2eb01de3923094a0b3db71/src/protocol/fluvio-protocol-api/src/response.rs#L43) does not take in consideration those bytes used in the encoding to represent the size. 

Does that make sense? If that is true, then the first 4 bytes are just the length of the ResponseMessage so I think that those 4 bytes are fine.

**Comment by sehz** [comment]
It's probably because of https://github.com/infinyon/fluvio/blob/master/src/protocol/fluvio-protocol-codec/src/codec.rs which is used in the TCPStream.   It's not symmetrical.  Can you update codec so `ReponseMessage` can have symmetrical encoder/decoder?

**Comment by morenol** [comment]
Sure, I am going to check that @sehz

**Comment by morenol** [comment]
Correct me if I'm wrong, do you want that [`encode`](https://github.com/infinyon/fluvio/blob/1aa7b33e421febb0f0124c56b81dfe3e6303aa5b/src/protocol/fluvio-protocol-codec/src/codec.rs#L73) includes the length? So it is symetric with `decoder` and we don;t send the length separately like [this](https://github.com/infinyon/fluvio/blob/1aa7b33e421febb0f0124c56b81dfe3e6303aa5b/src/protocol/fluvio-protocol-codec/src/codec.rs#L160) in the tests?

**Comment by sehz** [comment]
Yes.  We want to have no surprise.  RequestMessage encode and decode should work in any network connection

**Comment by morenol** [comment]
I tried #1080, but then since most of the primitive types does not include their length in their encoding, the decoding of them is failing. On the other hand I think that we cannot do many modifications to fluvio-protocol-codec since they handle raw data and we are not aware in the encoding part about the length of the underlying type.

The other approach that I think that we can do is to make  RequestMessage, ResponseMessage and ApiMessage decoder and encoder symmetric. And then modify this to send the lenght of the data just like I see that it is done with the primitive types. What do you think?
