### ISSUE TITLE
Add automatic batching to Producer API

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1077]
We want Fluvio's Producer API to be as easy-to-use as possible, while also achieving the highest possible performance. Our current TopicProducer API has several drawbacks that harm usability and make high performance the exception rather than the norm. The number-one problem with the current API is the **lack of automatic batching**.

Let's take a look at some things the current TopicProducer API does poorly, and what things we want to be able to do well.

## What do we do now?
- Currently, `producer.send(...).await?` will make a full round-trip request/response to the SPU.
- This means that every single record is sent as an individual network request, it is _highly inefficient_
- To do any sort of batching, we require the caller to use `producer.send_all(...)`, which has several downsides:
  - It requires the user to memorize one more function and know when it is appropriate to use it (hard to use)
  - It requires the user to write their own buffering logic any time they want to use batching, when batching should be the default in most cases.
- We do not provide any metadata to describe committed records, e.g. Offset or Partition

## What we _should_ be doing

- We should accept individual records from the caller, but automatically perform batching to increase efficiency
- Batching should be configurable with the following options:
  - Linger: A duration of time during which new records will be buffered rather than immediately sent. Every time the linger duration elapses, the producer should flush all buffered records to SPUs.
  - Max Bytes: The maximum size that a batch may become before it _must_ be flushed. Upon accepting a new record, if that record would increase the size of the batch above `max_bytes`, it will trigger a flush to SPU, and the new record will be added to the next batch.
- We should ensure that callers can still detect when their record has been committed or failed to commit
  - We will tackle this in Phase 2
- We should provide access to metadata for committed records, such as Offset and Partition
  - Phase 2
- We should provide the ability to manually flush any buffered records
- Accomplish this with as few breaking API changes as possible

---

## API Changes

The following changes will be made to the Producer API to support batching:

1) The addition of `TopicProducer::flush()` to flush batched records
2) The addition of `ProducerConfig` to specify batching behavior (batch duration and batch size)
3) A new `Fluvio::topic_producer_with_config` method for instantiating a producer with non-default configuration

1) Definition

```rust
impl TopicProducer {
    /// Waits for all records to be flushed from the internal buffer
    pub async fn flush(&self) -> Result<(), FluvioError> { ... }
}
```

2) Definition

```rust
pub struct ProducerConfig {
    pub batch_duration: std::time::Duration,
    pub batch_size: usize, // Max batch size in bytes
}
```

3) Definition

```rust
impl Fluvio {
    pub async fn topic_producer_with_config(&self, config: ProducerConfig) -> Result<TopicProducer, FluvioError> { ... }
}
```

---

## Example scenarios

The `producer.send` method shall have a new behavior where it simply buffers records, rather than performing a full request to the SPU. Consider the following snippet:

```rust
producer.send(RecordKey::NULL, "A").await?;
producer.send(RecordKey::NULL, "B").await?;
producer.send(RecordKey::NULL, "C").await?;
```

Before batching, this would result in:

- Three distinct requests being sent to an SPU
- Each `send` call waiting for the request/response to complete

After batching, this will result in:

- Three records being added to the producer's buffer
- These records _may_ be flushed automatically, depending on the flushing configurations. Since this snippet did not use `flush`, it is possible that no records are flushed at all, when `producer` is dropped these may be lost.
- The exact requests that are constructed from this snippet are not defined. That is, there may be three requests with one record each, there may be one request with three records, or any combination. This will depend on the flushing configuration.

We can add a `flush` call to ensure that all records are flushed from the internal buffer:

```rust
producer.send(RecordKey::NULL, "A").await?;
producer.send(RecordKey::NULL, "B").await?;
producer.send(RecordKey::NULL, "C").await?;
producer.flush().await?;
```

This will result in:

- The three `send` calls buffer their records
- The three records will be flushed to the SPU in one or more batches
- After `flush` has returned, all the records will be flushed and no longer in the buffer

## Example scenario: backpressure

One scenario in which `send` might not complete immediately is if the buffer has become full. Consider the following snippet:

```rust
producer.send(RecordKey::NULL, "11234").await?; // Buffer is now full, requests are being sent as fast as possible
producer.send(RecordKey::NULL, "11235").await?; // Here, the caller does not return immediately, it must wait until the buffer has room.
```

In this scenario:

- 11,234 records have been given using `producer.send`
- Zero or more of those records may be in-flight in requests to the SPU
- The buffer is full, meaning that the producer cannot accept this record until some records are successfully flushed from the buffer.

---

Action Items:

- [ ] Implement batching (https://github.com/infinyon/fluvio/pull/1631)
- [ ] Update documentation, tutorials, and examples
- [ ] Write tests

Related:

-  #1626
-  #972

**Comment by sehz** [comment]
What happens if failure happen during delivery? For example,

producer.send(RecordKey::NULL, "A").await?;   // buffer is not full, this is queued
producer.send(RecordKey::NULL, "B").await?;  // buffer is full
producer.send(RecordKey::NULL, "C").await?; //

Where does client waits? If client doesn't wait in B then how doe it gets error?  I would argue that it is better if client waits on B so that it gets error  if something goes wrong.  This  also preserves existing semantics and simpler to understand now. Alternatively, if we don't want to wait for B, we need to provide way to get some status.   This is optimization we can defer.

**Comment by morenol** [comment]
For the initial implementation of the automatic batching, we want to add configurations to the producer to handle failures initially through retries.

Just like in the initial comment of this issue, we need to add `TopicProducer::flush()` but we also need to modify TopicProducer::send() to return something that we could use to detect failures while batching/delivering the record.

We can create a `FutureRecordMetadata` that has the following implementation:

```rust
impl Future for FutureRecordMetadata {
    type Otuput = Result<RecordMetadata, FluvioError>;


    fn poll(&mut self) -> Poll<Self::Output> { ... }
}
```
```rust
impl TopicProducer {
    /// Waits for all records to be flushed from the internal buffer
    pub async fn flush(&self) -> Result<(), FluvioError> { ... }

    pub async fn send<S, K, V>(&self,  key: K, value: V) -> Result<FutureRecordMetadata, FluvioError>
    where:
        K: Into<RecordKey>,
        V: Into<RecordData>,
    { ... }

}
```


With this in mind, in order to get status about record delivery we can await on result of send call, so
```rust
let future_ record_a_metadata = producer.send(RecordKey::NULL, "A").await?; // buffer is not full, this is queued
let future_record_b_metadata = producer.send(RecordKey::NULL, "B").await?; // buffer is full
let future_record_c_metadata = producer.send(RecordKey::NULL, "C").await?; //

// Get specific record_b_metadata
let recordb_metadata = future_record_b_metadata.await?;
```

**Comment by sehz** [comment]
close in favor of #2000
