### ISSUE TITLE
[CI] Configure Bors to run Release on PR to stable

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#1084]
The last of the simple release tasks to automate is updating `stable` branch w/r/t the `master` branch. Right now this is administratively difficult bc it is a protected branch and it needs to be unprotected for whoever is running release to update.

This will take care of 2 problems (releasing artifacts, and updating stable) as well as drive more formal process into PRs.

Related: #929

**Comment by tjtelan** [comment]
Bors doesn't need to be configured to support merging to stable. The concern is potentially requiring Bors run the CI tests twice. Once from PR to `master`, and again from PR on `master` to `stable`. I believe this is not the case.

Looking closely at the `bors.toml` [config docs](https://bors.tech/documentation/):

```
status | [pattern] | List of commit statuses that must pass on the merge commit before it is pushed to master.
```

The commit hash is equivalent from `staging` to `master` and finally to `stable`. So there should be no need to run any more tests for Bors to perform merges to `stable`.

---

What we want to do is configure the `Release` workflow to run **after** commits land in the `stable` branch. Here's the final form of this workflow.

* Devs PR to `master`. CI runs a subset of jobs we use to verify before running `bors r+`.
* On `bors r+`, Github Actions runs on CI workflow on `staging`, including the last required job needed for merge (job `Done`), then Bors pushes merge to `master`.
* Release dev PR from `master` to `stable`
* On `bors r+` Bors pushes merge to `stable`, because the required jobs have already run on this commit. Github Actions then runs on Release workflow on `stable`. This job shouldn't fail, (but the job can be re-run idempotently)

---

The Release job needs to be modified to run when Bors merges to stable.

Add:
```
on:
  push:
    branches:
      - stable
```

**Comment by tjtelan** [comment]
My testing shows this strategy kind of works.

The problem I'm having is Bors shares the `staging` and `trying` branches. So when we do our PR from `master` to `stable`, the moment a commit hits `staging`, we'll kick off jobs on CI.

Since Bors is doing this as a `push` event to `staging`, I can't distinguish the intention to merge to `master` vs the intention to merge to `stable`.

---

We might need to move some of the jobs to trigger on the push to `master`, to compensate for the ambiguity.

**Comment by sehz** [comment]
https://github.community/t/access-to-target-branch-on-push/16735/4

**Comment by tjtelan** [comment]
> https://github.community/t/access-to-target-branch-on-push/16735/4

The problem is that the target branch is `staging`, not that I can't read the base ref. 

I don't have enough context to determine if Bors is planning on merging to `master` or `stable` with that context.

So the way our workflows are written now, any push to `staging`, will 100% always trigger CI, including the jobs that are intended for when Bors merges to `master`.

**Comment by tjtelan** [comment]
Closing this in favor of #1026 since this issue is Bors focused.
