### ISSUE TITLE
Make the CLI relationship between profiles and clusters more intuitive.

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1091]
Currently, the Fluvio config defines "profiles" and "clusters" separately. This leads to some confusing commands such as:

- `fluvio profile delete <profile>`
- `fluvio profile delete-cluster <cluster>`

To a user, it may not at all be intuitive what the two different commands are needed for. I'd like for us to use this issue to brainstorm a better conceptual model for these two ideas and figure out how we can best represent them to users.

The first question I have is: Do we need to actually distinguish between profiles and clusters?
- If yes, what are the use-cases where that is necessary, and
- If no, can we consolidate these two ideas into one?

By the time we're done with this issue, we should have:

- [ ] Discussed possibilities for simplifying the config
- [ ] Identified common workflows for users and brainstormed ways to simplify them
- [ ] Implement any changes we decide need to be made
- [ ] Update the CLI Reference documentation to reflect the changes

**Comment by sehz** [comment]
kubectl has similar commands.  So maybe just better help for commands.
```
Available Commands:
  current-context Displays the current-context
  delete-cluster  Delete the specified cluster from the kubeconfig
  delete-context  Delete the specified context from the kubeconfig
  get-clusters    Display clusters defined in the kubeconfig
  get-contexts    Describe one or many contexts
  rename-context  Renames a context from the kubeconfig file.
  set             Sets an individual value in a kubeconfig file
  set-cluster     Sets a cluster entry in kubeconfig
  set-context     Sets a context entry in kubeconfig
  set-credentials Sets a user entry in kubeconfig
  unset           Unsets an individual value in a kubeconfig file
  use-context     Sets the current-context in a kubeconfig file
  view            Display merged kubeconfig settings or a specified kubeconfig file
```

**Comment by nicholastmosher** [comment]
Maybe we should also look into how kubectl documents these commands elsewhere e.g. in their reference

**Comment by sehz** [comment]
defer until we have more feedback from user
