### ISSUE TITLE
Tracking: CLI cluster install preflight check

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#112]
Before performing cluster install, we should perform series of check to ensure installation goes smooth

# For both k8 and local install
* Check if helm is installed and is right version: #119 
* Ensure current kubectl context doesn't use IP address, if not ask to perform ```minikube-context```
* Check if compatible sys chart is installed

# For minikube

* check tunnel is up and running #87 

- For AWS
[TBD]

**Comment by nacardin** [comment]
It would be helpful to also check that docker and minikube are installed and in healthy state. The with `--develop`  git and ssh are required, otherwise it would silently fail.

**Comment by sehz** [comment]
this is implemented by #145
