### ISSUE TITLE
`fluvio update` should install the latest stable release CLI by default

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#1133]
This was caught by @ajhunyady after running `fluvio update`

```bash
$ fluvio version
Fluvio CLI           : 0.8.4
Fluvio CLI SHA256    : 73ac08a8ea2b2cf9ea162c546556bcd0a12079d232e6fcf5c0b3d5d50851fcb3
Fluvio Platform      : 0.8.2 (cloud)
Git Commit           : 56bf555f6831545f5cdccd608c497d54e9c31ac2
OS Details           : Darwin 10.14.6 (kernel 18.7.0)
```

The version and git commit correspond to `VERSION=latest`, which is intended to be used during development only.

Since `0.8.4` has not yet been generally released, we shouldn't install with `fluvio update`. The expected version is the latest version from Github Releases, which is `0.8.3`

**Comment by sehz** [comment]
This should be fixed. If not, let's create another issue since this dates to old packager
