### ISSUE TITLE
feat: compress WASM binaries (SmartStream)

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#1140]
Currently WASM files are send uncompressed which can increase network delay.   A simple gzip shows that 3:1 compress ratio can be easily achieved:
```
-rwxr-xr-x  2 ubuntu docker 207285 May 29 04:22 example_filter.wasm
-rw-r--r--  1 ubuntu docker  71745 May 29 16:16 filter.gzip
```

**Comment by sehz** [comment]
Assigning to @nicholastmosher with new SmartStream API

**Comment by tomindisguise** [comment]
@sehz @nicholastmosher I'm planning to work on this issue, but am new to the codebase, so wanted to check on the approach.
I was thinking I could add a new variant (e.g. `Gzip(Vec<u8>)`) to `SmartStreamWasm`: https://github.com/infinyon/fluvio/blob/master/src/spu-schema/src/server/stream_fetch.rs#L87 that would indicate that the WASM module payload in a fetch request was gzipped.
This would naturally break "SmartStream API", as binaries on older versions don't have this capability. I noticed there were version indicators, but I am not sure of their current status or what the release/breaking change policy is: is it OK to do this change, so in `request_stream` in https://github.com/infinyon/fluvio/blob/master/src/client/src/consumer.rs#L434 it'd keep using the raw version for "SmartStream V1" (and unzip if necessary) and assume one can handle gzipped payloads in "SmartStream V2"? Or should this introduce "SmartStream V3" (and perhaps even a new field on `StreamFetchRequest`)?

**Comment by sehz** [comment]
So there are 2 compatibilities.  Rust API compatibility and protocol compatibility.  It's ok to break Rust API compatibility by bump up rust version (i.g. `0.10.0`).  However, we need to keep protocol compatibility which can be done by using `fluvio` attribute in the field.

**Comment by nicholastmosher** [comment]
@tomindisguise your approach is exactly right, `SmartStreamWasm` is indeed the place to add this kind of extension. In addition to handling the version expectations in the client code (i.e. `request_stream`), you can add a `#[fluvio(min_version = 14)]` attribute to the `SmartStreamWasm::Gzip` variant itself, which will cause that variant only to be recognized when the proper API version is used. See an example here: https://github.com/infinyon/fluvio/blob/2309cd28aab0357e6daba35fafd55c489cba4216/src/spu-schema/src/server/stream_fetch.rs#L42
