### ISSUE TITLE
Remove `minikube tunnel` from CI tests

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#1141]
When #668 is fixed and released in `0.8.4`, we will still need to wait for **one more release** before we rid our development workflow of `minikube tunnel`.

Our CI test will still need to support using minikube's `LoadBalancer` in order to run the cluster upgrade test, which uses version `0.8.3` the last version that doesn't use NodePort by default.

This should be a simple deletion of a few `minikube tunnel` related lines in the cluster upgrade job.

**Comment by sehz** [comment]
Raising priority since we need to support more K8 Cluster types

**Comment by sehz** [comment]
Done by #1206
