### ISSUE TITLE
bug: SPU should return error if smart stream WASM file is invalid

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#1143]
Currently SPU doesn't return invalid WASM file properly.  If for any reason, WASM can't be compiled correctly, it should return client the proper error code instead of continue to keep stream open.

steps to reproduce it:
```
 fluvio consume hello-smartstreams -B --smart-stream Cargo.toml 
```

**Comment by avinassh** [comment]
I thought of sending a patch to this bug, but seems this is fixed already. When I run the above: 

```sh
fluvio consume echo -B --smart-stream some-random-file
Consumer stream has closed
```

relevant error handling: https://github.com/infinyon/fluvio/blob/92be977/src/spu/src/services/public/stream_fetch.rs#L150,#L160

However, we can display the proper error in the CLI, that change can be made.

**Comment by sehz** [comment]
This bug is about propagating error to client if WASM module loading fails.  Currently SPU close stream silently.  This is also related to map capability that @nicholastmosher is working on

**Comment by nicholastmosher** [comment]
This would probably benefit from what I'm calling "error delivery" in https://github.com/infinyon/fluvio/issues/1198

**Comment by nicholastmosher** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-6140c6361f93f200184da0bf/issues/infinyon/fluvio/1143?planning-poker) with ZenHub @morenol @nacardin @sehz @tjtelan @simlay
