### ISSUE TITLE
Platform support: Arm32 for Raspberry pi v3 (Arm7)

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#1160]
Support IOT use cases.

**Comment by nicholastmosher** [comment]
I have been able to build for 32-bit raspberry pi using the following:

```
cross build --bin fluvio --target=arm-unknown-linux-gnueabifh
```

We should incorporate this into the `TARGET`s so that we can use `TARGET=arm-unknown-linux-gnueabihf make build-cli` and publish this target in CI.

**Comment by sehz** [comment]
use if Zig possible.  No cluster admin support.  Need installer support

**Comment by nicholastmosher** [comment]
https://github.com/infinyon/fluvio/issues/1269
