### ISSUE TITLE
flv-test - Add instrumentation to test driver

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#1166]
Modify the test driver to assist in collecting statistics during a test run.

Creating topics (to collect # topics and partitions created)
Keeping track of producers (mapping producers to topics)
Keeping track of consumers (mapping consumers to topics)

---

And measuring throughput, latency

Open Messaging Benchmark utilizes a library (which has a Rust port), [HdrHistogram](https://hdrhistogram.github.io/HdrHistogram/), which may handle a lot of the basic reporting we'd like to collect.

**Comment by tjtelan** [comment]
The current state of https://github.com/tjtelan/fluvio/tree/flv-test-stats only works for single-threaded tests. I'm limited due to errors like this:

```rust
error: future cannot be sent between threads safely
  --> tests/runner/src/tests/concurrent/mod.rs:64:5
   |
64 |     spawn(consumer::consumer_stream(
   |     ^^^^^ future returned by `consumer_stream` is not `Send`
   | 
  ::: /Users/telant/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/spawn.rs:28:29
   |
28 |     F: Future<Output = T> + Send + 'static,
   |                             ---- required by this bound in `fluvio_future::task::spawn`
   |
   = help: within `impl Future`, the trait `Send` is not implemented for `std::sync::RwLockWriteGuard<'_, FluvioTestDriver>`
note: future is not `Send` as this value is used across an await
  --> tests/runner/src/tests/concurrent/consumer.rs:24:34
   |
15 |     let mut lock = test_driver.write().unwrap();
   |         -------- has type `std::sync::RwLockWriteGuard<'_, FluvioTestDriver>` which is not `Send`
...
24 |     while let Some(Ok(record)) = stream.next().await {
   |                                  ^^^^^^^^^^^^^^^^^^^ await occurs here, with `mut lock` maybe used later
...
37 | }
   | - `mut lock` is later dropped here

error: aborting due to previous error

error: could not compile `flv-test`
```

---

I think that I might need a completely different strategy to collect measurements in a concurrent manner. Open Messaging Benchmark starts a webserver for stats collection, and their test driver just makes POST calls to record scalar values. This might be a more pragmatic approach.

**Comment by nicholastmosher** [comment]
I noticed you are using a `std::sync::RwLock` in your `async fn`. What would happen if you used an async-aware `RwLock` instead?

**Comment by nicholastmosher** [comment]
It seems like using `async_lock::RwLock` fixes it

https://github.com/tjtelan/fluvio/pull/1
