### ISSUE TITLE
Implement transform (map) SmartStream

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1172]
Following the initial "filtering" smartstream `#[smartstream(filter)]`, we should now implement a "mapping" smartstream that takes Records as input and allows users to edit them and transform them.

Here is the current proposal for the SmartStream Map API:

```rust
use fluvio_smartstream::{smartstream, Record, RecordData};

#[smartstream(map)]
fn map(record: &Record) -> (Option<RecordData>, RecordData) {
    let key = record.key.cloned();
    let mut value = Vec::from(record.value.as_ref());

    value.make_ascii_uppercase();
    (key, value.into())
}
```

In this API:

- A Record is passed by reference, allowing full visibility into the Record and its metadata (e.g. offset)
- The input record is immutable, meaning that it is transparent to view but closed for modification
- The SmartStream returns a tuple of an optional key and a new record value

**Comment by sehz** [comment]
Please update proposal for API in this issue.

**Comment by nicholastmosher** [comment]
@sehz I updated the comment with the current API proposal, and some examples of how it may be used. Let me know if you have any feedback.

**Comment by sehz** [comment]
Don't think we should support mutation nor return record.  Record may contain other metadata which are only valid as input.

**Comment by nicholastmosher** [comment]
Ok, what would you think about something like this:

```rust
use fluvio_smartstream::{smartstream, Record, RecordData};

#[smartstream(map)]
fn map(record: &Record) -> RecordData {
    let mut value = Vec::from(record.value.as_ref()); // Copy data into our own Vec
    value.make_ascii_uppercase(); // Modify or otherwise use the value in some useful way
    let modified_record_data = RecordData::from(value);
    modified_record_data
}
```

In this API we don't allow mutation of Record internals, which gives visibility to metadata like the offset and key, but no way to edit it. By using `RecordData` as a return type, we don't let them control the metadata of the Record (including the Key), but we do let them return essentially an arbitrary value. (note, you can build a `RecordData` out of anything that implements `Into<Vec<u8>>`).

My number 1 question about this API design is: Do we want to allow users to modify the key, or no? I think for a first implementation, not being able to edit the key is fine. I think this is especially true because SmartStreams are sort of transient/temporary right now (i.e. the edited records are not stored anywhere permanently). Maybe we'll want to allow users to derive new keys in future versions (i.e. perhaps in Derived Streams), but for now I think this will work nicely.

Thoughts?

**Comment by sehz** [comment]
We should support transforming key as well as value. Here are possibilities

no key, old_value => no key, new value
old key, old value => no key, new value
old key, old value => old key, new value
old key, old value => new key, new value

out of this, key1,value1 => key1, value2 is probably most common and we should make it easier for that transformation

**Comment by nicholastmosher** [comment]
Ok, what about something like this:

```rust
#[smartstream(map)]
pub fn map(record: &Record) -> (Option<RecordData>, RecordData) {
    let key = record.key.clone();
    let mut value = Vec::from(record.value.as_ref());

    value.make_ascii_uppercase();
    (key, RecordData::from(value))
}
```

This way, we have:

- Read access to all of the contents of the input Record (key, value, offset, etc.)
- NO write access directly to the input Record

Also, we can use the return values to achieve the following scenarios:

- Pass the key directly through with `(key, value)`
- Drop the key using `(None, value)`
- Generate a new key using `(Some(RecordData::from("my new key")), value)`

**Comment by sehz** [comment]
Ok.  that works.  

Can you also make map example simpler?  For example, use into() such that explicit Record data creation is not needed

**Comment by nicholastmosher** [comment]
Sure. I think the simplest we can get is something like this:

```rust
#[smartstream(map)]
pub fn map(record: &Record) -> (Option<RecordData>, RecordData) {
    let key = record.key.clone();
    let mut value = Vec::from(record.value.as_ref());

    value.make_ascii_uppercase();
    (key, value.into())
}
```

Unfortunately I don't think we can get rid of the `RecordData` import since we need those in the function signature. But this should work nicely I think.

**Comment by sehz** [comment]
This is good enough for first iteration of map function.  Nice job
