### ISSUE TITLE
Add `#[smartstream(aggregate)]` API

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1173]
Another type of SmartStream we want to support is one for aggregations (folding). My thinking right now is to just provide an "accumulator Record" to the SmartStream fold function on each iteration, and have the fold function return the new aggregate Record. For example:

```rust
use fluvio_smartstream::{smartstream, Record, RecordData};

#[smartstream(aggregate)]
fn aggregate(accumulator: &Record, next: &Record) -> RecordData {
    todo!()
}
```

Let's imagine that our input stream is a set of records that are UTF-8 strings containing numbers we want to add together

```
topic-numbers:
["1", "2", "3", "4", "5", "6", "7", "8", "9"]
```

We want to write an aggregation so that our output stream gives the following:

```
["1", "3", "6", "10", "15", "21", "28", "36", "45"]
```

The implementation of this SmartStream would look like the following:

```rust
use fluvio_smartstream::{smartstream, Record, RecordData};

#[smartstream(aggregate)]
fn aggregate(accumulator: &Record, next: &Record) -> RecordData {
    let acc_value = Vec::from(accumulator.value.as_ref());

    // Parse the accumulator's number
    let acc_number_result = std::str::from_utf8(acc_value)
        .and_then(|s| s.parse::<u32>());
    let acc_number: u32 = match acc_number_result {
        Ok(n) => n,
        Err(_) => return acc_value.into(),
    };

    // Parse the current record's number
    let next_number_result = std::str::from_utf8(next.value.as_ref())
        .and_then(|s| s.parse::<u32>());
    let next_number = match next_number_result {
        Ok(n) => n,
        Err(_) => return acc_value.into(),
    };

    let next_acc_number = acc_number + next_number;
    let next_acc_string = format!("{}", next_acc_number);
    next_acc_string.into()
}
```

---

## CLI

In order to support aggregation, we'll make the following changes to the CLI:

```
fluvio consume <topic> --smart-stream // DEPRECATE
fluvio consume <topic> --filter=filter.wasm
fluivo consume <topic> --map=map.wasm
fluvio consume <topic> --aggregate=aggregator.wasm --initial=initial.txt
```

**Comment by nicholastmosher** [comment]
@sehz I have been thinking about the API design for the `#[smartstream(fold]`, I put my latest thoughts in the issue description. I'd like to hear your thoughts when you have a chance.

**Comment by ajhunyady** [comment]
@nicholastmosher I don't hear the term fold when I talk to users. I suggest we change `fold` be `aggregate`.

**Comment by sehz** [comment]
https://en.wikipedia.org/wiki/Fold_(higher-order_function).

KStream uses fold, Flink uses aggegrate.  Nodejs/JS, Scala, Rust uses `reduce`.

**Comment by ajhunyady** [comment]
Does it mean that every time I need an aggregate I need to provision a new stream?

**Comment by sehz** [comment]
No, `aggegrate/fold/reducer` will do is keep `accumulator` which will be hold by SPU. For every records, it will pass to WASM function which will update to next state.  For example, to implement sum, it will just need to increase accumulator

**Comment by nicholastmosher** [comment]
Aggregations can be "consumer stream" style or "derived stream" style (once we have that). But rather than an aggregation just being one end result, it essentially looks like a stream where each element is the "current" total sum

**Comment by ajhunyady** [comment]
So, the SPU keeps all aggregates in memory. If I start an aggregate from offset 0 and another one from offset 10, they will both work correctly.

**Comment by ajhunyady** [comment]
Also, can I use a data structure with multiple values and compute multiple aggregates in parallel?

**Comment by nicholastmosher** [comment]
Here is a diagram from a quick brainstorming during standup today:

<img width="2014" alt="image" src="https://user-images.githubusercontent.com/4210949/122982428-d9db0080-d368-11eb-9327-369ab9a39bdf.png">

@ajhunyady you brought up a very good point here which caused me to start thinking

> So, the SPU keeps all aggregates in memory. If I start an aggregate from offset 0 and another one from offset 10, they will both work concurrently and compute the correct value.

We are now thinking that an aggregation should work in the following way:

- A consumer asks to consume from offset X with aggregating-SmartStream Y, using initial value Z

So, rather than aggregating from the beginning of time, the consumer stream starts aggregating from the offset of the first _requested_ record. This actually makes a lot of sense if you start to think about retention: we will not always have all records from the beginning of time. Instead, we can jump into the middle of a stream and say "hey, start counting from 100" and we will get a sort of "relative aggregation" from that point forward.

**Comment by nicholastmosher** [comment]
> Also, can I use a data structure with multiple values and compute multiple aggregates in parallel?

Yes, the aggregation value may be anything. Let's imagine a scenario where we are counting GitHub stars for three different repos. Each record in our Topic is the number of stars gained each day for those three repos, something like this:

```json
{
    "infinyon/fluvio": 10,
    "infinyon/node-bindgen": 8,
    "infinyon/fluvio-client-node": 6
}
```

We could imagine after a week, our aggregate object would look something like this:

```json
{
    "infinyon/fluvio": 70,
    "infinyon/node-bindgen": 56,
    "infinyon/fluvio-client-node": 48,
}
```

**Comment by ajhunyady** [comment]
Everything above sounds pretty good to me.
Except, why would an aggregate from offset 0 fail?

**Comment by nicholastmosher** [comment]
An aggregate from 0 would not fail, what part of what I was saying made you think that (just curious)? The point I think I was trying to make was that, at first I imagined that _all_ aggregates would begin at offset zero, whereas now we have come up with a way to begin an aggregation at an offset greater than zero (by supplying an aggregate value to begin from).

**Comment by ajhunyady** [comment]
@nicholastmosher In implementaiton options: "1) Aggregation start at offset 0 always `x`."

**Comment by nicholastmosher** [comment]
Ah I see. I think originally I was thinking we could not accomplish aggregation from an arbitrary offset without having persistent derived streams. That list was my way of brainstorming possible workarounds.

That particular workaround involved introducing a limitation where we would not allow consumers to aggregate starting from any offset other than 0. So if you wanted to get the aggregation of the stream at offsets 100, 101, 102, ... you could not just _start counting_ at 100, you would need to start counting at 0 and work your way up to 100, then send only 100, 101, 102 to the consumer.

We put an ❌ there because we decided that was a bad idea, and instead we could do this "relative aggregation" where we instead say "start aggregating at offset 100, and your initial value is xyz".

**Comment by ajhunyady** [comment]
I suggest removing whatever you decided against to eliminate confusion.

**Comment by nicholastmosher** [comment]
I updated the diagram to remove that point for confusion 👍

**Comment by ajhunyady** [comment]
![image](https://user-images.githubusercontent.com/26554085/122995652-b9a64400-d35e-11eb-99c4-d9408930b35f.png)
I believe you meant "From the offset 40 - an absolute value"
