### ISSUE TITLE
Investigate clash between Fluvio and Fluvio Cloud installations on the same Kubernetes instance

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1176]
There is an error that sometimes occurs when installing a local Fluvio cluster when you also have Fluvio Cloud running in the same Kubernetes cluster. We believe this error is caused by a clash in the CRD's from the Fluvio system charts. Today, fixing this error can be done in one of two ways:

- Deleting all of the infinyon CRDs from the cluster, or
- Nuking the cluster via `minikube delete && minikube start`

This can cost a lot of time during development, so if we can fix this it should help with productivity.

**Action Item**

- [ ] Update system chart check to search all namespaces for `fluvio-sys`

**Comment by nicholastmosher** [comment]
I just tested this and the problem is in fact caused by trying to `helm install` the fluvio-sys charts when they have already been installed by Fluvio Cloud. This can be avoided by using `fluvio cluster start --local --skip-checks`.

The `fluvio-cluster` crate already has logic to check if the system charts have been installed, but I think this check is failing in this case because Fluvio Cloud installs the system charts in the `fluvio-cloud` namespace on Kubernetes, rather than in `default`, which is where the check happens.

I think the easiest way to fix this is to make the `fluvio-cluster` check search all namespaces for a `fluvio-sys` chart when trying to detect whether the system chart is installed.

**Comment by sehz** [comment]
@simlay can you try using skip check flag see if it works?

**Comment by simlay** [comment]
Oh nice. This did work. Thanks!

**Comment by nicholastmosher** [comment]
Once we publish the next patch version of `fluvio-helm` this should work itself out when it gets pulled in by Cargo.
