### ISSUE TITLE
Add a SmartStream filter example using Regex

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1177]
It would be nice to demonstrate a SmartStream accepting or rejecting records based on using a Regex to search for substrings in the Record. I'm imagining a regex that searches for `XXX-XX-XXXX` (imagine scrubbing social-security numbers), and rejecting matching records.

@ajhunyady feel free to post any example scenarios you think would be good to show off with regex.

**Comment by ajhunyady** [comment]
@nicholastmosher, nice use case!
