### ISSUE TITLE
`fluvio partition list` should sort by Topic, then by Partition number

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1181]
Currently, whenever we use `fluvio partition list`, the output comes out in no particular order

```
 TOPIC  PARTITION  LEADER  REPLICAS  RESOLUTION  HW  LEO  LSR  FOLLOWER OFFSETS
 multi  3          0       []        Online      5   5    0    []
 multi  2          0       []        Online      3   3    0    []
 multi  0          0       []        Online      0   0    0    []
 multi  4          0       []        Online      2   2    0    []
 multi  1          0       []        Online      0   0    0    []
```

It is confusing to read this, because the partitions are out of order. Even worse, when there are multiple Topics, then the partitions of many topics can get mixed among each other. We should sort this list:

- First sort by Topic,
- Then sort by Partition number

With this fix, the above list should instead look like:

```
TOPIC  PARTITION  LEADER  REPLICAS  RESOLUTION  HW  LEO  LSR  FOLLOWER OFFSETS
multi  0          0       []        Online      0   0    0    []
multi  1          0       []        Online      0   0    0    []
multi  2          0       []        Online      3   3    0    []
multi  3          0       []        Online      5   5    0    []
multi  4          0       []        Online      2   2    0    []
```

**Comment by sehz** [comment]
I agree, this is nice to have, but filter should be more useful.

**Comment by ajhunyady** [comment]
Filters is nice to have, we should have `topic centric` look-up:

fluvio partition list --topic <topic-name>

This is what I did yesterday to get around this:

```
$ fluvio partition list | grep multi
 multi               1          0       []        Online      2   2    0    [] 
 multi               2          0       []        Online      2   2    0    [] 
 multi               0          0       []        Online      3   3    0    [] 
```

**Comment by ajhunyady** [comment]
@nicholastmosher, items should be sorted by topic (and partition id if not too hard). Otherwise, just topic would be good enough.
