### ISSUE TITLE
Rename `fluvio profile view` to `fluvio profile list`

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1185]
Per @ajhunyady's request:

- Rename `fluvio profile view` to `fluvio profile list`
- Add alias so that `fluvio profile` acts the same as `fluvio profile current`

**Comment by ajhunyady** [comment]
Thank you @nicholastmosher

**Comment by nicholastmosher** [comment]
In #1186:

<img width="521" alt="image" src="https://user-images.githubusercontent.com/4210949/122933592-c87bff00-d33c-11eb-8e53-1d4a5b7f0a5c.png">
