### ISSUE TITLE
[Bug]:Broken link in hello world tutorial

### ISSUE THREAD

**Issue by mjgarton** [infinyon/fluvio#1191]
**What happened**
Broken link in hello world tutorial

**Expected behavior**
A working link

**How to reproduce it (as minimally and precisely as possible)**
1. Go to https://www.infinyon.com/tutorials/rust/hello-world/
2. Click the "getting started" link
3. See a 404 page.

**Comment by nicholastmosher** [comment]
Hi @mjgarton, thanks for the report! I'll get right on fixing that. In the meantime if you are looking to get started, you can check out the main docs page here: https://www.fluvio.io/docs/ and the "getting started" guides are now sorted by OS on the top left :)
