### ISSUE TITLE
Error reporting for SmartStreams

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1198]
The current API for SmartStreams does not provide much room for error management. Right now we have Map and Filter implemented with these APIs:

```rust
fn filter(record: &Record) -> bool {}
fn map(record: &Record) -> (Option<RecordData>, RecordData) {} // (Key, Value)
```

Both of these return types are "infallible", meaning that an implementor _must_ provide a "successful" return value. This is easy to hand-wave with Filter, because if something fails you can "just return false". But this approach will not support debugging very well, and furthermore it does not account for the possibility of failures in Map.

For example, in a Map, we may be expecting input records to be JSON, but receive records that do not parse correctly. We should have a way to indicate when errors occur and what the errors were.

So it seems right away that the APIs should look more like this:

```rust
fn filter(record: &Record) -> Result<bool, SmartStreamError> {} // Where the details of SmartStreamError are TBD
fn map(record: &Record) -> Result<(Option<RecordData>, RecordData), SmartStreamError> {}
```

> Note, another approach would be with a trait, e.g. `-> Result<bool, impl SmartStreamError>` for Filter

Another question that needs answering is what to do when a SmartStream panics. We will need to investigate how wasmtime propagates panics (trapping mechanism) and how to communicate information to the host during a panic.

We will have some constraints on the `SmartStreamError` type (or trait), based on the following limitations:

- Passing values over the WASM boundary essentially requires serializing to bytes and back
- This implies that we should have some type of bound like `SmartStreamError: Serialize + Deserialize` (either using serde or another encoding scheme such as `fluvio_protocol::{Encode, Decode}`

### Design Update

As of now, here is the plan for the error handling interface:

- Create a type `fluvio_smartstream::Result` which is aliased as `type Result<T> = eyre::Result<T>`
  - This is used because it implements `From<E> where E: std::error::Error`, i.e. any error type we are likely to see
- Create a wrapper `struct SmartStreamResult<T> where T: Encode + Decode` which wraps a `Result<T, String>`
  - When we get the `eyre::Result<T>` back from the SmartStream call, if it is `Err` we convert it to a Stringified representation of the error and wrap that in `SmartStreamResult<T>`
  - We also implement `SmartStreamResult<T>: Encode + Decode` so we can serialize it to pass across the WASM boundary.

---

The next question after figuring out how to capture and collect errors is how to report them. Some options are:

- Upon error, end the consumer stream with the error as the last item in the stream
- Upon error, inject the serialized error into the data stream and continue data processing
- Create a dedicated "errors" topic where errors are sent to be viewed later, preserving the original stream for "successful" data only

I think at this stage, the best course of action would be the first of these, as it will be the simplest to implement and begin to collect feedback for further use-cases. I imagine we will want to revisit this at some time in the future.

---

## Action Items

- [x] Design a type/trait `SmartStreamError` (name flexible) for reporting errors
- [x] Implement "error delivery" by halting a consumer stream and terminating it with the responsible error value

**Comment by sehz** [comment]
I agree, we should do most simplest (option 1). However, distinguish error for last return is also requires changes to protocol.  Instead I suggest we add new API to SPU.
```
    LastStreamFetchError = 1006
```

Whenever SPU encounters any error during stream, it will store error in temporary cache which can be retrieved by this API.  Cache will be automatically purged after 24h or fixed time period.

**Comment by sehz** [comment]
Can you add example using `Result`?

**Comment by nicholastmosher** [comment]
Added 👍
