### ISSUE TITLE
Update relative offset resolution to be saturating

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1210]
Right now, using relative offsets `Offset::from_beginning(X)` or `Offset::from_end(X)` when fetching from a partition have undesirable behavior when X is greater than the number of records in that partition. When this happens, a stream request will just hang. Instead, I think that the relative offset resolution should be _saturating_, meaning that:

If `n` is the size of the partition, then

- When we fetch using `Offset::from_end(X)` and `X > n`, then the fetch should resolve to absolute offset `0`
- When we fetch using `Offset::from_beginning(X)` and `X > n`, then the fetch should resolve to absolute offset `X-1`

The end result of this is that no call to `fetch` should ever cause the client to hang.

Related: https://github.com/infinyon/fluvio/issues/1007

**Comment by sehz** [comment]
find root cause
