### ISSUE TITLE
Add `fluvio diagnostics` for collecting useful debugging information

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1215]
When debugging a problem with Fluvio, it is useful to have a bunch of information such as:

- Logs
- Tooling info (e.g. `kubectl version`, `helm version`, etc.)
- Host info (uname)
- Profile type
- etc.

Some of this information is given by `fluvio version`, but it'd be nice to have an all-in-one command that produces a `.zip` file that we can collect when something goes wrong, to make it easier to report bugs.

**Comment by sehz** [comment]
Let's roll into `cluster check` command.  We can add different flags `--platform` ``-network` for different check

**Comment by nicholastmosher** [comment]
I think this is still worth having, going to remove the stale label
