### ISSUE TITLE
[Bug]: Unable to install in Rancher kubernetes cluster

### ISSUE THREAD

**Issue by cortopy** [infinyon/fluvio#1220]
**What happened**
I tried to follow the Getting Started guide but couldn't make fluvio work

**Expected behavior**
Fluvio CLI creates a new fluvio cluster in my kubernetes cluster

**Describe the setup**
- I'm just following the instructions in the [docs](https://www.fluvio.io/docs/get-started/linux/)
- What version of Fluvio are you using? 0.8.4

**How to reproduce it (as minimally and precisely as possible)**
1. Have a Kubernetes cluster deployed with Rancher
2. Install the CRDs using `fluvio cluster start --sys` (this works ok)
3. Then run `fluvio cluster start`

I get this error:

```
Error: 
   0: Fluvio cluster error
   1: Fluvio cluster error
   2: Failed to install Fluvio on Kubernetes
   3: Kubernetes client error
   4: no client cert crt path founded
   5: no client cert crt path founded
```

In most setups, one can connect with a downstream Rancher k8s cluster using the [Rancher proxy](https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cluster-access/kubectl/#accessing-clusters-with-kubectl-from-your-workstation). In my case, the proxy is already using a TLS certificate issued by a well-known authority (Cloudflare), and so I don't have to have any certificate configuration in my kube config file.

The strange thing though is that the command `fluvio cluster start --sys` works fine

Since the error is about certificates, I've tried connecting directly with the downstream cluster (which in my setup is quite difficult as I have to disable firewalls, etc.). But even in this case I'm also getting an error

```
✅ ok: Kubernetes config is loadable
✅ ok: Supported helm version is installed
✅ ok: Fixed: Missing Fluvio system charts.
✅ ok: Previous fluvio installation not found
Error: 
   0: Fluvio cluster error
   1: Fluvio cluster error
   2: Failed to install Fluvio on Kubernetes
   3: Kubernetes client error
   4: client error: 401 Unauthorized
```

**Log output**
I didn't manage to install Fluvio, so I have no logs

**Environment (please complete the following information):**
 - OS: Linux
 - Fluvio Version 0.8.4
 - Minikube version (if used): N/A
 - Kubernetes version: 1.20.4

**Comment by sehz** [comment]
Hi @cortopy, Thanks for reporting issue.  We are currently working on installation for k3d and other Kubernetes distribution: https://github.com/infinyon/fluvio/issues/1193.   Meantime, can you try using minikube?

**Comment by cortopy** [comment]
thanks for that @sehz ! I'm looking forward to that

In the meantime, I'm also getting an error with minikube:

```
✅ ok: Kubernetes config is loadable
✅ ok: Supported helm version is installed
✅ ok: Fixed: Missing Fluvio system charts.
✅ ok: Previous fluvio installation not found
Jul 10 21:40:30.497 ERROR fluvio_cluster::start::k8: timeout for SC port check sock_addr=192.168.49.2:31329
Error: 
   0: Fluvio cluster error
   1: Fluvio cluster error
   2: Failed to install Fluvio on Kubernetes
   3: Unable to detect Fluvio SC K8 service

```

This is on a brand new minikube cluster as it's the first time I use it.

The sc pod has started but it logs many errors like: 
```
Jul 10 20:39:41.693 ERROR outer_loop{self=Partition K8StateDispatcher namespace="default"}: fluvio_stream_dispatcher::dispatcher::k8_dispatcher: cannot retrieve K8 store objects: error retrieving k8: error trying to connect: failed to lookup address information: Try again
```

I guess it's not related to this issue, but I'm not familiar with minikube at all. 

Is there a way to deploy fluvio without the cli? Being able to deploy a helm chart directly would be easier when these things fail and would allow me to get started on my environment

**Comment by sehz** [comment]
Looks like doc was not updated.  We haven't validated with Kubernetes version 1.20. Can you try to delete minikube and re-install with v1.19?

```
minikube delete
minikube start  --kubernetes-version 1.19.6
```

I will update the doc as well.   Regarding the `helm`, we do have charts but requires more detail documentation to install it correctly due to number of configuration.   With next version, it should be make easy to deploy to any version of Kubernetes.

**Comment by sehz** [comment]
this works in 0.9.0
