### ISSUE TITLE
cli crate doesn't build without consumer feature flag

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#1255]
`cargo check --manifest-path ./src/cli/Cargo.toml --no-default-features` returns errors when it shouldn't.

**Comment by sehz** [comment]
have you tried `cargo check --p fluvio-cli --no-default-features`?

**Comment by simlay** [comment]
After discussion in triage meeting, we should remove the `consumer` feature flag to the CLI and just assume we always support consuming via the cli.
