### ISSUE TITLE
[Bug]: TLS error in `fluvio install`

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1273]
We noticed in the `CD_Dev` workflow that the `install.sh` script was failing when using `VERSION=latest`:

https://github.com/infinyon/fluvio/runs/3120104226?check_suite_focus=true

![image](https://user-images.githubusercontent.com/4210949/126509730-7ca60643-67f7-4b7e-8e08-392bcabbb747.png)

After some digging, I figured out that this is a TLS problem introduced in https://github.com/infinyon/fluvio/commit/4ffcaa66376d9bf95232058db4e137d0485be19c when we switched from `fluvio_future::native_tls` to `fluvio_future::openssl_tls`. It affects all http calls in the CLI, which includes `fluvio install` and `fluvio update`.

This was the code change that caused this:

https://github.com/infinyon/fluvio/blob/4ffcaa66376d9bf95232058db4e137d0485be19c/src/cli/src/http.rs#L39-L42

**Comment by nicholastmosher** [comment]
For posterity, the way I found this commit was the following:

```
git bisect good v0.8.4
git bisect bad upstream/master
git bisect run ./bisect.sh
```

where `bisect.sh` is

```
#!/usr/bin/env bash

_output=$(cat <(cargo run --bin fluvio -- install fluvio-cloud 2>&1) | tee /dev/fd/2)
grep -v Handshake <(echo $_output)
```

**Comment by sehz** [comment]
that's nice trick!

**Comment by sehz** [comment]
CD flow detected problem:  https://github.com/infinyon/fluvio/actions/runs/1046829991.

In addition to fix this problem, 
* Add CD status to badge
* Way to test issue with packager before publishing. @nicholastmosher

**Comment by sehz** [comment]
Can replicate this with: ```curl -fsS https://packages.fluvio.io/v1/install.sh | VERSION=latest bash```
