### ISSUE TITLE
Rename LSR to LRS

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1296]
- https://github.com/infinyon/fluvio/blob/a3b5074add2983180db4693367efe08c88eeb16b/src/controlplane-metadata/src/partition/status.rs#L88
- https://github.com/infinyon/fluvio/blob/a3b5074add2983180db4693367efe08c88eeb16b/src/controlplane-metadata/src/partition/status.rs#L32

**Comment by nicholastmosher** [comment]
bors try

**Comment by nacardin** [comment]
Live set of replicas
