### ISSUE TITLE
Remove `consumer` hierarchy from CLI modules and errors

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1308]
Right now, the non-admin commands of Fluvio are oddly organized as being "consumer" commands, when it would make sense for them to be considered top-level commands. This hierarchy is reflected in the module structure and the error structure of the CLI, which can lead to some confusing error messages such as a "consumer error" when producing:

```
 $ fluvio produce test2                    
Error: 
   0: Consumer Error
   1: Fluvio client error
   2: Topic not found: test2
```

We should:

- [ ] Flatten the CLI module structure, removing the `consumer` grouping for topic, partition, produce, consumer
- [ ] Flatten the error types, removing the ConsumerError type that wraps other CLI errors

**Comment by sehz** [comment]
Make sense. But also, we need to fix the error reporting.  In this context, only relevant is "Topic not found"
