### ISSUE TITLE
feature: add "channel" concept

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#1320]
Similar to "Rustup", we should add concept of multiple release channels.
Currently, we can't install k8 cluster for latest release because it default to 'stable' image tag.  It need some kind of metadata to tell to install "latest" image tag.

**Comment by tjtelan** [comment]
Related: #1663

**Comment by tjtelan** [comment]
The goals of this issue are exactly the same as #1663. I'll close this issue as duplicate and scope out more of the user experience details in #1663
