### ISSUE TITLE
Add `#[smartstream(flat_map)]` API

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1335]
It is often desirable to take the contents of one input Record and produce multiple output Records as a result of this. An example use-case is where an input record is a JSON array of objects, and the output should be one record per object in that list.

This supersedes the desire for a `#[smartstream(filter_map)]` because `flat_map` is strictly more general than `filter_map`. That is, everything filter_map can do, flat_map can do, but not vice-versa.

The API for `flat_map` should look something like this:

```rust
use fluvio_smartstream::{smartstream, Result, Record, RecordData};

#[smartstream(flat_map)]
fn flat_map(record: &Record) -> Result<Vec<(Option<RecordData>, RecordData)>> {
    ...

    // Return a Vec of records, may be empty
    Ok(vec![...])
}
```

**Comment by sehz** [comment]
let's defer per planning
