### ISSUE TITLE
Add Fluvio CLI subcommand for Windows build to perform initial setup

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1371]
In Unix environment, the recommended way to install Fluvio is via `install.sh`, which performs some setup tasks like creating the `.fluvio` directory and downloading some plugins like `fluvio-cloud` and `fluvio-run`. Since Windows does not have an install script, it would be nice to create a subcommand like `fluvio setup` or `fluvio init` that does those setup tasks for Windows.

Another option is to have `fluvio.exe` just check whether it has been initialized (e.g. check if `.fluvio` exists) and automatically prompt the user to perform initialization, no subcommand required.

**Comment by simlay** [comment]
> Another option is to have fluvio.exe just check whether it has been initialized (e.g. check if .fluvio exists) and automatically prompt the user to perform initialization, no subcommand required. 

Looks like the call to [`fluvio_base_dir`](https://github.com/infinyon/fluvio/blob/7a38083c7710dc118a6fce9f101bbc0bc619086e/src/cli/src/install/mod.rs#L12-L31) creates the directory if it doesn't exist and likewise for the extensions directory. So, it looks like the initial call to `fluvio` does the setup steps.

**Comment by nicholastmosher** [comment]
There is also the matter of installing `fluvio-cloud` if it is not yet installed.

**Comment by simlay** [comment]
> There is also the matter of installing `fluvio-cloud` if it is not yet installed.

Hmm, I think the open source version of `fluvio` shouldn't auto-install `fluvio-cloud` when running a setup/init. Having the user run `fluvio.exe install fluvio/fluvio-cloud` seems limke an okay amount of work for the user. I'm sure we may eventually have more items that are nice to install but we're not there yet.
