### ISSUE TITLE
Need release validation flow

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#1416]
To ensure release process has built right image and binaries.  It doesn't need to be full brown CD deployment.  At min

- [x] Ensure CLI/Installer has right version and checksum
- [x] Docker image has right binaries.

This should trigger after release flow

**Comment by tjtelan** [comment]
This can be another step in the release workflow that depends on `bump_stable_fluvio`.

To verify the public installation, I'll install via curl and save the installer output to verify the installer output, and then use `fluvio version` to verify the checksum.

For the docker image, I'll pull the docker image and verify a container's `fluvio version` output.
