### ISSUE TITLE
Add more visual progress indication to `fluvio cluster start`

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1445]
Currently, `fluvio cluster start` has some good visual output when it goes to check if the system is ready to install Fluvio on, but during the actual installation there is much less feedback about the progress of the installation itself.

Some feedback to include:

- Whether the SPU specs have been successfully uploaded
- Whether the SC has been launched
- Whether each SPU has been launched

If you can think of more status indicators that would be nice feel free to add them to the list

- [x] --local --setup
- [x] --local

**Comment by sehz** [comment]
For each of the check, we need to show what they have discovered.  for examples version of kubernetes, helm.
Show progress indicator anything longer than 1s
