### ISSUE TITLE
Track: CLI syncing profiles from cloud

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#147]
# Purpose
To allow a user to import a list of cluster profiles from remote sources easily.

# Background:
Fluvio CLI maintains a list of cluster profiles to store address and access configuration (such as TLS, access key, etc.)  to reach fluvio clusters.  

# Requirements:
Make it easier to download cluster profiles from remote sources (such as fluvio cloud) with minimum hassle.  
Users should be able to keep downloaded cluster profiles and manage them locally (please see fluvio command ```profile``)

There are two solutions proposed:
Users need to authenticate with remote clusters manager (i.g. Fluvio cloud), then copy and paste the download link to Fluvio CLI.
Provide additional command in the CLI to authenticate against the remote manager and download the cluster profiles directly.

We have chosen to implement 2nd solutions because the first solution
Adds the extra burden for remote cluster managers to implement UI for the download link. 
The user has to perform additional steps.

# Propose solution:

New top-level keyword ```sync``` is introduced to unify sync of profiles from any sources.  Existing profiles commands are also simplified.  

```
fluvio profile <SUBCOMMAND>
FLAGS:
    -h, --help    Prints help information
SUBCOMMANDS:
    current                 Display the current context
    delete                  Delete a profile
    switch                  Switch to another profile
    sync                    Synchronize a profile from remote source
    view                    Display entire configuration
    help   
```

Then ```sync``` command should as below:
```
fluvio profile sync <SUBCOMMAND>
FLAGS:
    -h, --help    Prints help information
SUBCOMMANDS:
    local              synchronize profile from cluster running locally
    k8                 synchronize profile from cluster running Kubernetes
    cloud              synchronize profile from cluster running in Fluvio Cloud
    help
```

New ```sync cloud```  will authenticate against the remote source.   Any necessary user name and password will be prompted with essential masks.  

## Syncing clusters from Remote cluster profile:

The syncing operations follow the same principle as existing sync to ```local ``` and ```k8```.

Steps as follows:
* Retrieve cluster profiles from remote sources.
* For each cluster profiles,
   - Copy to local fluvio config file if the matching cluster doesn't exist.
   - Replace existing local config if it exists

## Authentication expiration

When authentication token has expired, the remote cluster profiles in the local fluvio config not modified..

**Comment by nicholastmosher** [comment]
@sehz 

I'm thinking about how to go about saving the login credentials. I think the easiest way to do that would be to save the username and password in the `~/.fluvio/config` file, taking the stance that the user's computer should be within their own trust boundary and so saving the credentials there should be fine. A more advanced (and time-consuming approach) might be to do what [docker login](https://docs.docker.com/engine/reference/commandline/login/#credentials-store) has started doing and integrating with native OS credential stores such as the Mac OS keychain. I think that might be overkill for now but it may be a future possibility.

A middleground idea might be to create a different file for credentials (e.g. `~/.fluvio/login`) and make sure that the file permissions on it are user-read-only (`chmod 400`). An added bonus to this idea is that "logging out" would be as easy as deleting that file.

**Comment by sehz** [comment]
Using separate file to store token would be good compromise for now

**Comment by ajhunyady** [comment]
CLI supports multiple profile. I can imagine situation where I have a local cluster and a cloud cluster. How does login reconcile with that? Can I be logged-in into multiple environments at the same time?

**Comment by sehz** [comment]
Only one login at a time.  During login, CLI will sync cluster profiles with remote clusters(cloud).    Since remote clusters won't be removed after login expired, you can use multiple environments at the same time.

**Comment by sehz** [comment]
Maybe this command should be renamed as ```fluvio profile remote-sync``` instead of login.   This still will require login but limit scope to this feature only.

**Comment by ajhunyady** [comment]
This feature seems to be quite complex. Do we have a place for a functional spec? Such spec could be used to educate us (product)  and to draft the CLI documentation as well.

**Comment by ajhunyady** [comment]
I was thinking authorize/unauthorize.

**Comment by sehz** [comment]
We will have separate RFC or [RFD](https://oxide.computer/blog/rfd-1-requests-for-discussion/) to track specifications.  For now, we will use this issue for tracking specification.

**Comment by sehz** [comment]
@ajhunyady How about then ```fluvio profile sync```

**Comment by nicholastmosher** [comment]
Status update: I've pushed a branch with my changes so far: https://github.com/infinyon/fluvio/compare/master...nicholastmosher:cloud-credentials

Here's what I've got so far and what I'd like to have before opening a PR:

- [x] `fluvio profile sync cloud` command will prompt for email and password
- [x] Email and password can be used to authenticate with cloud-ops
- [x] After authentication, a Fluvio Cloud token is saved to `~/.fluvio/login`
- [x] After one authentication, future requests do not require email/password unless token expires
- [ ] Profile download is not implemented on server side, so client currently does nothing after auth
- [ ] I moved around other CLI options and have not fixed them yet

**Comment by sehz** [comment]
Once you fixed other CLI options, you can make PR request.   Profile download can be done as separate PR

**Comment by nicholastmosher** [comment]
After further discussion, I'm going to close this issue and track TLS progress in separate issues.

**Comment by sehz** [comment]
Please add story points
