### ISSUE TITLE
Improve Configuration object structure and API for `fluvio`

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1472]
The configuration in the `fluvio` crate is something that has been a little clunky and inflexible for a while now, and is due for some cleanup. We should use this issue to collect ideas and requirements for things we need our configuration to be able to do, and eventually serve as the blueprint for future updates to our config-handling code.

Some initial features I can think of that our config should be able to handle include:

- It should be able to deserialize itself from the standard location on-disk (e.g. `~/.fluvio/config.toml`) - already works
- It should be able to read config from environment variables kube-config style
  - This should first check for a profile in the environment (e.g. if being run in a pod), then check for local config
  - We should have a minimal list of required fields for reading a profile from the environment, e.g.:
    - `FLUVIO_CLUSTER_ENDPOINT`
    - `FLUVIO_CLUSTER_DOMAIN`
    - `FLUVIO_CLUSTER_KEY`
    - `FLUVIO_CLUSTER_CERT`
    - `FLUVIO_CLUSTER_CA`
- Profiles should be standalone objects that are semantically complete even without the context of the entire config
  - This may already be the case, but we should codify it as a requirement going forward
- Profiles should have a canonical string representation that may be used as a shorthand instead of requiring a config file
  - This may be similar to how database URLs work, e.g. `postgresql://user:secret@address`
  - This may or may not be feasible if we require client TLS certs

Ideas that may or may not be good:

- I am trying to think of how to represent a whole profile object as compactly and neatly as possible, in a way that also allows it to be standalone and composable (e.g. allowing the sharing or manipulation of a single profile without dragging along an entire config file, which may have unrelated profiles or other settings included). This is tricky because TLS certificates make profiles big enough to be awkward to carry around as a string. I'm thinking about representing profiles as a zip or tar archive with a manifest file (e.g. something like `profile.toml/yaml/json`) as well as any certificates needed.

**Comment by sehz** [comment]
It would be good if you can write the problem statement first.
