### ISSUE TITLE
[Bug]: Initial value for SmartStream Aggregate does not work

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1491]
While testing various examples for the Aggregate blog, I realized that using the `fluvio consume --initial` flag doesn't work as expected, it just uses the empty accumulator always.

**Comment by sehz** [comment]
Lets add to integration test

**Comment by nicholastmosher** [comment]
Ok after digging into this, it turns out that the initial accumulator mechanism is working 100% fine, it's just that the examples I was using were trying to parse an integer from a string that had a trailing newline. For instance, in the `sum` example, we have this:

```rust
let accumulator_int = accumulator_string.parse::<i32>().unwrap_or(0);
```

When feeding input for the "initial accumulator", the two ways I have gone about it are:

Using a file:

```
$ cat initial.txt
5

$ fluvio consume topic --initial=initial.txt
```

Or piping from a subshell:

```
$ fluvio consume topic --initial=<(echo 5)
```

However, `echo` will append a newline to its output, and many text editors automatically append a newline as well. This means that our record actually looks like

```
5\n
```

which fails to be parsed as an `i32`, resulting in the smartstream "ignoring" the initial value. An easy way to fix this is to trim the accumulator buffer before attempting to parse it, such as:

```rust
let accumulator_int = accumulator_string.trim().parse::<i32>().unwrap_or(0);
```

Note the `trim()` call before `parse`

I will update the affected examples with `trim` and also add a tip to the documentation to help avoid this.
