### ISSUE TITLE
If 2 consumers listen for the same topic/partition, only one of them gets messages

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/fluvio#15]
Steps to reproduce:

1) Create topic:
./target/debug/fluvio topic create -t my-topic-1 -p 1 -r 2

2) Create first consumer 
 ./target/debug/fluvio consume -t my-topic-1 -p 0 -C

3) Create second consumer
 ./target/debug/fluvio consume -t my-topic-1 -p 0 -C

4) Create producer
./target/debug/fluvio produce -t my-topic-1 -p 0 -C

type a few lines... only 1 consumer gets the messages.

**Comment by sehz** [comment]
bug exists regardless of replication

**Comment by sehz** [comment]
fixed as part of 0.3.0 release.

async::sync::channel doesn't send copy of the message to every receiver.
switch to Tokio::sync::broadcast.
