### ISSUE TITLE
Release workflow does not force push docker image

### ISSUE THREAD

**Issue by nacardin** [infinyon/fluvio#1516]
`FORCE_RELEASE` is not having intended effect in `release_docker` job

**Comment by nicholastmosher** [comment]
@nacardin can you assign this to a milestone when you have a chance?

**Comment by tjtelan** [comment]
The problem is that while we check for `FORCE_RELEASE`, we do not actually perform the push on L144, unlike what we report.

https://github.com/infinyon/fluvio/blob/aa30e7eab255d995509be4b6fa0f8465120ba578/.github/workflows/release.yml#L143-L151

**Comment by digikata** [comment]
outdated
