### ISSUE TITLE
Weekly Longevity  Test

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#1534]
Goal:  Validate that Fluvio can run minimum of periods without problem.  This is required validation for transitioning to Beta.

**Criteria**
Producers: 100,
Consumer: 100
Period: 1 week.
Replication: 3
Partition: 10
Data: TBD

**Workflow**
For every 24 hour, launch Fluvio cluster with number of  consumer/producers specified above.   Test will continuously run for 1 week.  Since Github action only runs with maximum of several house, Longevity test workflow must run in detached mode.  This means there should be maximum of 7 concurrent test session at any time. 

For every hour(?), Github action collector can be used to collect status of each run. If there are failures, failure should be saved as GitHub artifacts. 

Dependent on #627 for scaling producers and consumers into processes instead of threads

**Comment by tjtelan** [comment]
Some implementation details:

### longevity runner

The test scheduler should probably be a executed as a simple cron job script or systemd service to ensure the test is always producing data. If it could also assist in reporting failure, by collecting relevant logs before restarting a test, that would be great.

The test itself needs to have a designated space for keeping failure logs in the filesystem. This test should be running all the time, so we need an efficient way to collect logs between runs for the github action to collect. 


### github action

The github action is only for reporting status and any information that will communicate a need to log into the longevity runner for any kind of failure analysis.

We might like cluster status, test status, and some kind of file-based alert about if the test has failed so the logs can be collected.

Thinking maybe we can keep track of the expected process id and keep that as an artifact. Each run of the action, we'd compare the PID and report a failure if they are different (or not found, like the test stopped running and couldn't be restarted). A negative of this approach is possibly missing logs if there are multiple restarts between a collection period. If the github runner deletes logs on the host after uploading to Artifacts, we can be certain to collect everything w/o duplicates.
