### ISSUE TITLE
Restructure SPU spec to separate cluster endpoint and ingress endpoint

### ISSUE THREAD

**Issue by nacardin** [infinyon/fluvio#1546]
Ingress should be separate from the local endpoint so that the client can choose how to connect. This will allow clients to be deployed within the same K8 cluster.

Renaming from public/private to data/control should clarify their intended usage.

Also, if possible, it would be better to move the endpoint fields from spec to status, as they do not define the desired state of an SPU, rather they are derived from K8 service after creation.

Example:
```
SpuSpec {
    id: 0,
    type: Managed,
    rack: None,
}

SpuStatus {
    resolution: Online
    data_endpoint: {
        host: "fluvio-spu-main-0.fluvio-spg-main",
        port: 9005
    },
    data_ingress_endpoints: [{
        host: "192.168.49.2",
        port: 9005
    }]
    control_endpoint: {
        host: "fluvio-spg-main-0.fluvio-spg-main",
        port: 9006
    },
}
```

**Comment by sehz** [comment]
Sorry.  they are both for data plane but one is between SPU `private` , other is for client.  To make it unify, it would be better to look like:
```
SpuStatus {
    resolution: Online
    end_points: {
       client: {
            port: 9006,
            external: 'my-cluster',
            internal: 'fluvio-spu-main-0.fluvio-spg-main'
       },
       peer:  {     
           host: "fluvio-spu-main-0.fluvio-spg-main",
           port: 9006
       },
    }
}

```

**Comment by nacardin** [comment]
> ```
>             external: ['my-cluster'],
>             internal: ['fluvio-spu-main-0.fluvio-spg-main']
> ```

Do the client endpoints need to be an array?
