### ISSUE TITLE
Producer client error - Connection refused

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#1560]
I'm able to reproduce this locally if I run the test for long enough. This is the error I got after attempting to run a 10 min test. Failed after 9.5 minutes.

Repro steps:

Start a cluster (in k8 mode not local):
`fluvio cluster start`

Run the longevity test:
`make longevity-producer-test`

Example failure output
```
+ echo 1630431825,1/20,570/600,oKUdUqV2ItEW9beukZfXaypHS41zEVAiUAo9nOT03F4rukXJ85nCmwTzfg83XSYWsZ4IN8H5Xz7j9Myd7cTjKRen5pGGsHlrNBlNayGZ3joZ17bvNnnB7JnlqD03AZa4AeFhiMDlMoE6tpSgFzLpWpTD3fUFX35PvIXfPXDnHFZJwGRbF3uzn5yuyVanjBkPTY8N52UCuMmfWnXSCQjTdLZjWTngRBiRpA7c8IUVX5ijPDF8Jnxh3gACXmiwSw93VNHffZb6Y7yIL0wltXcBSO4XIcu8MMTclRYTYfgVOgTDxQ8PPVlI5s1XeygGFXMxNVs8otUCEYc2oFDUUvjkXaZ7WWKdt29KG9muymvNKQOQ1cR6KUWKUg814UNsDSoCWN4PBCYeJAGOJYJBIc3rJZ8UvYLMpFN6hTJA5AqICqrrX2Kvke63uK9aJASWGvA5ve31ggMVnZ7LQ6eP3ycPMJZqs633jwHfLHnSqpA1h9lAEGrVQuCnvwPmYqAxJlNWjTdVrDBYXcbiL7rYjghdVseGDe2Nn0afOivsqM8p6g4nV8zHP57dkmGw4PnHw3VJECL6lqASeNSxs5fNndLYr3vXcH0rk2Vhtdsns6KhTOx9Vk1QjU3LNviYNBLRJlkYop6IlKCDnkskGWMHHKDeAZpSMLQMajqVY7EKF4KuLlqhZj2EM6dlGjKi49SDUwbMsnzKwCBOBmFXQBt1qS9edmeFkvF3LzXFKd50bft9iWgGxAx0p5bDvyXBHbhKKJOYFk2Tpf65T2jb5IUwzT7rczXZgApV0HiW7zeKNF1LW9kyX7UbxFd4yjbf0TEeTKMZYZj7geDeZ5o0lKeP3T1fGDu86gh8MkdGCCMrGi9bbaGqv0k8towAfKWhyqddll8TtXo4eo5MnkLGQ3iIIkthtoGl5x18OAC7mM2KVgr62DvkdubPahi8UYoxyQnTAQrnJDBalC9VP3qEFMrlXe5O9oJlagkQX9zXY2oHKqoW
+ /home/telant/.fluvio/bin/fluvio produce longevity-existing
Error: 
   0: Fluvio client error
   1: Fluvio socket error
   2: Connection refused (os error 111)
```

_Originally posted by @tjtelan in https://github.com/infinyon/fluvio/issues/1476#issuecomment-909481193_

**Comment by sehz** [comment]
what's step to reproduce locally?

**Comment by tjtelan** [comment]
> what's step to reproduce locally?

`make longevity-producer-test`

The default runtime is 10 minutes, and I would say about 25% of the time I will hit this on my local machine.

**Comment by tjtelan** [comment]
Seems like the issue we're seeing is we create a new connection on every instance of `fluvio produce` and we're running the test fast enough that these connections accumulate and aren't terminated fast enough. We eventually hit a default number of max connections.

The action item is to either bump the sysctl for max connections:

```
sysctl net.core.somaxconn=1024
```

Or we can re-write the test to re-use the connections.

This feels like a future ergonomic issue for the CLI, but the other language APIs support connection re-use and batching, which would be more of a realistic usage.

**Comment by tjtelan** [comment]
This error appears to be a duplicate of #1519 and will continue to be tracked there.
