### ISSUE TITLE
HandshakeError does not expose underlying error

### ISSUE THREAD

**Issue by nacardin** [infinyon/fluvio#1629]
We only see the following for any connection error:
```
❯ fluvio topic list                                                                          
Error: 
   0: Fluvio client error
   1: Fluvio socket error
   2: HandshakeError
```

This may be something that needs to be fixed in our futures crate.

**Comment by sehz** [comment]
This is also opportunity to clean up our error handling
* implement Display trait for Error
* Review Client Error handling

**Comment by sehz** [comment]
https://github.com/infinyon/fluvio/issues/791

**Comment by sehz** [comment]
Backtrace should only be display in the verbose mode.  It is not for typical user

**Comment by nacardin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-6140c6361f93f200184da0bf/issues/infinyon/fluvio/1629?planning-poker) with ZenHub @morenol @nicholastmosher @sehz @simlay @tjtelan
