### ISSUE TITLE
Rename crates for branding and clarity

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#171]
@sehz was talking about renaming some of the crates and getting rid of the `flv-` prefix in favor of `fluvio-`. If we're going to be renaming all of our crates, I figured we might want to have a place to discuss further renaming potential. Right now I'm only looking at crates in the `fluvio` repo itself.

Here are some possibilities I was thinking of:

- [x] `cli`
	- package: `fluvio-cli`
	- library: `fluvio_cli`
	- binary: `fluvio` (cargo install fluvio)

- [x] `client-rs` -> `client`
	- package: `fluvio`
	- library: `fluvio` (cargo add fluvio)

- [x] `cluster`
	- package: `fluvio-cluster`
	- library: `fluvio_cluster`

- [x] `event-stream-k8` -> `stream-dispatcher`
	- package: `fluvio-stream-dispatcher`
	- library: `fluvio_stream_dispatcher`

- [x] `event-stream-model` -> `stream-model`
	- package: `fluvio-stream-model`
	- library: `fluvio_stream_model`

- [x] `internal-api` -> `controlplane`
	- package: `fluvio_controlplane`
	- library: `fluvio_controlplane`

- [x] `metadata-cluster` -> `controlplane-metadata`
	- package: `fluvio-controlplane-metadata`
	- library: `fluvio_controlplane_metadata`

- [x] `sc-api` -> `sc-schema`
	- package: `fluvio-sc-schema`
	- library: `fluvio_sc_schema`

- [x] ~`sc-k8` -> `sc-cli`~ Binary target moved to `sc` crate below
	- ~package: `fluvio-sc-cli`~
	- ~binary: `fluvio-sc` (external subcommand to fluvio?)~

- [x] `sc-core` -> `sc`
	- package: `fluvio-sc`
	- library: `fluvio_sc`
	- binary: `fluvio-sc-k8`

- [x] `spu-api` -> `spu-schema`
	- package: `fluvio-spu-schema`
	- library: `fluvio_spu_schema`

- [x] `spu-server` -> `spu`
	- package: `fluvio-spu`
	- binary: `fluvio-spu`
	- ~library: `fluvio_dataplane`~ Move all shared SPU code to `spu` crate

Here are some things I was thinking when changing these names:

~* Changing `sc` -> `controlplane` and `spu` to `dataplane`~
  ~* Changing `spu` to `dataplane` was @sehz's idea, and I really like it because `spu` and `sc` are in-house names that nobody outside of fluvio is going to know what it means. However, `controlplane` and `dataplane` I think are pretty common terms in distributed systems. Just googling those really quickly gives you a sense of their roles. So this renaming would help new developers get to know their way around the repo by understanding the roles of each crate.~

* Changing `event-stream-k8` to `eventstream-dispatcher`
  * For some reason I find kebab-case really attractive with only two words but ugly with three words
  * Moving away from k8 in the name decouples us from third-party technology
  * The crate name was already `eventstream-dispatcher` without a hyphen

* `metadata-cluster` to `metadata`
  * I feel like right now there's no other metadata to confuse this with, so no need to distinguish "cluster" specifically
  * Shorter import name

* `internal-api` seems like an unsatisfying name, but I don't have a better idea right now. It makes me think that it's a private crate even though it isn't. I don't know if something like `controlplane-bridge` makes any sense. Ideas for this would be awesome.

### Future thoughts

This might deserve its own issue, but its in line with cleanup and refactoring so I thought I'd mention it.

* We should get rid of the `fluvio_cli` library target. Any business logic that lives in there should be moved to a different crate with a proper library interface. I think the `client` crate (`fluvio` library) would be a great place to put that code. In my opinion, any `cli` crate should just be a thin wrapper around StructOpt or Clap to do validation and then call the public functions from the other crates where functionality lives.
  * The same thought could apply to the other `cli` crates
  * This would allow us to make use of doctests, which we currently can't do because it's a binary target
  * It would force us to think about how to make a nice and usable public interface. Our CLI would be "dogfooding" our library crate.

**Comment by nacardin** [comment]
> I was actually just working on that ;) I'm trying to move all of the business logic from the `cli/cluster/install` module into `client-rs` right now. In fact I'll make an issue for it

Why should installer logic be in `client-rs` as opposed to a separate crate?

**Comment by Ryanmtate** [comment]
I think the proposal is reasonable. I don't have any immediate concerns and generally agree with the renaming and exposing of public interfaces through libraries only to be thinly consumed by the binaries.

**Comment by nacardin** [comment]
> internal-api seems like an unsatisfying name, but I don't have a better idea right now. It makes me think that it's a private crate even though it isn't. I don't know if something like controlplane-bridge makes any sense. Ideas for this would be awesome.

What if `sc-api`, `spu-api`, and `internal-api` were in one crate called `fluvio-api`, the different modules could be behind feature flags if needed. Also, note that these three packages have roughly the same dependencies.

**Comment by ajhunyady** [comment]
I suggest dividingevent stream into 2 words
eventstream => event-stream

**Comment by nicholastmosher** [comment]
> I suggest dividing event stream into 2 words
> eventstream => event-stream

@ajhunyady we talked about this in today's engineering meeting, and we got to thinking that since any "stream" we refer to in Fluvio is an "event stream", that we would just shorten the names to `stream-dispatcher` and `stream-model`. That seemed to flow nicely :)

**Comment by nicholastmosher** [comment]
Closed by #239
