### ISSUE TITLE
Add check for installer script after release

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#1722]
We just need a simple check to let us know if we ever update the `install.sh` script, but the release process fails to update the script at `packages.fluvio.io`.

Compare:
https://packages.fluvio.io/v1/install.sh == https://github.com/infinyon/fluvio/blob/master/install.sh

With the action item on failure being to copy from the git repo to the S3 bucket.

I think this check is probably going to live in `CD_Release`

**Comment by nacardin** [comment]
The script is updated on release since https://github.com/infinyon/fluvio/pull/1723.
