### ISSUE TITLE
[Bug]: Broken link in https://github.com/infinyon/fluvio/blob/master/CONTRIBUTING.md

### ISSUE THREAD

**Issue by qrilka** [infinyon/fluvio#1739]
**What happened**
Link https://www.fluvio.io/docs/getting-started/ on "Getting started" results in 404

**Expected behavior**
Link returns proper result

**Additional context**
It looks like the website has links of form https://www.fluvio.io/docs/get-started/<XXX>/ where <XXX> is mac, linux, paspberry or cloud. As it's not clear which one to choose I couldn't create a PR fixing the problem

**Comment by sehz** [comment]
Hi, that link is obsolete and all other links point to download page.  Which doc or page still has ` https://www.fluvio.io/docs/getting-started/`?

**Comment by qrilka** [comment]
It's in the title of this ticket - https://github.com/infinyon/fluvio/blob/master/CONTRIBUTING.md

**Comment by sehz** [comment]
Gotta, that should point to `https://www.fluvio.io/download/`
