### ISSUE TITLE
Add CLI command for managing SmartModules

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1758]
New proposed subcommands for persistent SmartStreams/SmartModules

```
# Create a new SmartModule
$ fluvio smartmodule create <name> [--wasm-file=path/to/binary.wasm] [--source-file=path/to/project]

# Update a SmartModule that already exists, or create it if it does not exist
$ fluvio smartmodule update <name> [--wasm-file=path/to/binary.wasm] [--source-file=path/to/project]

# Delete if the named smartmodule is not in use, reject otherwise unless --force is given
$ fluvio smartmodule delete <name> [--force]

$ fluvio smartmodule list
$ fluvio smartmodule describe
```

Fluvio Client needs an API for SmartModules 

Fluvio CLI should accept SmartModule name for consuming
```
fluvio consume my-topic --filter=<name of smartmodule>
```

`--filter` should accept file path or persistent SmartModule

This applies also to `--map` and `--aggregate`.

Checklist: 
- [X] `fluvio smartmodule add/delete/list` 
- [ ] `fluvio smartmodule describe`
- [ ] `fluvio smartmodule update`

**Comment by nacardin** [comment]
We don't seen describe or update at the moment. Update requires a versioning strategy. Otherwise this is done.
