### ISSUE TITLE
Check the PUBLISH_CRATES list in release CI.

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#1784]
I added `fluvio-smartstream-executor` a while back but didn't add to the [`PUBLISH_CRATES`](https://github.com/infinyon/fluvio/blob/2246a7daed2845f8cbd87e9134cb9f29dcca78d5/release-scripts/publish-crates.sh#L5) list because it wasn't on crates.io which caused CI to fail. Please add it and check other crates.

**Comment by tjtelan** [comment]
#1785 renamed this crate and also set it to not publish. It's not immediately clear how to proceed at the moment.

**Comment by sehz** [comment]
Update `fluvio-connectors` ?  The crates is unstable until we are done with integrations.  We can publish for 0.9.12 release.

**Comment by nacardin** [comment]
We don't create new crates often enough to justify this
