### ISSUE TITLE
Investigate Single Docker Image for Fluvio

### ISSUE THREAD

**Issue by Ryanmtate** [infinyon/fluvio#182]
Setup minikube, registry, tunnel -- Additionally, try to setup these steps as sharable or reusable (e.g. Docker container for steps).

**Comment by Ryanmtate** [comment]
PR #188 combines the sc and spu make steps into `make fluvio_image` and adds a new `fluvio` docker folder until k8-util. Not sure if this is what we're thinking in terms of consolidating the images or not. That said, the PR does not setup minikube, a registry or tunnel.

**Comment by sehz** [comment]
create a single binary.   may need to to update
- helm chart
- deployment controller
- sc and spu CLI
- ....

all smoke test should pass

**Comment by Ryanmtate** [comment]
Can you provide more detail than this?

**Comment by sehz** [comment]
updated
