### ISSUE TITLE
publish nightly docker image for fluvio

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#185]
Each night, publish docker images.

Questions
- to docker hub?

**Comment by Ryanmtate** [comment]
Use Amazon ECR for pushing docker images for fluvio

https://github.com/aws-actions/amazon-ecr-login

**Comment by Ryanmtate** [comment]
@sehz Will need access to the AWS credentials for this;

```yaml
aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

**Comment by sehz** [comment]
It looks like publishing nightly image is [ok](https://github.com/rust-lang/docker-rust-nightly).

We just use `nightly` tag.

I will add docker credentials as secrets

**Comment by sehz** [comment]
maybe unify binary could be part of this issue.

**Comment by Ryanmtate** [comment]
We may also want to setup an IAM account exclusively for github actions workflow with the following permissions: https://github.com/aws-actions/amazon-ecr-login#security-disclosures

**Comment by Ryanmtate** [comment]
> maybe unify binary could be part of this issue.

We have #182 open; I'll see about combining...

**Comment by Ryanmtate** [comment]
Might be worth creating a separate IAM for each developer as well to be able to make changes in the console/CLI

**Comment by sehz** [comment]
we will stick with docker hub for now.  may move to another registry if warranted later

**Comment by sehz** [comment]
use `latest` for tag.

Fluvio install work with nightly image as before.

**Comment by sehz** [comment]
manual image published is working.  will close this issue when daily job is running

**Comment by sehz** [comment]
periodic docker publishing worked!, closing issue
