### ISSUE TITLE
Expose `fluvio completions` in the top-level subcommand `--help`

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#1850]
We have structopt generate shell completions for us, but if you don't know about `fluvio completions` then you have no chance of discovering it. This subcommand should not be hidden.

We're also going to need to update our docs to walk a user through how to load shell completions. A shortened version might be useful if you run `fluvio completions --help`

**Comment by bohlmannc** [comment]
Hey TJ, I think I was able to tackle this issue. I created my own branch, but I wasn't able to push to it. Should I have forked the repo instead? Or do I need to be in the fluvio organization?

**Comment by sehz** [comment]
[Please fork the repo and create PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)
