### ISSUE TITLE
CLI smoke test occasionaly generates invalid topic names

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#1864]
The problem is the format of the topic name. Neither the test nor the Fluvio error reports back what topic was being used.

```
not ok 16 Create a topic
# (from function `assert_success' in file tests/cli/smoke_tests/../test_helper/bats-assert/src/assert_success.bash, line 42,
#  in test file tests/cli/smoke_tests/topic-basic.bats, line 21)
#   `assert_success' failed
# 
# -- command failed --
# status : 1
# output (2 lines):
#   Error: 
#      0: Invalid argument: Topic name must only contain lowercase alphanumeric characters or '-'.
```

The topic name is randomly generated. The only consideration made to the topic name is that it doesn't start with `-`. It seems that possibly this isn't strict enough?

https://github.com/infinyon/fluvio/blob/a739ea6493f3fe20631bc4fd48bef19b8e36a8e1/tests/cli/test_helper/fluvio_dev.bash#L18-L37

The test needs to print out the topic name that is trying to be used when it fails in CI. We do have this output if we we the `DEBUG` env var to true while the tests run.

**Comment by tjtelan** [comment]
Seems that we also need to make sure topic names don't end in `-`. I think the error message can be improved, bc this was harder than necessary to figure out.

```
$ fluvio topic create topicname-
Error: 
   0: Invalid argument: Topic name must only contain lowercase alphanumeric characters or '-'.
```

**Comment by sehz** [comment]
ouch
