### ISSUE TITLE
bug in join stream: no refresh

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#1878]
steps to reproduce:
1.  Create topic: `left,`right`.
2. Create smart module join:
```
 flvd smartmodule create join --wasm-file crates/fluvio-smartstream/examples/target/wasm32-unknown-unknown/release/fluvio_wasm_join.wasm 
```
3. Produce right:
```
echo 100 | flvd produce right
```
4. Consume left:
```
flvd consume left -B --join join --join-topic right
```
5.  Produce left first.
```
echo 5 | flvd produce left
```
This produce: `105`.
However, adding more records to right doesn't update join stream:
```
echo 5 | flvd produce right
```

```

**Comment by morenol** [comment]
I thought that this is the expected behavior, only produce output on updates on left topic. Updates on right will only update the right record that will be used once a new record in left arrives

**Comment by sehz** [comment]
Yes, but doesn't looks like that's happening, it only updates once even thought it receives updates. It need to update SmartEngine with new data

**Comment by nacardin** [comment]
Works as expected
