### ISSUE TITLE
DerivedStream join right record

### ISSUE THREAD

**Issue by morenol** [infinyon/fluvio#1890]
Currently, smartmodule join waits for first record from right and then continue with the first batch, we may be interested in to get first the latest available value from right and then proceed with the batches

**Comment by ajhunyady** [comment]
@morenol, please describe the algorithm for join as it needs to be documented in `fluvio/docs`. Going forward, all algorithms have to be described in detail in the docs as users need to understand how they behave.

**Comment by sehz** [comment]
related to https://github.com/infinyon/fluvio/issues/1890
