### ISSUE TITLE
[Bug]: ssl handshake error

### ISSUE THREAD

**Issue by gvierno** [infinyon/fluvio#1895]
**What happened**
minikube in macos, I got this error:
```
2021-11-14T05:14:40.653230Z DEBUG install_fluvio{namespace="default"}:install_app: fluvio_cluster::start::k8: Using NodePort service type
2021-11-14T05:14:40.653256Z DEBUG install_fluvio{namespace="default"}:install_app: fluvio_cluster::start::k8: Getting external IP from K8s node
2021-11-14T05:14:40.653267Z DEBUG install_fluvio{namespace="default"}:install_app: fluvio_cluster::start::k8: Trying to query for Nodes
2021-11-14T05:14:40.660524Z DEBUG install_fluvio{namespace="default"}:install_app: k8_client::client::client_impl: Node: retrieving items: https://192.168.64.2:8443/api/v1/nodes
Error:
   0: Fluvio cluster error
   1: Failed to install Fluvio on Kubernetes
   2: Kubernetes client error
   3: error trying to connect: tls handshake: The certificate was not trusted.
   4: error trying to connect: tls handshake: The certificate was not trusted.
   5: tls handshake: The certificate was not trusted.
   6: tls handshake: The certificate was not trusted.
```
**Expected behavior**

**Describe the setup**
- Are you using a local Fluvio install? Minikube? Fluvio Cloud?
- What version of Fluvio are you using? `fluvio version`
`minikube`
```
Fluvio CLI           : 0.9.12
Fluvio CLI SHA256    : d96454486602fd6aa2ea79ea76822a869a6eeea8816ddc47855d062febc9f83a
Fluvio Platform      : Not available
Git Commit           : b2250033d49a279c3d718cd25c42a4cee0b40297
OS Details           : Darwin 10.16 (kernel 20.6.0)
=== Plugin Versions ===
Fluvio Runner (fluvio-run)     : 0.0.0
Infinyon Cloud CLI (fluvio-cloud) : 0.1.6
```
**How to reproduce it (as minimally and precisely as possible)**
1. Run the command '...'
2. Type the input '...'
`fluvio cluster start`
**Log output**
It helps to have logs from Fluvio's SC and SPU processes.
Depending on your setup, here's how you can get the logs:

- For a local Fluvio installation on Mac:
  - Run `cat /usr/local/var/log/fluvio/flv_sc.log` for SC logs
  - Run `cat /usr/local/var/log/fluvio/spu_log_XXXX.log` for each SPU
    - E.g. when running 1 SPU, there will be `spu_log_5001.log`
- For a Fluvio installation on Minikube:
  - Run `kubectl logs fluvio-sc` for SC logs
  - Run `kubectl logs fluvio-spg-main-X` for each SPU

**Environment (please complete the following information):**
 - OS: [e.g. Linux, Mac]
 - Fluvio Version [e.g. 22]
 - Minikube version (if used): use `minikube version`
 - Kubernetes version: use `kubectl version`
Mac
**Additional context**

**Comment by sehz** [comment]
This seems like same bug as: https://github.com/infinyon/fluvio/issues/1838 which is fixed.  Can you check dev release?

```
$ fluvio update --develop.
$ fluvio cluster upgrade --image-version latest
```

**Comment by sehz** [comment]
Works on latest fluvio release. closing
