### ISSUE TITLE
Bulk Save and Restore

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#1898]
For development and testing purposes, we need way to move data between clusters.   This utility should work on both local and k8 clusters.   It should be designed only for bulk copying not replacement for consumer/producer.  

Something like this:
```
$ fluvio-bulk export /tmp/
<this will create zip file for existing data set>
```
fluvio-data.zip
```
$ fluvio cluster start --import /tmp/fluvio-data.zip
```

**Comment by tjtelan** [comment]
Related: #1672 

We need some assurance that no writes to the cluster are possible during the save or restore actions

**Comment by sehz** [comment]
related issue: https://github.com/infinyon/fluvio/issues/1504.

```
kubectl cp fluvio-spg-main-0:/var/lib/fluvio/data data1
```

This works.   Can probably use similar technique to reload them.  Just probably need to restart SPU after load them.

**Comment by sehz** [comment]
Copying 784M using `kubectl cp` took 1 min 10 seconds
```
time kubectl cp fluvio-spg-main-0:/var/lib/fluvio/data data3
tar: removing leading '/' from member names
error: unexpected EOF

real	1m10.510s
user	0m3.215s
sys	0m4.167s
```

Consuming using fluvio CLI took: ~1m 15 seconds:
```
fluvio consume producer-test -B > producer3.data
```

**Comment by sehz** [comment]
Similar for produce:
``
time fluvio produce test -f producer3.data

real	0m53.774s
user	0m13.656s
sys	0m0.907s
``

Closing this issue since there are no benefit of having alternative path to copy data from/to from pod.
