### ISSUE TITLE
Add support for 3rd party connectors

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#1903]
Right now to start a connector you can only start a connector that's an official infinyon docker image.

Let's allow some the ability to start the cluster with more allowable prefixes for images rather than just [`infinyon/fluvio-connect-{}`](https://github.com/infinyon/fluvio/blob/82c29cf9fbb2b020bca5fc5a1aca301461fbfaa3/crates/fluvio-sc/src/k8/controllers/managed_connector_deployment.rs#L211-L224)

**Comment by nacardin** [comment]
@simlay Adding `from` field to specify arbitrary source of metadata/image ?
