### ISSUE TITLE
Release fluvio-smartmodule crate and update fluvio-smartstream-template (rename)

### ISSUE THREAD

**Issue by morenol** [infinyon/fluvio#1934]
we should add that crate to the publish list and update the template repo

**Comment by nicholastmosher** [comment]
I would suggest archiving the current template repo (`fluvio-smartstream-template`) and cloning it under a new name (`fluvio-smartmodule-template`). That way, current blogs and docs will still continue to work, but new ones can use the new URL.

**Comment by tjtelan** [comment]
We want to deprecate the `fluvio-smartstream` crate and point at the `fluvio-smartmodule`. We'll bump the `fluvio-smartstream` create with an update to the README.
