### ISSUE TITLE
Enable feeding an Aggregate to a Tableformat

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1967]
Right now, there is no way to feed an aggregated stream into a Tableformat to get a pretty display. This is problematic because we would like to be able to view aggregates as a live-updating table, which is what tableformat is for.

The root problem is that Aggregates typically represent a collection of data points in _each_ Record in a stream. For example, if we have Records in an aggregate stream that look like this, they cannot be used in a tableformat:

```
[
  {"repo": "infinyon/fluvio", "stars": 790},
  {"repo": "infinyon/node-bindgen", "stars": 236}
]
```

For this, we would expect a tableformat with columns namd `repo` and `stars`, with two rows.

One way to make this happen is to enable `array-map`s in a derived stream. The array-map would flatten the collection of data points and create a stream of the individual data points, which the tableformat can understand. Currently, however, array-map is not implemented/supported for derived streams, so this solution is unavailable.

**Comment by ajhunyady** [comment]
Let's evaluate what's the easiest way to get this accomplished.

**Comment by tjtelan** [comment]
The way I'm approaching this is to check if the input json is an array or an object.

* If it is an object, we apply the updates to the table (this is the current functionality). 
* If it is an array, we expect that we are dealing with an array of objects.

To join these two functionalities together, we will internally change the workflow use a list of events to render table updates. When the input is an object, we will update the table with an array length of 1. When it is an array, we will convert the array into a list of events.

**Comment by ajhunyady** [comment]
@tjtelan seems like a good solution.
