### ISSUE TITLE
SmartModule Aggregate does not seem to accept initial value

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#1988]
I've been re-running our blogs on infinyon.com and I noticed that in the Aggregate blog we show off the ability to set an "initial" value to begin accumulating from, but it does not work as expected.

The workflow I was testing is this one: https://www.infinyon.com/blog/2021/08/smartstream-aggregates/#initial-value

In summary, I created a file called `initial.txt` with the string "100" in it:

```
100
```

Then I ran the consumer over a stream, providing the path to the `initial.txt` file, but the initial value did not get used.

```
fluvio consume aggregate-ints -B --initial=./initial.txt --aggregate=target/wasm32-unknown-unknown/release/aggregate_blog_sum.wasm
1
2
3
4
5
15
```

The expected output should have been this:

```
101
102
103
104
105
115
```

**Comment by sehz** [comment]
@morenol Can you confirm the bug?

**Comment by morenol** [comment]
This is working as expected for me:

```
fluvio consume numbers --aggregate crates/fluvio-smartmodule/examples/target/wasm32-unknown-unknown/release/fluvio_wasm_aggregate_sum.wasm  -B --initial initial.txt
```

**Comment by ajhunyady** [comment]
% fluvio version
Fluvio CLI           : 0.9.13
Fluvio CLI SHA256    : 2f41e2874c1390657c2574fcd53ff4c9a4f12a7b463be2a4e8efc5afa55870c0
Fluvio Platform      : 0.9.13 (minikube)
Git Commit           : e1ef6333f3fb12660a096f2ad697961ab2b085db
OS Details           : Darwin 10.16 (kernel 21.1.0)
=== Plugin Versions ===
Fluvio Runner (fluvio-run)     : 0.0.0
Infinyon Cloud CLI (fluvio-cloud) : 0.1.6

**Comment by ajhunyady** [comment]
@morenol, we are using the step-by-step in this blog: http://localhost:1314/blog/2021/08/smartstream-aggregates/#initial-value

**Comment by morenol** [comment]
Could you check that this is your issue?

https://github.com/infinyon/fluvio/issues/1491#issuecomment-904716154

It seems that in the blog we have 

```
    let accumulator_int = accumulator_string.trim().parse::<i32>().unwrap_or(0);
```

But in the smartmodule template we dont have the call to `trim()`. I will update the smartmodule-template to include by default the trim() call

**Comment by ajhunyady** [comment]
@morenol yes, it uses trim. Happy to test locally if you tell me what to change.

**Comment by ajhunyady** [comment]
Template Issue fixed by https://github.com/infinyon/fluvio-smartmodule-template/pull/5

**Comment by morenol** [comment]
Maybe we should explain in the blog post why we are using trim()

**Comment by nicholastmosher** [comment]
Good catch @morenol, I can certainly update the blog with an explanation for this 👍
