### ISSUE TITLE
[Bug]: found duplicate version of package `trybuild v1.0.42` vendored from two sources

### ISSUE THREAD

**Issue by happysalada** [infinyon/fluvio#2029]
**What happened**
trying to vendor the source does not work because of a duplicate dependency.

**Expected behavior**
Trying to package this for Nixos (a linux distribution), the most common way to package rust executables is by vendoring depedencies. It would make things much easier if dependencies could be vendored.

**Describe the setup**
- Just trying to build fluvio-cli from source

**How to reproduce it (as minimally and precisely as possible)**
1. Run `cargo vendor` at the root of the directory to reproduce the failure

**Environment (please complete the following information):**
 - OS: Mac
 - Fluvio Version: 0.9.15

**Additional context**
Like I was saying, this is in the context of trying to package this for a linux distro (albeit a minor one). If something can be done to vendor the sources, it makes it a lot easier. I would perfectly understand if nothing can be done.

**Comment by sehz** [comment]
@tjtelan can you look at if we can do something about this?

**Comment by morenol** [comment]
In `fluvio-smartmodule` and `fluvio-test-derive` we are using https://github.com/sehz/trybuild as dependency and in `fluvio-protocol-derive` we are using https://github.com/infinyon/trybuild, I think that if consolidate all of these crates to use https://github.com/infinyon/trybuild this issue will be solved
