### ISSUE TITLE
CI says "Canceled" rather than "Failed" due to Panic Handler 

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#2042]
CI failed but said it was actually canceled for unclear reasons.
This was the main part of the stacktrace:
```
Creating the topic: test
topic "test" created
Test panicked: PanicInfo {
About to start producer test
    payload: Any { .. },
    message: Some(
        called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" },
    ),
    location: Location {
        file: "crates/fluvio-test/src/tests/smoke/mod.rs",
        line: 261,
        col: 48,
    },
}
+--------------+--------------+
| Test Results |              |
+--------------+--------------+
| Pass?        | false        |
+--------------+--------------+
| Duration     | 197.453274ms |
+--------------+--------------+

found topic: test offset: 0
starting fetch stream for: test base offset: 0, expected new records: 1000
found topic: test offset: 0
make: *** [Makefile:74: smoke-test] Terminated
```

![image](https://user-images.githubusercontent.com/1163510/147694772-de8629f4-2f03-41f5-abba-5efee4dc9a1b.png)

With my particular bug, it was because I moved a file and forgot to update the path. In any case, this should have said "Failed".

**Comment by sehz** [comment]
This is becoming more critical

**Comment by tjtelan** [comment]
I think this might have something to do with the signal that `fluvio-test` uses to terminate its child processes. We use `SIGTERM` and so does Github Actions when `Cancel Workflow` is triggered.

I am hoping that this will be resolved if we use a different signal. But worst case is we will need a signal handling thread so we know to exit with a non-zero

**Comment by sehz** [comment]
Without this box, we can't diagnose failures in the CI

**Comment by tjtelan** [comment]
Priority is to have these types of failures save logs, since that's the step that gets missed. But getting the error reporting properly is still the goal
