### ISSUE TITLE
ensure VERSION match

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#206]
the file `VERSION` in the top level directory specifies version for fluvio as whole.  However, there are other versions in the code.  We need to ensure following matches to VERSION:

- version in fluvio-core chart

if they don't match, CI should fail with warning.

**Comment by sehz** [comment]
top level `VERSION` should now match `appVersion` in:  `k8-util/helm/Chart.yaml`.  Currently it contains:
```
apiVersion: v2
name: fluvio-app
description: A Helm chart for Fluvio
type: application
version: 0.1.0
appVersion: 0.6.0
```

**Comment by sehz** [comment]
hmm. maybe not.  closing this issue for now

**Comment by sehz** [comment]
VERSION should match both version and appVersion in the Chart.yaml

**Comment by nacardin** [comment]
To ensure Helm chart is in-sync with the cluster create, consider embedding the Helm chart into the cluster crate during compilation.

**Comment by sehz** [comment]
for now, existing makefile `update_version` step is sufficient which need to be run for every change.   Need better versioning and component compatibility in the future
