### ISSUE TITLE
Update 'inventory' create new version in fluvio test

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#2085]
This should be updated to 0.2.   Just updating `cargo.toml` cause compilation error

**Comment by tjtelan** [comment]
It appears this crate is being deprecated?
The repo and others related were made readonly https://github.com/dtolnay/inventory

More background:
https://www.reddit.com/r/rust/comments/sjrt8f/dtolnayinventory_got_archived_is_there_an/
https://github.com/rust-lang/rust/issues/47384#issuecomment-1022913071

**Comment by morenol** [comment]
We should retry with [new](https://github.com/dtolnay/inventory/issues/32) version

**Comment by sehz** [comment]
@tjtelan can you look into this?

**Comment by tjtelan** [comment]
I just tried to swap out `0.1` for `0.3` and it looks like there's an incompatibility w/ the macro implementation using `.to_string()`. Will need to look into the proc macro.

```
error[E0015]: cannot call non-const fn `<str as ToString>::to_string` in statics
  --> crates/fluvio-test/src/tests/self_test/mod.rs:46:1
   |
46 | #[fluvio_test()]
   | ^^^^^^^^^^^^^^^^
   |
   = note: calls in statics are limited to constant functions, tuple structs and tuple variants
   = note: this error originates in the attribute macro `fluvio_test` (in Nightly builds, run with -Z macro-backtrace for more info)
```
