### ISSUE TITLE
CLI - Fluvio channel should enforce version pinning

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#2155]
Specifically, when using a Fluvio version channel (that is not `stable`, `latest` or `dev`), we should not support `fluvio update`.

The way we install different channel binaries, we can generally infer versions based on their name. If version channels support `fluvio update`, we break these assumptions and it can be a very confusing mess to troubleshoot.

To illustrate the problem in a bit more detail, I'll relate `fluvio update` behavior to the other channels.

* Stable
The stable channel binary gets installed at `~/.fluvio/bin/fluvio-stable`. In the event of a new official release, running `fluvio update` will replace `~/.fluvio/bin/fluvio-stable` with the binary of the newest `stable`, `vX.Y.Z`.

* Latest
The latest channel binary gets installed at `~/.fluvio/bin/fluvio-latest`. This channel updates on every merge to the `master` branch. Running `fluvio update` will release `~/.fluvio/bin/fluvio-latest` with the binary of the newest `latest` build, typically `vX.Y.(Z+1)-<git commit>`, (`Z` with respect to the stable version)

* Version channel
Any version channel binaries get installed in a similar place, but with the version in their name. So for version channel `0.9.16` we would install at `~/.fluvio/bin/fluvio-0.9.16`. And here is where user expectations come into play.

It is expected that switching over to that channel will always be 0.9.16. However, running `fluvio update` will update `~/.fluvio/bin/fluvio-0.9.16` to whatever the stable version `vX.Y.Z` is.

---

Anyway, that's a long story to say that we need to check in `fluvio-channel` if we're in a version channel before executing `fluvio update`.

**Comment by LanceEa** [comment]
I would be happy to take a look at this one. Seems like a good one to start getting familiar with the code-base and provide a small DX improvement for users of the Version Channel binaries.

**Comment by tjtelan** [comment]
@LanceEa This one is all yours if you'd like to take it on.

The channel feature is still under-documented, but the in progress docs are here: https://github.com/infinyon/fluvio-website/pull/263

Otherwise feel free to reach out if you have any questions

**Comment by LanceEa** [comment]
Sounds good. I read the link to the docs you have in the PR and all make sense to me.

Is the assumption that when someone wants to do an update for the Version branch that they need to be explicit and follow the steps you outline in your PR?

```bash
fluvio version create X.Y.Z
fluvio version switch X.Y.Z
```

If so do we want to mention this in the error response or point the user to the docs with a link? I guess the concern in both scenarios would be trying to keeping the error message in-sync if links or commands change.

When reading the Channel Docs PR, I was curious about when the binaries get downloaded for a channel so I tested the switch command and noticed it does the first and then updates the Channel Config. Most people I think would assume that is what will happen but might be worth calling it out explicitly. Just a general thought :).

**Comment by tjtelan** [comment]
> Sounds good. I read the link to the docs you have in the PR and all make sense to me.
> 
> Is the assumption that when someone wants to do an update for the Version branch that they need to be explicit and follow the steps you outline in your PR?
> 
> ```shell
> fluvio version create X.Y.Z
> fluvio version switch X.Y.Z
> ```
> 
Yes, but **update** is not the action want to attach to this workflow. Multiple versions can co-exist.

The idea is that `stable` and `latest` are moving targets that can be updated. The Version channels shouldn't ever update. If you were to switch to another version, you'll point to a separate binary that will be downloaded.

Long term, it would be nice to not use the `fluvio version create` step to download official binaries. Preferably `fluvio version switch X.Y.Z` only. (We don't need to take care of that friction in this issue.)

The original intent behind the `create` interface was to allow Fluvio devs to create local channels that point to their `cargo build` output but it is a lower priority feature.

> If so do we want to mention this in the error response or point the user to the docs with a link? I guess the concern in both scenarios would be trying to keeping the error message in-sync if links or commands change.
>
A mention in the error at least. Concern is warranted, but I don't see version channels being a frequently used feature in the short-term. We're exploring other ways to keep docs in sync with CLI commands as a much larger effort.

> When reading the Channel Docs PR, I was curious about when the binaries get downloaded for a channel so I tested the switch command and noticed it does the first and then updates the Channel Config. Most people I think would assume that is what will happen but might be worth calling it out explicitly. Just a general thought :).

Good call 👍 I'll point out when the download occurs.
