### ISSUE TITLE
Storage: Enforce size based retention for topic

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#2179]
The current retention policy only supports the time-based property.   This may result in a incorrect estimate of the total data size.  We should add max data size properties as part of retention. 

The topic should have new property: 'max_size' to indicate maximum data size will be allowed to accumulate.

**Comment by ExternalReality** [comment]
Hi @sehz, I'd like to take a look at this issue. At first glace it looks a good first issue that is beyond just a simple CLI fix. Would be a good idea to work this one as a new contributor?

**Comment by sehz** [comment]
Sounds good

**Comment by galibey** [comment]
@sehz Do we really want to have max size per topic or per partition will suffice? Per topic size calculation will require communication between nodes whereas per partition can be done locally.

**Comment by sehz** [comment]
Per partition make sense
