### ISSUE TITLE
Installer:   self-signs certs cause installation failure

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#2216]
steps reproduce it:
1.  Create Kubernetes cluster with self-signed certs
2. Installer will set up the cluster but SC and SPU pods are running correctly.

Please see: https://gist.github.com/tarokkk/be24d9c1fde100b21150fa26a6031ce9.  Installer terminates with error:
```
Error:
   0: Fluvio cluster error
   1: Failed to install Fluvio on Kubernetes
   2: Kubernetes client error
   3: error trying to connect: tls handshake: HandshakeError: the handshake failed: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1916:: unable to get issuer certificate
   4: error trying to connect: tls handshake: HandshakeError: the handshake failed: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1916:: unable to get issuer certificate
   5: tls handshake: HandshakeError: the handshake failed: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1916:: unable to get issuer certificate
   6: tls handshake: HandshakeError: the handshake failed: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1916:: unable to get issuer certificate
```

This is probably because K8 library doesn't add `ca.crt` in `kubernetes.io/service-account-token`.
```
kubectl get secret -n fluvio fluvio-token-5x5hb -o=jsonpath='{.data.ca.crt}' | base64 -D | openssl x509 -text                             *[master]
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            [xxx]
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=cluster-7133-ca
        Validity
            Not Before: Feb 14 09:37:46 2022 GMT
            Not After : Feb 13 10:38:16 2027 GMT
        Subject: CN=kubernetes-ca
```

**Comment by tarokkk** [comment]
Just to make clear that is 2 different error:
1. During the installation the rust Kubernetes client does not use/satisfied with the ca.crt in the KubeConfig it tries to search for the Issuer of that certificate. (`curl --cacert ca.crt https://x.x.x.x:6443/` work as expected)
2.  The fluvio service in-cluster config fails to authenticate probably mishandling kubernetes.io/service-account-token (described in the issue)

**Comment by wendyOn** [comment]
So OpenSSL has this X509_V_FLAG_PARTIAL_CHAIN thing
https://github.com/nodejs/node/issues/36453#issuecomment-743468716

a lot of node users have hit this with intermediary self-signed certs

curl has it enabled it by default
https://github.com/curl/curl/pull/4655

I could try enabling it in k8-client by default to fix this.

**Comment by wendyOn** [comment]
Hi, I've proposed a feature that would resolve this but I am lacking tests for this scenario.

@tarokkk would it be possible to see how did we create the openssl cert chain here exactly and which k8s are we using and what kind of configuration so Ic an repro as-is?

Thanks
