### ISSUE TITLE
[Bug]: Cannot use underscore in SmartModule name

### ISSUE THREAD

**Issue by nacardin** [infinyon/fluvio#2224]
**What happened**
Creating a smart module with a underscore in its name via the CLI, results in a vague error.

**Expected behavior**
CLI should state that underscore is not allowed in the name.

**Describe the setup**
Fluvio Cloud 0.9.20
Fluvio CLI 0.9.20

**How to reproduce it (as minimally and precisely as possible)**
1. Run the command `fluvio smart-module create data_cleanse --wasm-file example.wasm`

**Log output**
```
2022-02-23T18:39:39.090080Z ERROR K8StateDispatcher{spec="SmartModule" namespace="acct-0c8a1762-47ec-481e-94aa-6a106bae97ec"}:process_ws_action: fluvio_stream_dispatcher::dispatcher::k8_dispatcher: error: "SmartModule", update spec Client(
    422,
)
```

**Environment (please complete the following information):**
 - OS: Linux
 - Fluvio Version 0.9.20
 - Kubernetes version: 1.21.2

**Comment by morenol** [comment]
I think that this is related to https://github.com/infinyon/fluvio/issues/1464

**Comment by tjtelan** [comment]
This is essentially only workaround for the K8 api, which is [using DNS for resource names](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names).

If we want to support underscores here, then the scope should include adding support in Topics as well. This may mean using some kind of name encoding for the crds.

**Comment by nacardin** [comment]
Show error for now like topic creation
