### ISSUE TITLE
[CLI] User presentable errors should be mapped contextually out

### ISSUE THREAD

**Issue by wendyOn** [infinyon/fluvio#2240]
Errors that are in User interface - e.g. CLI need user errors as well as in contextual form.

Also Test automation should easily make these jump out in predictable form so we can increase velocity to address all UX errors without spending too much time on each.

The form should be in a way - e.g. Debug off the error - that enables fast velocity to addresses any missing errors when someone adds a negative test.

I've proposed a precedent on how to address it all here:
- #2238 

Also interfaces may need a bit checking:
- #2239

**Comment by nacardin** [comment]
Problem not defined
