### ISSUE TITLE
Replace `prettytable-rs` with another simple table formatter

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#2263]
It seems that `prettytable-rs` has been abandoned and there's a [PR for adding it to RustSec Advisory Database](https://github.com/rustsec/advisory-db/issues/1173).

There are no current reports of CLI issues related to prettytable, so I don't think this is urgent. But since there are a [lot of choices for replacements](https://lib.rs/keywords/table), I think this might come down to personal preferences.

We should balance to keep the table render as close as possible with minimal code changes.

**Comment by sehz** [comment]
done
