### ISSUE TITLE
Improve error reporting in smartmodule runtime errors

### ISSUE THREAD

**Issue by morenol** [infinyon/fluvio#2286]
When there is an error in the smartmodule execution, we get an error like this one:

```
 Error:
   0: Dataplane error: Other error: SmartModule err wasm trap: wasm `unreachable` instruction executed
   1: Other error: SmartModule err wasm trap: wasm `unreachable` instruction executed
```

We may want to have better error reporting, so it is more clear the cause of the failure

**Comment by tjtelan** [comment]
A simple way to trigger this issue is to use serde to deserialize a record to a struct, but mismatch the types.

example record:
The point is the value is an integer type.
```json
{"key":"12345"}
```

And the smart module, would look something like this:
Serde should fail to deserialize the json value into a `String`.
```rust
use fluvio_smartmodule::{smartmodule, Record, Result, SmartOpt};

#[derive(SmartOpt)]
pub struct FilterOpt {
    id: String,
}

impl Default for FilterOpt {
    fn default() -> Self {
        Self {
            id: "".to_string(),
        }
    }
}

#[derive(serde::Deserialize)]
struct TestRecord {
  key: String,
}

#[smartmodule(filter, params)]
pub fn filter(record: &Record, opt: &FilterOpt) -> Result<bool> {
    let test_record = serde_json::from_slice::<TestRecord>(record.value.as_ref())?;
    Ok(test_record.key.eq(&opt.key))
}
```

**Comment by sehz** [comment]
Let's open issue regarding WASM panic.  We can work with Wastime project to address panic issue

**Comment by galibey** [comment]
Created follow-up issue #3266.
