### ISSUE TITLE
[Bug]:`connector logs` doesn't work with InfinyOn Cloud

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/fluvio#2287]
Create a connector, then run

```
% fluvio connector logs discord-glucose
Error:
  0: Invalid argument: Connector discord-glucose does not exist
```

**Comment by nacardin** [comment]
Until we get this working, we should display a better error message indication that direct k8 access is required for this.

**Comment by ajhunyady** [comment]
Sounds good, but let's keep this bug around.

**Comment by sehz** [comment]
This is depend on #2223

**Comment by nacardin** [comment]
Should also handle `kubectl` not being installed

**Comment by ajhunyady** [comment]
completed
