### ISSUE TITLE
[Bug]: Precheck flight should give warning/error message if running in  cloud environment.

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/fluvio#2308]
```
% fluvio profile list
  PROFILE       CLUSTER       ADDRESS             TLS
 * cloud        cloud        router.infinyon.cloud:9003   Verified
  minikube      minikube      192.168.64.6:30003       Disabled

% fluvio cluster check
Current channel: stable
Running pre-startup checks...
  :white_check_mark: Kubectl active cluster minikube at: https://192.168.64.6:8443/ found
  :white_check_mark: Supported Kubernetes server 1.22.2 found
  :white_check_mark: Supported helm version 3.7.0+geeac838 is installed
  :white_check_mark: Can create service
  :white_check_mark: Can create customresourcedefinitions
  :white_check_mark: Can create secret
:broken_heart: Some pre-flight check failed!
Error:
  0: Fluvio cluster error
  1: Preflight check failed
```

Cluster error is too generic. It should guide me to a resolution.
For example, it could say
```
 [err]: your profile points to cloud
      Try switching profile `fluvio profile switch minikube`
```

**Comment by sehz** [comment]
Preflight check requires admin access to Kubernetes clusters.  Before running `cluster` any sub commands check for k8 access for profile and  warn them this requires Kubernetes access.

**Comment by morenol** [comment]
Will add a `--fix` flag to `fluvio cluster check` to try to fix recoverable checks.

Will update `fluvio cluster check --help` to indicate that user needs access to Kubernetes cluster and have the Kubernetes context set.

Will update `fluvio cluster check` to warn user that Kubernetes cluster is required

Will add a message to run `fluvio cluster check --fix` if a recoverable error is raised.
