### ISSUE TITLE
Make ClusterInstaller install `fluvio-sys` if it is not installed

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#235]
This could be a good step in improving the open-source user experience. Right now, you have to manually install both `fluvio-app` and `fluvio-sys`. We should be able to make our installer detect whether `sys` is installed and do it for the user, with options to override for specific use-cases like development.

**Comment by sehz** [comment]
there was issue with installing CRD in the helm chart before.  It maybe solved.   There are 2 options:
- Integrate `sys` and `app` chart into a single chart.  And have option to install combination of them.
- Make sys chart dependencies of `app` using helm dependencies.

**Comment by vijaylaxmid** [comment]
I think this is already done and can be closed. @sehz ?

**Comment by sehz** [comment]
Doesn't seems it works in the master

**Comment by vijaylaxmid** [comment]
I performed the following steps in the master. Seems to work fine. Do you see any difference?

```
$ fluvio cluster uninstall        
release "fluvio" uninstalled

$fluvio cluster uninstall --sys  
release "fluvio-sys" uninstalled

$fluvio cluster install --develop
NAME: fluvio-sys
LAST DEPLOYED: Thu Nov  5 00:44:44 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NAME: fluvio
LAST DEPLOYED: Thu Nov  5 00:44:49 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
waiting for spu to be provisioned for: 1 seconds
1 spus provisioned 
```

**Comment by sehz** [comment]
Works in the CI
