### ISSUE TITLE
3 phases of ACK back to SPU to update current offset.

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#2369]
The `last_read_offset` (naming not fully determined) we will add to [`ReplicaSlice`](https://github.com/infinyon/fluvio/blob/2d191918329c7f7b97b802022e79deeba1d6a8d1/crates/fluvio-storage/src/lib.rs#L112-L116) needs to be a incremented (and never decremented) via 3 flows:
* SPU sending a new batch - The offset should be `max(current_id, batch.start_id)` or whatever the variable names are
* When client recieves a new batch, the client must send some sort of [TCP/IP ACK](https://en.wikipedia.org/wiki/Transmission_Control_Protocol#TCP_segment_structure) back to the SPU with the batch's start ID.
* When a client reads a new record in the [`stream.next().await`](https://github.com/infinyon/fluvio/blob/2d191918329c7f7b97b802022e79deeba1d6a8d1/crates/fluvio/src/consumer.rs#L490-L523), this will also require sending the record's offset id back to the SPU for saving.

**Comment by sehz** [comment]
Client already send ACK back to SPU.

**Comment by morenol** [comment]
This spawn task do that:

https://github.com/infinyon/fluvio/blob/2d191918329c7f7b97b802022e79deeba1d6a8d1/crates/fluvio/src/consumer.rs#L365
