### ISSUE TITLE
CLI commands should check that minikubeCA in `/etc/hosts` is up-to-date

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#241]
Currently, Fluvio installs an entry to `/etc/hosts` when running `fluvio cluster set-minikube-context`. However, if minikube restarts or is deleted/recreated, the address may change and the `/etc/hosts` entry may become outdated. This currently causes silent errors which are confusing to debug.

We should make any CLI command that interacts with minikube perform a check that the `/etc/hosts` entry is up-to-date with the address of the live minikube instance. If the entry is not up-to-date, the command should gracefully exit and prompt the user to run `fluvio cluster set-minikube-context` to fix the setting.

- [ ] CLI commands should check for a valid `/etc/hosts` minikubeCA entry.
- [ ] CLI commands should exit early when minikubeCA is invalid
- [ ] CLI commands should prompt user to run `fluvio cluster set-minikube-context` when minikubeCA is invalid

**Comment by sehz** [comment]
Current this is broken in the master for latest minikube

**Comment by sehz** [comment]
no longer need since we switch to use `native-tls` for k8-client
