### ISSUE TITLE
[CLI] Delete commands should support multiple targets

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#2427]
We should allow the `fluvio [topic, smart-module, connectors, etc...] delete` to accept multiple names.

The intended outcome is that each of the names listed get deleted, as opposed to 1 command per resource.

Unless there are strong feelings for a different default behavior, in the event of an error, we should return an error to stderr, and exit on the first encounter. But if we provide a flag, something like `--force` or `--continue-on-error`, then cycle through all the names.

**Comment by ajhunyady** [comment]
What if a SmartModule is referenced in a Connector? I believe, we should prevent it from being deleted, otherwise, the connector may unexpectedly stop working.

**Comment by tomuxmon** [comment]
Hey, according to clap you can just Use `Vec<T>` and add `required = true` to disallow zero-length `Vec`.
Would look something like this:

```rust
#[derive(Debug, Parser)]
pub struct DeleteTopicOpt {
    /// The name of the Topic to delete
    #[clap(value_name = "name", required = true)]
    topics: Vec<String>,
}

impl DeleteTopicOpt {
    pub async fn process(self, fluvio: &Fluvio) -> Result<()> {
        let admin = fluvio.admin().await;
        for topic in self.topics.iter() {
            debug!("deleting topic: {}", topic);
            admin.delete::<TopicSpec, _>(topic).await?;
            println!("topic \"{}\" deleted", topic);
        }
        Ok(())
    }
}
```

I can prepare a pull request and see what it looks like.

**Comment by sehz** [comment]
done
