### ISSUE TITLE
SPU Group's TLS secret name is hardcoded (probabaly shouldn't be)

### ISSUE THREAD

**Issue by tothandras** [infinyon/fluvio#2434]
**What happened**

I'm using the Helm charts for deployment and noticed that my SPU Group is only able to come up when the TLS secret name (`cert.tls`) is defined as `fluvio-tls` (the default) because it seems to be hardcoded: https://github.com/infinyon/fluvio/blob/master/crates/fluvio-sc/src/k8/objects/spg_group.rs#L285

**Environment (please complete the following information):**
 - Fluvio Version: `0.9.27`
 - Kubernetes version: `1.22.8`

**Comment by sehz** [comment]
Hi, Let me see if I understand the issue.   This is about TLS Secret name is hard coded to `fluvio-tls`?

**Comment by tothandras** [comment]
@sehz yes

**Comment by sehz** [comment]
Why would that be an issue? it's just id.

**Comment by sehz** [comment]
I agree, that it should be configurable.  Contribution Welcome!

**Comment by udsamani** [comment]
@sehz Do you mind if I pick this up ? Looks like a good issue to start with !

**Comment by udsamani** [comment]
Just to make sure that all of us are on same page on what is happening here. 

- Currently we have hard coded `fluvio-tls` secret name everywhere. This is true even for `SC`. What I mean to say is that even if change value of `cert.tls` here : https://github.com/infinyon/fluvio/blob/master/k8-util/helm/fluvio-app/values.yaml#L16, it would not work as when we upload the secret to Kubernetes it is hardcoded (https://github.com/infinyon/fluvio/blob/2968b7af1e450f00e405d9527c9ad9637f4154da/crates/fluvio-cluster/src/start/k8.rs#L1257). I did a fun experiment of changing the value [here](https://github.com/infinyon/fluvio/blob/master/k8-util/helm/fluvio-app/values.yaml#L16), and found that SC would run into error.

### How do we solve it ?
- Idea would be to have an option for secret-name as part of TlsConfig, and pass it accordingly. We can keep it as optional and default it to `fluvio-tls`. 
- @sehz Do you feel the need for doing it for ca-cert too ? https://github.com/infinyon/fluvio/blob/2968b7af1e450f00e405d9527c9ad9637f4154da/crates/fluvio-cluster/src/start/k8.rs#L1250.


@sehz Let me know if you are fine with making both configurable. I can move ahead in that case. Sorry for the delay took a bit of time to get used to the code base.

**Comment by sehz** [comment]
Yes, this is good solution.  I dont' think we need do it for `ca-cert`.

**Comment by udsamani** [comment]
PR: #2788

**Comment by ajhunyady** [comment]
@tothandras, please let us know if the fix works for you.
