### ISSUE TITLE
[Test] Add connector regression testing

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#2439]
In preparation for https://github.com/infinyon/fluvio/issues/2433, we need some connector focused tests.

The point to make is that a cluster maintains its ability to interact with connectors over upgrade. And we expect connector traffic to be maintained as well.

First thought scenarios for `CD_Dev`:
* Stable cluster + connector
Create a cluster from the current stable. Then create a connector, then verify it.
* Stable cluster then upgrade + new connector
Create a cluster from the current stable, upgrade to `latest`, create a new connector, then verify it.
* Stable cluster + connector then upgrade + new connector
Create a cluster from the current stable, create a connector, upgrade to `latest`, create another new connector, then verify both connectors.

For verification, run for 5 minutes and verify the topic offset never stops increasing

(w/ respect to data source update frequency)

**Comment by morenol** [comment]
I think that we also should add a
