### ISSUE TITLE
[Bug]: CLI tries to use the k8s Node's InternalIP instead of the ExternalIP when reaching the public SC endpoint

### ISSUE THREAD

**Issue by tothandras** [infinyon/fluvio#2441]
**What happened**

- `InternalIP`: IP address of the node accessible only from within the cluster
- `ExternalIP`: IP address of the node accessible from everywhere

It seems like the intention was to use the `ExternalIP` based on this comment:
https://github.com/infinyon/fluvio/blob/master/crates/fluvio-cluster/src/start/k8.rs#L732

Still, the `InternalIP` is being used:
https://github.com/infinyon/fluvio/blob/master/crates/fluvio-cluster/src/start/k8.rs#L750
https://github.com/infinyon/fluvio/blob/master/crates/fluvio-cluster/src/start/k8.rs#L926

I guess you deploy your cloud service behind an in-cluster proxy.

**Expected behavior**

Use the Node's external IP to be able to access it publicly when the service type is NodePort. I'd also consider dropping support for NodePort services, because with TLS you'd probably need a proxy anyway.

**Describe the setup**

- DigitalOcean Kubernetes `1.22.8`
- Fluvio `0.9.29`

**How to reproduce it (as minimally and precisely as possible)**

1. `fluvio cluster start`
```
📝 Running pre-flight checks
    ✅ Kubectl active cluster do-fra1-k8s-1-22-8-do-1-fra1-1656321479334 at: https://7f5663e8-cfc6-4014-8523-f3b649fc8935.k8s.ondigitalocean.com found
    ✅ Supported helm version 3.9.0+g7ceeda6 is installed
    ✅ Supported Kubernetes server 1.22.8 found
    ✅ Fixed: Fluvio Sys chart 0.9.29 is installed
    ✅ Previous fluvio installation not found
🎉 All checks passed!
✅ Installed Fluvio app chart: 0.9.29
🖥️  Trying to connect to SC: 10.114.0.5:30003 242 seconds elapsed -
```

```
kubectl get nodes,pods,svc -o wide                                                                                                  Recog-MacBook-Pro.local: Tue Jun 28 15:28:49 2022

NAME                        STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP      OS-IMAGE                       KERNEL-VERSION         CONTAINER-RUNTIME
node/pool-img6oqaou-ck6dw   Ready    <none>   57m   v1.22.8   10.114.0.5    206.189.50.124   Debian GNU/Linux 10 (buster)   5.10.0-0.bpo.9-amd64   containerd://1.4.13
node/pool-img6oqaou-ckqh9   Ready    <none>   28h   v1.22.8   10.114.0.2    164.92.190.191   Debian GNU/Linux 10 (buster)   5.10.0-0.bpo.9-amd64   containerd://1.4.13

NAME                             READY   STATUS    RESTARTS   AGE   IP             NODE                   NOMINATED NODE   READINESS GATES
pod/fluvio-sc-548949d57f-wr9vr   1/1     Running   0          17m   10.244.1.123   pool-img6oqaou-ck6dw   <none>           <none>

NAME                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE   SELECTOR
service/fluvio-sc-internal   ClusterIP   10.245.255.113   <none>        9004/TCP         17m   app=fluvio-sc
service/fluvio-sc-public     NodePort    10.245.61.59     <none>        9003:30003/TCP   17m   app=fluvio-sc
service/kubernetes           ClusterIP   10.245.0.1       <none>        443/TCP          28h   <none>
```

**Comment by sehz** [comment]
Similar issue on latest version of EKS: `Kubernetes server 1.21.12-eks-a64ea69 found`

**Comment by digikata** [comment]
A potential fix for this was merged to master. If there are problems on retest, please reopen the issue.
