### ISSUE TITLE
[Bug]: Producer failed to retrieve record metadata when sending more than one batch in a request

### ISSUE THREAD

**Issue by morenol** [infinyon/fluvio#2443]
**What happened**
When the request of producer has more than one batch.
 The producer only sends back the base offset of the first batch. Therefore batch metadata is not resolved for the batches that are after the first one.

**Expected behavior**
record metadata in:
```rust
let produce_output = producer.send(RecordKey::NULL, value).await?;
let record_metadata = produce_output.wait().await?;
```
should not fail with : `receiving from an empty and closed channel`

**How to reproduce it (as minimally and precisely as possible)**
1. Run the command:
fluvio topic create topicname
fluvio produce topicname -f input.txt

with this file:
[input.txt](https://github.com/infinyon/fluvio/files/9003188/input.txt)

**Comment by digikata** [comment]
The odd part is that TJs stat branch pr does not have the same problem if you add the --stats flag.
