### ISSUE TITLE
Connector: Enforce version field as mandatory

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#2456]
[Right now in the connector yaml if the `version` field isn't specified, the connector defaults to `latest`](https://github.com/infinyon/fluvio/blob/749df76b6a277bbb3a8c966b511c2b9ad7002ca8/crates/fluvio-sc/src/k8/controllers/managed_connector_deployment.rs#L267-L274) which means that if the connector is re-created (or if the cluster is upgraded), the connector will try to get the `latest` image which may have breaking changes.

If the `version` field is unspecified, the connector should pin the version of the latest image and this image version/tag should be pinned to the version it was created with.

**Comment by ajhunyady** [comment]
I suggest to make `version` a mandatory field. Though the problem here is that the yaml file is not backward compatible. Once we are in production, we'll need a backward compatibility policy. I suggest 2 releases before aging a field. @sehz, we need to agree on the time period.

**Comment by nacardin** [comment]
Semantic versioning solves this. We should make `version` mandatory and use SemVer to determine when to update.

**Comment by sehz** [comment]
Either it is mandatory or not.  Let's make it mandatory
