### ISSUE TITLE
Identify type of SmartModule by signature

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#2457]
Right now in order to use a SmartModule, the user has to identify the type of SmartModule 

Example: Fluvio CLI consume
```
$ fluvio consume --filter my-filter example-topic
$ fluvio consume --map my-map example-topic
```

But this can be a little confusing, and you can easily make mistakes.

Example of potential error
```
$ fluvio consume --array-map my-mystery-smartmodule example-topic
```

It seems like name should suffice, and the responsibility for type checking should go to the cluster.

Example w/ more generic flag
```
$ fluvio consume --smartmodule my-mystery-smartmodule example-topic
```

**Comment by ajhunyady** [comment]
Great suggestion!
