### ISSUE TITLE
Does support for keep records forever ?

### ISSUE THREAD

**Issue by Matrix-Zhang** [infinyon/fluvio#2467]
Some times maybe we should do some analytics from begining,
when i create the topics with --retention-time 0, it will failed

**Comment by sehz** [comment]
Currently, You can do this by setting a very long retention period (years).  But I agree explicit disabling would be simpler.  Note that, if you increase retention or disabling it would increase the chance of filling up a topic and may cause the producer to fail.

**Comment by Matrix-Zhang** [comment]
so,  how to config the storage size in k8s cluster? i don't find any mount config

**Comment by sehz** [comment]
Looks like it's not exposed directly.  Will add them in issue #2469.   Keep this issue for disabling retention
