### ISSUE TITLE
Add Minimum supported Rust version (MSRV) check to CI

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#2510]
This one caught me while trying to fix the Fluvio website CI.

The root cause of the failure was the Rust Docker image we were using as a reference environment.

It was using `rust:1.61` but new updates to the repo use new standard traits, so the minimum version the `fluvio` crate will build on is `1.62.1`.

Maybe we can use this?
https://github.com/marketplace/actions/minimum-supported-rust-version

**Comment by aaronaaeng** [comment]
I'll take this.  Do you think this should be handled on merges to `master` or should it run as a weekly cron job?  I've noticed that running `msrv` takes 15-20 minutes for the repository.  I personally prefer the idea of running it on each new merge so that it's updated with the code changes.

**Comment by sehz** [comment]
Yes, let's try to run on each commit.
