### ISSUE TITLE
Throughput Control

### ISSUE THREAD

**Issue by galibey** [infinyon/fluvio#2512]
We need to find a way to control the throughput that we produce during integration testing. Currently, it is limited only by available system resources and is unstable due to that fact. 

We need to figure out on which level we want to do this. Possible options: `fluvio-test` where we generate the test data or `fluvio` client where we can add a back pressure mechanism to control the throughput that goes to the Producer.

**Comment by tjtelan** [comment]
I vote for adding this in `fluvio`, and adding a `fluvio-test` test to externally verify the throughput based on client configuration.

**Comment by sehz** [comment]
We need to fix this ASAP with CI becoming more flaky
