### ISSUE TITLE
[Bug]: Installation behind proxy environments

### ISSUE THREAD

**Issue by sysarcher** [infinyon/fluvio#2517]
**What happened**
While installing behind a corporate proxy environment, the `fluvio` binary does not respect environment `http_proxy`, `https_proxy` variables. So, in the installation script, the command `fluvio install fluvio-cloud` fails

**Expected behavior**
Installation should succeed even behind an HTTP proxy.

**Describe the setup**
- Setting up fluvio right now

**How to reproduce it (as minimally and precisely as possible)**
1. Run the command '...'
2. Type the input '...'

**Log output**
```
# BEHIND HTTP_PROXY and HTTPS_PROXY env
curl -fsS https://packages.fluvio.io/v1/install.sh | bash
fluvio: ⏳ Downloading Fluvio 0.9.32 for x86_64-unknown-linux-musl...
fluvio: ⬇️  Downloaded Fluvio, installing...
fluvio: ✅ Successfully installed /home/intel/.fluvio/bin/fluvio-stable
fluvio: ⏳ Downloading Fluvio channel frontend 0.9.32 for x86_64-unknown-linux-musl...
fluvio: ✅ Successfully installed /home/intel/.fluvio/bin/fluvio
fluvio: ☁️ Installing Fluvio Cloud...
Current channel: stable
Error: 
   0: Http Error: Network unreachable (os error 101)
```

**Environment (please complete the following information):**
 - OS: Linux
 - Fluvio Version: stable, CLI: 0.9.32

**Additional context**
Installation behind corporate proxy environment

**Comment by whoconli** [comment]
I have the same problem, can the Fluvio Cloud and Fluvio Runner be installed by source code?

**Comment by sehz** [comment]
Curl provides a proxy setting.  Can you try this:
```
curl -fsS https://packages.fluvio.io/v1/install.sh --proxy <your_proxy> | bash
```

See this also: https://oxylabs.io/blog/curl-with-proxy

**Comment by sysarcher** [comment]
@sehz `curl` works behind the proxy. It's the `fluvio` binary that fails.

**Comment by sehz** [comment]
Got it.  We will add support in the next release.

**Comment by sysarcher** [comment]
@sehz awesome, thank you!!

**Comment by sehz** [comment]
This is now part of the dev release.  Can you try, please?  You can use the dev release by:
```
$ fluvio version switch latest
$ fluvio update
``
