### ISSUE TITLE
Topic-level Permissions for Producers and Consumers

### ISSUE THREAD

**Issue by AshleySchaeffer** [infinyon/fluvio#2528]
I have a use case whereby I wish to deploy producers in third-party environments owned by different entities. Inline with requirements (the data I intend to transfer via Fluvio is sensitive) I need to limit access to topics. 

At present, authentication of Fluvio producers and consumers is facilitated through the use of a client certificate, but it looks **like once authentication succeeds it is possible to consume from and produce to any topic**. This means one badly handled client certificate could lead to the compromise of all data transiting Fluvio, permit contamination of data transferred via all topics, and potentially expose downstream systems.

While this scenario can not be entirely mitigated (Fluvio can not mitigate mishandled client certificates), it would certainly be a mitigating factor if permissions could be restricted such that producers could only write to specific topics, and consumers could only read from specific topics.

I may be wrong, but it doesn't seem to be possible to work around this issue via a filtering SmartModules as they sit within producers and consumers themselves, not within the Fluvio SPU (server-side).

Would it be possible to implement an authorisation model such that a producer/consumer could be restricted to producing and/or consuming, to or from specified topics?

I believe [NATS has good implementation of this](https://docs.nats.io/running-a-nats-service/configuration/securing_nats/authorization), whereby you can specify user permissions at a subject-level if inspiration is needed.

PS. Fluvio looks super promising, great work!

**Comment by sehz** [comment]
Great question.

Currently, SC implements a generalized policy for accessing objects:  https://github.com/infinyon/fluvio/blob/master/crates/fluvio-auth/src/policy.rs.   We could extend to SPU as well.  We just haven't got around it.  SPU internally uses SmartModule to filter out outgoing traffic (consumer traffic), so it would not be that much work to apply to incoming requests.    With SmartModule, you would not be limited to the static configuration but can use the OpenPolicy rule or write your policy.

**Comment by AshleySchaeffer** [comment]
I think this issue may also affect my use case:

https://github.com/infinyon/fluvio/issues/2517

I don't know whether this has been overlooked, but I feel like solving these issues would allow Fluvio to be used exclusively of other data streaming solutions or bespoke setups. My intention is to deploy Fluvio producers in numerous third-party environments so that I don't have to bother with Kafka, a microservice, or some other sudo-proxy solution, before the data arrives in the Fluvio cluster. The fewer hops to Fluvio the better. It would make both development and operations a breeze.

**Comment by sehz** [comment]
Sorry, I was probably not clear on the explanation.

When Consumer or Producer communicates SPU, it performs the following activities:
1) It connects to SPU's public port.
2) TLS validation occurs; invalidated TLS session gets dropped at this point (This assumes TLS)
3) SPU then performs actions

The flow in the SC is similar, except for auth/session check: https://github.com/infinyon/fluvio/blob/master/crates/fluvio-sc/src/services/public_api/public_server.rs after TLS.  So we could insert similar auth checks in the SPU as well.

**Comment by AshleySchaeffer** [comment]
Sounds great! Thanks for your time.
