### ISSUE TITLE
Documentation: wrong flag listed in k8-util/helm/README.md

### ISSUE THREAD

**Issue by mfdorst** [infinyon/fluvio#2555]
The [readme] says:
> Then to install sys chart:
> ```
> $ fluvio cluster start --sys
> installing sys chart
> ```
But there is no `--sys` flag. There is a `--sys-only` flag, is that the one that's intended?

[readme]: https://github.com/infinyon/fluvio/blob/master/k8-util/helm/README.md

**Comment by sehz** [comment]
Good catch.  It's now should be: `--sys-only`

**Comment by mfdorst** [comment]
Oh this needs to be updated on the site as well https://www.fluvio.io/docs/kubernetes/install/#install-multiple-instances-of-fluvio
