### ISSUE TITLE
CI: Report outdated dependencies

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#2559]
It would be good to show outdated dependencies.
It should be triggered by either
- merged into Master
- workflow_dispatch

**Comment by tjtelan** [comment]
This probably looks like adding https://lib.rs/crates/cargo-outdated  to the [CI checks job](https://github.com/infinyon/fluvio/blob/473bee631c8a5ac9e69fbb842e470fbd3a661bca/.github/workflows/ci.yml#L249)

**Comment by sehz** [comment]
Or have dependotbot do that for us.  Noticed that we don't have one
