### ISSUE TITLE
Create common GitHub Action for installing Fluvio

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#257]
Github Actions can be independently defined in order to be used as a dependency for workflows. This would be useful if we want to have Fluvio apps that want to test on a Fluvio installation in CI.

See https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

**Comment by Ryanmtate** [comment]
Going to create a composite actions step for this. Will use/test it in the node client smoke test;
