### ISSUE TITLE
[Bug]: a 0.9.34 docker tag is not publicly published

### ISSUE THREAD

**Issue by gregwebs** [infinyon/fluvio#2584]
**What happened**

fluvio cluster create failed because it the pod could not pull the docker image because the specific tag being used did not exist.

```
kubectl describe pod fluvio-sc
...
  Normal  BackOff  70s (x768 over 176m)  kubelet  Back-off pulling image "infinyon/fluvio:0.9.34"
```

It seems the tag is not published.

```
docker pull infinyon/fluvio:0.9.34
Error response from daemon: manifest for infinyon/fluvio:0.9.34 not found: manifest unknown: manifest unknown
```

I worked around this by tagging a recent 0.9.34-* release as 0.9.34 and then importing that.

**Expected behavior**
The pod downloads its docker image

**Describe the setup**
- Linux with k3d

**How to reproduce it (as minimally and precisely as possible)**
I followed along the installation instructions for Linux

**Comment by sehz** [comment]
Can you run:
```
$ fluvio version
```

0.9.34 is not released so not sure how did you get that version?

**Comment by gregwebs** [comment]
Sorry, I didn't clarify in this issue that I am following the Linux installation but that I am building the fluvio cli from source instead of downloading the prebuilt. So this is probably not a supported workflow and I am supposed to use `--develop`.

Although when I use `--develop` I see

```
  Warning  Failed     4m28s (x4 over 6m4s)  kubelet            Error: ErrImagePull
  Warning  Failed     4m16s (x6 over 6m4s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    62s (x20 over 6m4s)   kubelet            Back-off pulling image "infinyon/fluvio:27a10a4876c348011fd2bee01ebc2a6a8deaccba"
```

I think the instructions are just missing a mention of the need to download and import the image into the cluster, at least for k3d?

**Comment by morenol** [comment]
You need to import the image or run `make build_k8_image`, that will build and load the image to k3d/minikube

**Comment by gregwebs** [comment]
@morenol thanks! I didn't realize that it also imported the image into the cluster, that's convenient! I added that to the documentation here: https://github.com/infinyon/fluvio/pull/2585
