### ISSUE TITLE
Remove dependency on POSIX coreutils

### ISSUE THREAD

**Issue by BatmanAoD** [infinyon/fluvio#2597]
This is a suggested companion ticket to #1131.

The following `Command`s invoke coreutils:

```
Command::new("pgrep")
Command::new("pkill")
Command::new("sync")
```

These are not available by default on Windows, and the functionality they provide should be available either in the standard library or in Rust crates.

`pgrep` and `pkill` can be replaced using the SysInfo crate ([process search](https://docs.rs/sysinfo/latest/sysinfo/trait.SystemExt.html#method.processes_by_exact_name), [signalling](https://docs.rs/sysinfo/latest/sysinfo/trait.ProcessExt.html#tymethod.kill_with)).

The POSIX `sync` doesn't appear to have an exact equivalent in the Windows API; it appears that Windows only permits syncing [specific filehandles](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-flushfilebuffers). But it seems preferable to only flush the files pertinent to Fluvio anyway, rather than all system files.

**Comment by sehz** [comment]
fixed
