### ISSUE TITLE
Update Rust example applications for new API

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#261]
The current Rust example applications are using an older version of the Fluvio APIs. After we examine the updates we want to make to the interfaces, we will need to update the examples.

### Examples:

- [x] Echo example (the "Hello world" of Fluvio) #305 
- [x] Change-Data-Capture (MySQL replication) ~#315~ (moved to https://github.com/infinyon/fluvio-demo-apps-rust)

**Comment by sehz** [comment]
Is this done? If so, close it
