### ISSUE TITLE
SMDK: Generate new Smart module project 

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#2621]
Generate Rust SmartModule project for SmartModule development kit (SMDK).
It has two command, `initialize` and `new`.  

1. New command will create new project in separate directory
```
$ smdk new <project_name>
```
It should prompt for 
* Smart Module type
* Whether to include initialization (if so, generate generate skeleton)

After prompt, it should generate Cargo project plus `SmartModule.toml` metadata

2. Init command will create project in same directory using project name from direct name (similar to Cargo)

It should include cargo profile to set default to `wasm32-unknown-unknown` and LTO flag set

Generate command should be able to generate `smartmodule/sm-regex`

**Comment by EstebanBorai** [comment]
Hi @sehz, I'm working on this feature on #2630 and I wanted to know how do we manage different SmartModule versions?
So far the branch at #2630 generates the project similar to how we do today with `cargo-generate` by running `fluvio smart-module generate` as follows:

```bash
fluvio smart-module generate <NAME>
```

Where would we take versions from in this case? I can see the template on https://github.com/infinyon/fluvio-smartmodule-template has no versions/tags available neither.

**Comment by sehz** [comment]
This depends on getting initial `SMDK` setting up crate
