### ISSUE TITLE
How to dispatch mapped topic values to another topic.

### ISSUE THREAD

**Issue by rhrn** [infinyon/fluvio#2647]
Hi everyone!
For example, I have source topic and, and I need target topic with mapped values. 
How can I do with platform features (connectors)?
```
#topic "source_values"
--{1}--{2}--{3}--
#topic "source_values_mapped"
--{2}--{4}--{6}--
```

**Comment by sehz** [comment]
One way to accomplish this is to pipe the result of the consumer with mapping and pipe back to the producer:
```
$ fluvio consume topicA --smart-module map_module | fluvio produce topicB
``` 

Where `map_module` is map SmartModule.   We have a roadmap item to pipe one topic to another topic.

**Comment by digikata** [comment]
Another way  to do this is with a  connector and the fluvio crate in the project.

Use `cdk` to build a connector with consumer/producer parameters. (connector config already has input topic and smartmodule configs.).

Or you can talk to @drc-infinyon our product manager about getting onto our preview releases which have another way to do this.

**Comment by ajhunyady** [comment]
@sehz this is a good use case for `ssdk`

**Comment by ajhunyady** [comment]
Implemented by SDF - https://github.com/infinyon/stateful-dataflows-examples/tree/main/primitives/map
