### ISSUE TITLE
[Bug]: Auto fix for Fluvio Sys Chart failed

### ISSUE THREAD

**Issue by crajcan** [infinyon/fluvio#2651]
**What happened**
I tried to run `flvd cluster start --develop` as recommended by the developer guide, but received an error saying that the "System chart was not found". I expected the system chart to be generated and installed automatically, but the 'Auto fix' procedure failed.

After trying to create and install the Helm charts using the Helm CLI, I get:

```
📝 Running pre-flight checks
    ✅ Supported helm version 3.10.0+gce66412 is installed
    ✅ Kubectl active cluster rancher-desktop at: https://127.0.0.1:6443 found
    ✅ Supported Kubernetes server 1.24.6+k3s1 found
    ✅ Local Fluvio is not installed
    🟡️ System chart version 1.16.0 installed, upgrading to version 0.9.34 /  
    ❌ Auto fix for Fluvio Sys Chart failed ChartInstall(
    IoError(
        Custom {
            kind: InvalidData,
            error: "no chart found",
        },
    ),
)
💔 Some pre-flight check failed!
Error: 
   0: Fluvio cluster error
   1: Preflight check failed
```

**Expected behavior**
According to the dev guide, the Helm charts are "generated from CLI installer instead of from the helm registry". I understood this to mean that the 'Auto fix' step would generate the appropriate charts. 

Can I downgrade the version of the chart somehow?

**Describe the setup**
Building from source locally @3099d6. 

I installed Helm using Brew:

```
λ: helm version
version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.19.1"}
```
and I'm using rancher desktop.

**Comment by sehz** [comment]
Did you built CLI using `make build-cli`?

**Comment by crajcan** [comment]
> Hi, that should not happen. Did you build CLI using `make build-cli`?

I was using the `cargo run` alias from `DEVELOPER.md`:

```
alias flvd='cargo build --manifest-path="/Users/nick/infinyon/fluvio/Cargo.toml" --bin fluvio-run && \
    cargo run --manifest-path="/Users/nick/infinyon/fluvio/Cargo.toml" --bin fluvio --'
```

But I got the same result when I built with `make build-cli`:

```
λ: ./target/debug/fluvio cluster start --local
*** running local preflght check
📝 Running pre-flight checks
    ✅ Supported helm version 3.10.0+gce66412 is installed
    ✅ Kubectl active cluster rancher-desktop at: https://127.0.0.1:6443 found
    ✅ Supported Kubernetes server 1.24.6+k3s1 found
    ✅ Local Fluvio is not installed
    🟡️ System chart not installed, installing version 0.9.34 / 
    ❌ Auto fix for Fluvio Sys Chart failed ChartInstall(
    IoError(
        Custom {
            kind: InvalidData,
            error: "no chart found",
        },
    ),
)
💔 Some pre-flight check failed!
Error: 
   0: Fluvio cluster error
   1: Preflight check failed
```
