### ISSUE TITLE
Add -p <package> option to smdk to support cargo workspace projects

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#2652]
Right now `smdk build` builds a whole project for `wasm32-unknown-unknown`. This isn't ideal for [cargo workspaces](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html). 

Let's add a `smdk [build,test,load] -p, --package [<SPEC>...]` that passes the `-p <package>` down to the cargo exec.

If it's not too much work, let's do the same for `smdk test`. Looks like we're already using the [`cargo_metadata` crate to get the path so let's leverage that](https://github.com/infinyon/fluvio/blob/c540c3a6ca488261edd20cdfdb95fdf50a050483/crates/smdk/src/wasm.rs#L27-L50).

**Comment by sehz** [comment]
It would probably be better if we just passed arbitrary flags to cargo like:
```
$ smdk build -- --p my-module
```

**Comment by sehz** [comment]
@superstator update?

**Comment by superstator** [comment]
I had this working for `build`, but got  pulled onto other things before I could attack the other commands. I can make it a priority again if we want it asap.

**Comment by sehz** [comment]
Let's get this done
