### ISSUE TITLE
bug: Fix SmartModule List not showing proper status

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#2667]
This issue list couple of issues with current SmartModule list
* SmartModule API return entire SmartModule spec including actual WASM.  This is not needed for list
* Status is not useful
* Size should be be displayed more compact way
* Latest version is not compatible with last release 0.9.33

**Comment by ajhunyady** [comment]
We also need to add `Source`: Hub/Local

**Comment by ajhunyady** [comment]
+ Fully qualify, or ID: `infinyon/regex-filter@0.1.0`

**Comment by sehz** [comment]
Hub status will be done in separate issue.
