### ISSUE TITLE
finish migration to stable

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#267]
- build and unit tests passes
- all smoke test pass
- CI works

**Comment by sehz** [comment]
depends on #274

**Comment by sehz** [comment]
also depends on https://github.com/infinyon/flv-kf-protocol/issues/20

**Comment by Ryanmtate** [comment]
@sehz is this ready to be closed?

**Comment by sehz** [comment]
closing this issue since all requirement has been met
