### ISSUE TITLE
[Bug]: `fluvio cluster start` fails on Mac

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/fluvio#2722]
I noticed this during issue on a fresh install a few days ago. It was also reported by `xzkxaicxjp` in Discord.
This issue was reported on MacOS Monterey 12.6.

![image](https://user-images.githubusercontent.com/26554085/196742021-0bcf0c01-b2de-4335-908d-b83996d5c4c1.png)

![image](https://user-images.githubusercontent.com/26554085/196742187-4d368b4f-1512-454a-a7ae-50aca6742540.png)

**Comment by ajhunyady** [comment]
Is this a workaround or the solution? Should we update the documentation?

**Comment by sehz** [comment]
This is documented already.

**Comment by ajhunyady** [comment]
It's not... no reference to `proxy` https://www.fluvio.io/docs/get-started/mac/

**Comment by morenol** [comment]
I think that `proxy-addr` is not needed

**Comment by ajhunyady** [comment]
It fails without it.

**Comment by ajhunyady** [comment]
Proof that the `--proxy-addr` os required:

<img width="872" alt="image" src="https://user-images.githubusercontent.com/26554085/196808939-0f39d6f8-f4f1-40e9-9dd3-7aa6f2d61c73.png">

**Comment by ajhunyady** [comment]
@tjtelan @sehz we have 2 options:
* make the installation work without the `--proxy-addr` flag
* update the documentation to include `--proxy-addr` flag

**Comment by sehz** [comment]
For this release, we will update doc.  Will add next to release to automatically configure proxy-addr

**Comment by EstebanBorai** [comment]
Im setting `localhost` as proxy address for k8s environment as default value for macOS here: https://github.com/EstebanBorai/fluvio/commit/c38fa5f19977c1917b6fdc9f8f166ab50274caa8

Im testing locally and will open the PR for review soon. This way users don't have to do it theirselves.
