### ISSUE TITLE
[Bug]: All `fluvio hub` command return errors after switching `id`

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/fluvio#2727]
Set environment variable:
* INFINYON_HUB_REMOTE=...

Steps to reproduce:
% smdk hub id    
infinyon

 % smdk hub id aj 
hubid currently set to infinyon
hub: hubid aj is set

 % smdk hub id
Error: Hub access: Could not load from /../hub/90c6bcbebe1ee2fbc68ebfb1886d71d4316b9a2e0fb33c6a09577fa136449e67eebf544333776ef16358e6b3177af5f8a80e840ad749b4750e238403766a4378

Other commands that fail:

 % fluvio hub list
Error: 
   0: Hub error: missing access credentials, try 'fluvio cloud login'

 % smdk load            
Loading package at: /../smartmodule/my-filter
Found SmartModule package: my-filter
Please set a value for `group` in /../my-filter/SmartModule.toml

**Comment by digikata** [comment]
Still analyzing a bit more, but added one item in the path of this case.
