### ISSUE TITLE
cd_dev workflow broken

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#2779]
https://github.com/infinyon/fluvio/actions/runs/3406019765/jobs/5664419711

This is due to changes in: https://github.com/infinyon/fluvio/pull/2766

**Comment by davidbeesley** [comment]
Much of this has been fixed. However, CI-DEV is still unreliable due to `./install.sh` sometimes installing a different (usually second to last) commit than the head of the master branch.

Example
https://github.com/infinyon/fluvio/actions/runs/3447574936/jobs/5753722175

**Comment by tjtelan** [comment]
It's likely this was a result of caching. Our publish process modifies the contents of tag files. The file name doesn't change so we need a strategy that can accommodate rapid changes for testing on the `latest` channel.

Was suggested to look into the object entity tags.

**Comment by sehz** [comment]
was due to caching issue. closing
