### ISSUE TITLE
[Bug]: fluvio produce is very slow

### ISSUE THREAD

**Issue by davidbeesley** [infinyon/fluvio#2808]
**What happened**

I ran some tests and got very poor performance when producing with fluvio-cli

setup
```
fluvio topic create hello
cat data.txt | fluvio produce hello  [--delivery-semantic at-most-once]
```

Separate terminal
```
fluvio consume hello | tqdm --bytes > /dev/null
```

| Cli Version | Delivery Semantic | Cluster Version             | Throughput |
|-------------|-------------------|-----------------------------|------------|
| latest      | --at-least-once   | 0.10.1 (dev-infinyon-cloud) | 62 B/s     |
| latest      | --at-most-once    | 0.10.1 (dev-infinyon-cloud) | 2.7 MB/s   |
| stable      | --at-least-once   | 0.10.1 (dev-infinyon-cloud) | 62 B/s     |
| stable      | --at-most-once    | 0.10.1 (dev-infinyon-cloud) | 2.8 MB/s   |
| latest      | --at-least-once   | 0.10.1 (minikube)           | 33 B/s     |
| latest      | --at-most-once    | 0.10.1 (minikube)           | 3 MB/s     |
| stable      | --at-least-once   | 0.10.1 (minikube)           | 21 B/s     |
| stable      | --at-most-once    | 0.10.1 (minikube)           | 2.6 MB/s   |
| latest      | --at-least-once   | 0.10.0 (cloud)              | 18 B/s     |
| latest      | --at-most-once    | 0.10.0 (cloud)              | 2.7 MB/s   |
| stable      | --at-least-once   | 0.10.0 (cloud)              | 18 B/s     |
| stable      | --at-most-once    | 0.10.0 (cloud)              | 1.2 MB/s   |
| latest      | --at-least-once   | 0.10.0 (minikube)           | 22 B/s     |
| latest      | --at-most-once    | 0.10.0 (minikube)           | 3 MB/s     |
| stable      | --at-least-once   | 0.10.0 (minikube)           | 28 B/s     |
| stable      | --at-most-once    | 0.10.0 (minikube)           | 3 MB/s     |

I think it ties into this block here when `wait()` is called on `produce_output` after every single record.
`fluvio-cli/src/clinet/produce:404`
```
            while let Some(Ok(line)) = lines.next() {
                let produce_output = self.produce_line(producer, &line).await?;

                if let Some(produce_output) = produce_output {
                    if self.delivery_semantic != DeliverySemantic::AtMostOnce {
                        // ensure it was properly sent
                        produce_output.wait().await?;
                    }
                }
```

I'm not sure yet what the significance of calling `wait()` is.
There are a lot of moving pieces here that I'm still trying to sort out.
1. DeliverySemantic: `at-most-once` vs `at-least-once`
2. ProducerIsolation: `read-commited` and `read-uncommited` with respect to producer and in context of `DeliverySemantic`. The docs mention ProducerIsolation in a somewhat contradictory manner here (https://www.fluvio.io/docs/concepts/delivery-semantics/#at-most-once) and here (https://www.fluvio.io/docs/concepts/data-consistency/#producer-isolation).

3. `wait()` vs `flush()`, especially with respect to batching, `DeliverySemantic`, and `ProducerIsolation`

That said, it seems like the default behavior is not very optimal.

**Comment by morenol** [comment]
Could you try increasing the linger time?

**Comment by morenol** [comment]
Also could you try using --file instead of piping file with stdin?

**Comment by davidbeesley** [comment]
> Could you try increasing the linger time?

Increasing linger time make performance much much worse. It appears that as currently implemented the linger time provides a lower bound for the latency (it is only sending once it timeouts I guess?) so with a linger time of `1s`, only one message per second is sent.

**Comment by davidbeesley** [comment]
> Also could you try using --file instead of piping file with stdin?

Running against the cloud, I get 40kb/s.

It looks like the main difference is that it sends all the records, then calls `produce_output.wait()` for all of them, instead of one at a time.
