### ISSUE TITLE
[Bug]: Failure to create topic

### ISSUE THREAD

**Issue by davidbeesley** [infinyon/fluvio#2836]
**What happened**
Fluvio cli fails trying create a topic 

**Describe the setup**
- Fails on local fluvio cluster (minikube)
- Error not present against cloud after creating, producing, and deleting a separate topic.

**How to reproduce it (as minimally and precisely as possible)**
```rust
use fluvio::{metadata::topic::TopicSpec, FluvioAdmin, RecordKey};
#[async_std::main]
async fn main() {
    for i in 0..2 {
        let name = format!("topic-{i}");
        let new_topic = TopicSpec::new_computed(1, 1, None);
        let admin = FluvioAdmin::connect().await.unwrap();
        admin.create(name.clone(), false, new_topic).await.unwrap();
        let producer = fluvio::producer(name.clone()).await.unwrap();
        let value = "Hello, Fluvio!";
        producer.send(RecordKey::NULL, value).await.unwrap();
        producer.flush().await.unwrap();
        admin.delete::<TopicSpec, String>(name).await.unwrap();
    }
}
```

gives
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AdminApi(Code(TopicNotProvisioned, Some("only 0 out of 1 provisioned")))', examples/admin-bug/src/main.rs:8:60
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**additional notes**
Bug originally came up while testing the benchmark tool, this is a minimal reproducible creation. 
I think it is a race condition as the problem goes away when trace level logging is enabled or adding 
```rust
        admin.delete::<TopicSpec, String>(name).await.unwrap();
        sleep(Duration::from_millis(500)).await;
```

**Comment by sehz** [comment]
Currently, create doesn't wait for the topic to be provisioned.  It just creates metadata for SC. To make it reliable handling, check (have a loop) for topic status before producing.  Note that this doesn't happen in prod scenario since topic is created way before producer/consumer is started.
