### ISSUE TITLE
Bug: smdk build fails when generate was within preexisting Cargo project

### ISSUE THREAD

**Issue by davidbeesley** [infinyon/fluvio#2870]
```
$ cd fluvio
$ smdk generate
$ cd example
$ smdk build
Error: Failed to load cargo project at /home/dave/work/fluvio/example/Cargo.toml
```

**Comment by galibey** [comment]
Need to add an empty workspace section to the template, and it will isolate the generated project from parent-level workspaces.

**Comment by digikata** [comment]
For reference, cargo itself detects and suggests fixes for a similar situation but doesn't directly try to make it work. I think because there isn't a clear single way to integrate it we may want smdk to do something similar.

Inside ../fluvio
> cargo new floop                                                                                                                          
> warning: compiling this new package may not work due to invalid workspace configuration
> current package believes it's in a workspace when it's not:
> current:   .../fluvio/floop/Cargo.toml
> workspace: .../fluvio/Cargo.toml
>
> this may be fixable by adding `floop` to the `workspace.members` array of the manifest located at: .../fluvio/Cargo.toml
> Alternatively, to keep it out of the workspace, add the package to the `workspace.exclude` array, or add an empty  `[workspace]` table to the package's manifest.
>     Created binary (application) `floop` package
