### ISSUE TITLE
Failed to compile: Type-length limit reached

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#291]
I'm starting to notice weird build problems involving large type lengths. Here's an example of an error I'm getting:

```
error: reached the type-length limit while instantiating `async_task::utils::abort_on_pani...::Arc<async_executor::State>]>]>`
  --> /Users/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.1/src/utils.rs:24:1
   |
24 | / pub(crate) fn abort_on_panic<T>(f: impl FnOnce() -> T) -> T {
25 | |     struct Bomb;
26 | |
27 | |     impl Drop for Bomb {
...  |
36 | |     t
37 | | }
   | |_^
   |
   = note: consider adding a `#![type_length_limit="1602453"]` attribute to your crate

error: aborting due to previous error

error: could not compile `fluvio-spu`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

That's appearing in `fluvio-spu`. When I went to apply the new type length limit, I saw we already had a type length limit and I was wondering whether this has been a problem before, and what causes it. Is there anything we can do to our code to avoid this problem from happening? I'm wondering whether we can avoid these problems rather than patching them up, I don't know if a larger type-length limit might get us into bad compile-time or other weird compiler behavior eventually.

**Comment by nicholastmosher** [comment]
I will push a branch where I am seeing this compile error in just a minute

**Comment by sehz** [comment]
I think is due to compiler limitation in current version of Rust.   https://github.com/rust-lang/rust/issues/75992
