### ISSUE TITLE
feature: cluster shutdown command for local

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#2911]
We have a cluster `delete` command.  However, this deletes existing data.   It's nice to have a `cluster shutdown,` which terminates all cluster processes but leaves data intact.    This is useful for swapping or replacing data for testing or other purposes.

**Comment by SINHASantos** [comment]
user shall be given option to 

-kill the process without saving any dupm, if any  
-gracefull shutdown,

**Comment by EstebanBorai** [comment]
@sehz perhaps #2912 closes this?

**Comment by sehz** [comment]
yes
