### ISSUE TITLE
Connector builds require native libs

### ISSUE THREAD

**Issue by smndtrl** [infinyon/fluvio#2921]
**What happened**
Connector cannot build on systems without `libssl-dev` or `pkg-config`. This is due to the the selected features for e.g. `fluvio-future` pulling in `openssl-sys` even though `rustls` seems possible/available. Might consider switching to it for better dev experience?

**Expected behavior**
I can build a rust based connector without needing something besides rust/cargo.

**Comment by sehz** [comment]
`fluvio-future` supports `rustls` thru a feature flag.   You have to use `tls` as a feature flag.  Can you try it? I confirm you can build it

**Comment by smndtrl** [comment]
Situation is as follows.
Implementing the `Sink` trait out of `fluvio_connector_common` requires `fluvio::Offset`.

`connector/sink-test-connector/src/sink.rs`
```
impl Sink<String> for TestSink {
    async fn connect(self, _offset: Option<Offset>) -> Result<LocalBoxSink<String>> {
        let unfold = futures::sink::unfold((), |_: (), record: String| async move {
            println!("Received record: {}", record);
            Ok::<_, anyhow::Error>(())
        });
        Ok(Box::pin(unfold))
    }
}
```

 That requires me to have fluvio in `Cargo.toml` and `fluvio-future` ending up as a transitive having `opnssl-tls`enabled  either way.`

`crates/fluvio/Cargo.toml`
```
# Fluvio dependencies
fluvio-future = { version = "0.4.2", features = [
    "task",
    "openssl_tls",
    "task_unstable",
    "retry",
    "sync"
] }
```

So while I can build `fluvio-future` fine with default features or even `tls`, it won't work while pulling in the main `fluvio` crate.

**Comment by sehz** [comment]
Got it.  Will make  `openssl_tls` an optional feature

**Comment by smndtrl** [comment]
Or just replace `openssl_tls` with  `rustls` in place in to `fluvio/Cargo.toml`... Smaller change that likely just works. Who knows what can happen without on of the "tls" enabled by defauled

**Comment by sehz** [comment]
We had various issues with `rustls`,  in addition to other problems due to relying on assembly code.   The path of least resistance is to make it optional but keep `OpenSSL` as default.    

We use zig as a linker which makes it easier to link `OpenSSL` .

**Comment by sehz** [comment]
new feature flag `rustls`, which you can use after disabling the default feature flag.  Tested and it seem to working
