### ISSUE TITLE
Python SmartModule Support

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#2990]
This is a overall tracking issue. Here's a diagram of what it'll kinda look like:
![Python SmartModule Diagram](https://user-images.githubusercontent.com/1163510/219431817-44350d04-faf2-4e2c-90c0-aade5211328b.svg)

- [ ] `fluvio-smartmodule-py` needs to be a python package that wraps [`fluvio-smartmodule`](https://github.com/infinyon/fluvio/tree/master/crates/fluvio-smartmodule) as a python package and is built for wasm-wasi.
- [ ] Prebuilt [Python wasi](https://github.com/singlestore-labs/python-wasi/) that lives someplace the SPU knows about.
- [ ] Call the Python function via PyO3 through wasmtime.

**Comment by ajhunyady** [comment]
Support to be added via SDF.
