### ISSUE TITLE
Not able to call APIs inside smart module

### ISSUE THREAD

**Issue by sanjay-nit** [infinyon/fluvio#2991]
Added dependencies(reqwest, ureq) in Cargo.toml,
Able to build wasm file successfully, but while passing it to consumer it exit without throwing any error.
Even just importing it causing the problem.

<img width="673" alt="image" src="https://user-images.githubusercontent.com/103114249/219423685-c745c3ee-a0e0-4dcd-944c-347297323270.png">
<img width="838" alt="image" src="https://user-images.githubusercontent.com/103114249/219424364-7c467817-74f4-4fd8-a088-da09fdd611b7.png">

**Comment by simlay** [comment]
Hi there! Glad to see you're trying out smartmodules and learning some rust!

So, `ureq` doesn't compile to `wasm32` architectures and while `reqwest` does, it's actually targeting [client side browser web requests](https://github.com/seanmonstar/reqwest/blob/bdd4db02447c68b6be528c25cde6fa1fc47bf8e1/Cargo.toml#L152-L174). The `web-sys` crate is a shim into browser APIs (and maybe someday wasm-wasi).

Based on you trying to include a web request crate, I'm guessing you're trying to do a web request to some service in your smartmodule. Have you considered using the [fluvio http connector](https://www.fluvio.io/connectors/inbound/http/) pointing data into the topic and then using a smartmodule on that stream?

**Comment by sanjay-nit** [comment]
Hi simlay! Thanks for quick reply.
Our usecase is different, we wanna produce messages to topic using (Rust or Python) client and wanna call some API's for doing validation and all for each message, and wanna consume messages using (Rust or Python client) in some different format. 
I tried using reqwest blocking feature, but getting issue. Any suggestion for our usecase? Thanks!!

**Comment by sehz** [comment]
Hi @sanjay-nit, we don't support making outgoing API in the SmartModule yet.

**Comment by kesavkolla** [comment]
Is it possible to add https://github.com/deislabs/wasi-experimental-http to engine so that the smart modules can use http requests?

**Comment by sehz** [comment]
We will be looking into how we can support external API calls

**Comment by sehz** [comment]
@drc-infinyon let's add this to roadmap

**Comment by drc-infinyon** [comment]
10-4 @sehz

**Comment by ajhunyady** [comment]
@drc-infinyon let's schedule and add to public roadmap.
