### ISSUE TITLE
Support in memory metadata store

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#30]
Build version of SC that works against local in memory metadata store.  With in memory metadata store, we can build local cluster suitable for 
- smoke test
- local development

The in memory store implements traits in:  https://docs.rs/k8-metadata-client/1.0.1/k8_metadata_client/trait.MetadataClient.html.

Implementation should support full fluvio lifecycle:
- Create/Delete local cluster with CLI
- Run smoke test

**Comment by Ryanmtate** [comment]
@sehz I've removed myself on this one; I'll need more information before I jump into this. I may re-assign next week after spending some time with the codebase.
