### ISSUE TITLE
remove `--config` from CDK test

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#3011]
CDK test should use default `sample-config.yaml` if it is not specified.

```
$ cdk test --config <option_config_path>
```

**Comment by simlay** [comment]
What should be in the `sample-param.yaml` and what are the options for `--param`?

**Comment by ajhunyady** [comment]
security ? or https://www.notion.so/infinyon/Connector-Development-Kit-and-Packaging-6a4eedd712ed43ba872f2bc4f53b58ec?pvs=4#141643510c724ea39af2fd3d3306f7bb

**Comment by ajhunyady** [comment]
@sehz `Connector.toml` also has params section. Is the `params` file something different?

**Comment by sehz** [comment]
see: https://github.com/infinyon/mqtt-connector/blob/main/config-example.yaml

**Comment by sehz** [comment]
To reduce confusion, let's go back to `--config`.

**Comment by ajhunyady** [comment]
In that case the default should be `Connector.toml`.

**Comment by sehz** [comment]
That's connector definition not config

**Comment by sehz** [comment]
This depends on #3010
