### ISSUE TITLE
regression: SmartModule transform

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#3035]
Smartmodule transform doesn't work with `0.10.4` release. 

Steps to reproduce:
1.  Build/download 0.10.5(dev) version of Fluvio
2. Connect to 0.10.4 to Fluvio Cluster
3. Try run Jolt transforms with consume. ```fluvio consume helsinki --transform jolt```

In the 0.10.4 client to 0.10.4 cluster, everything works.   However, connecting 0.10.5 to 0.10.4 doesn't work with transforms.

**Comment by galibey** [comment]
The compatibility was broken in [commit](https://github.com/infinyon/fluvio/commit/76b0de652124f1f3a77bfd89dbf0b866789b1bb8) by removing variants from `SmartModuleKind` enum in `crates/fluvio-spu-schema/src/server/smartmodule.rs` file.

**Comment by sehz** [comment]
can you create PR to bring back Kind?  And lets add to backward compatibility test

**Comment by galibey** [comment]
For tests I created follow-up ticket #3037

**Comment by sehz** [comment]
Found out underlying issue with regression.  This is due to fact Enum use encoding based on enum ordering which will be different when adding/deleting occur.
```
for (idx, prop) in props.iter().enumerate() {
        let id = &format_ident!("{}", prop.variant_name);
        let field_idx = if let Some(tag) = &prop.tag {
            match TokenStream::from_str(tag) {
                Ok(literal) => literal,
                _ => LitInt::new(&idx.to_string(), Span::call_site()).to_token_stream(),
            }
```
