### ISSUE TITLE
Prepare SmartModuleKind enum for deletion

### ISSUE THREAD

**Issue by galibey** [infinyon/fluvio#3042]
`SmartModuleKind` enum will be deleted from Fluvio protocol. In this task need to properly prepare it by marking deprecated and setting max API version on types that are used in the protocol.

The type of smartmodule can be detected by its exports if needed.

Once it's done, need to create a task for deletion with the target version current+2.

**Comment by sehz** [comment]
Do still need this since this PR will perform forward and backward compatibility CLI test: https://github.com/infinyon/fluvio/pull/3048
