### ISSUE TITLE
Re-enable crates publish after Release workflow

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#3045]
Related to #2998 

It appears this job no longer runs after release. Should run after release completes successfully

**Comment by sehz** [comment]
Other option is top publishing to crates.io and use explicit GitHub dependency

**Comment by drc-infinyon** [comment]
Decision needed on publishing crates in the future.

**Comment by morenol** [comment]
It seems that also bump-stable job is being skipped
