### ISSUE TITLE
fix enum derive macro for protocol

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#3047]
Currently enum mapping for protocol derive use mapping in the source code.  For example
```
#[derive(Debug, Clone, Eq, PartialEq, Encoder, Decoder)]
pub enum SpuType {
    Managed,
    Custom,
}
```

This will encode Managed as 0 and Custom as 1 based on order appears in the code.  However, this is problematic if `Managed` is deleted.  Then `Custom` will be mapped as 0 since it appears as first.  This was root cause behind: https://github.com/infinyon/fluvio/issues/3035.  

In order to fix, we should not allow enum mapping without explicit mapping.  So this code will not compile.  It need to be change  into:

```
#[derive(Debug, Clone, Eq, PartialEq, Encoder, Decoder)]
pub enum SpuType {
    Managed = 0,
    Custom = 1,
}
```

or using fluvio tag

```
#[derive(Debug, Clone, Eq, PartialEq, Encoder, Decoder)]
pub enum SpuType {
   #[fluvio(tag = 0)]
    Managed,
   #[fluvio(tag = 1)]
    Custom,
}
```

As part of this bug

- [x] #3060
- [x] Migrate untagged enum to tag preserving existing mapping

**Comment by EstebanBorai** [comment]
@sehz should we keep both behaviors (Fluvio tag and discriminant) or should we migrate to a `fluvio(tag)` approach for existing code?

**Comment by EstebanBorai** [comment]
@sehz I think we can close this given that #3061 is now merged
