### ISSUE TITLE
Installer bug: Cannot re-use a name that is still in use

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#307]
I ran into this when trying to install a new development version of fluvio:

```
❯ fluvio cluster install --develop
Error: cannot re-use a name that is still in use
Exited with status code: 1
thread 'main' panicked at 'internal error: entered unreachable code', /Users/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/flv-util-0.5.1/src/cmd.rs:90:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The cause was when the installer ran this command:

```
helm install fluvio ./k8-util/helm/fluvio-app --namespace default --set image.registry=localhost:5000/infinyon --set image.tag=f6503e87c14a156ca4ce4e225595973fd8dcf346 --set cloud=minikube --version 0.6.0
```

I was able to fix it by manually helm-uninstalling the fluvio and fluvio-sys charts and re-installing

```
helm uninstall fluvio
helm uninstall fluvio-sys
fluvio cluster install --sys
fluvio cluster install --develop
```

I do not know the circumstances that led me to this invalid state, but I assume it is fairly likely to happen again. We should make the installer more robust to handling weird helm states.

**Comment by sehz** [comment]
this happens when you are trying to install over previous installation of Fluvio.   Solution is check if there is existing fluvio installation and warn user.
