### ISSUE TITLE
Need documentation for protocol specification

### ISSUE THREAD

**Issue by CoderYellow** [infinyon/fluvio#3074]
Hi team, I want to implement a Java client with netty because the official client use JNI which might cause performance overhead.     So could you please provide something like [Kafka Protocol Doc](https://kafka.apache.org/protocol) which documents the message format. The protocol framework in this project is written in Rust, which is a bit hard for the language programmers. If you want more other language clients from the community, I think this doc is necessary.

**Comment by sehz** [comment]
@CoderYellow we will add to roadmap.  Just aware that some of the protocol might be changing.  This is why we want to abstract out message format so it will be portable.
