### ISSUE TITLE
`fluvio produce` options `--key-separator` and `--file` should not be mutually exclusive

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#3076]
Our docs show an example of using `fluvio produce` with a key separator that saves to file.

<img width="985" alt="image" src="https://user-images.githubusercontent.com/344960/224781099-10f9e0b0-5f87-4fa9-b075-bbb9c03aa2c2.png">

But it no longer works

```
% fluvio produce --key-separator=">" -f records.txt metrics
error: the argument '--key-separator <KEY_SEPARATOR>' cannot be used with '--file <FILE>'
```

This may have been introduced a while ago during the update from Clap v2.

The expectation is the line by line output in `records.txt` should match what gets displayed in stdout

**Comment by morenol** [comment]
I think that `--key` is also not working as expected when using interactive mode:

```
fluvio produce topic-name --key my-key
```

**Comment by ajhunyady** [comment]
Can we add this to `ci` to ensure it won't break in the future?
