### ISSUE TITLE
CDK - Improve friction in user feedback loop

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#3100]
This is a handful of user experience issues. They are somewhat small, and related. But I can break this up into multiple issues if needed.

---

1. [x] Add more information to `cdk test` error message around missing config file

After running `cdk build`, I immediately ran `cdk test`, not thinking that I also need to provide a config file.

The error message isn't descriptive enough and may be misleading to new users.

```
% cdk test
    Finished release [optimized] target(s) in 0.17s
Error: No such file or directory (os error 2)
```

---

2. [x] Add connector name to output for `cdk deploy start`

`cdk deploy start` should print the name of the connector it starts, in addition to log and pid

Example:
```
% cdk deploy start --config config-example.yaml
Log file: /private/tmp/my-connector/my-connector.log
Connector runs with process id: 88589
Started connector `my-my-connector-test-connector`
```

---

3. [x] Accept config file with `cdk deploy shutdown` and `cdk deploy log` as alternative source for connector name

So the interface is similar to `cdk start`, which requires `--config`.

Right now, you must know the name of the connector. And that name comes from the config file, and it is a little bit of friction for new users coming from output of `cdk generate`.

Example: `cdk generate my-connector` generates a config file where the connector is named `my-my-connector-test-connector`.

The importance of the connector name isn't obvious from `--help` text. As a user, it makes sense, if you think about it.

But I don't exactly want to have to think about it. It feels more intuitive and flexible to accept `--config` for more than just starting.

---

4. [x] Connectors should exit a little more loudly by default (with option to exit quietly w/ flag)

`cdk deploy shutdown <connector name>` should give the user feedback about what has happened.

Currently there is no output after running:

```
% cdk deploy shutdown my-my-connector-test-connector
```

Since we have both the process id and connector name, we should echo that out to the user as a confirmation for the actions that has occurred.

**Comment by ajhunyady** [comment]
Good work @tjtelan, let's aim to fix these before we release, as it does impact usability.
