### ISSUE TITLE
Re-enable CLI specific tests once new stable version is released 

### ISSUE THREAD

**Issue by morenol** [infinyon/fluvio#3103]
When adding: https://github.com/infinyon/fluvio/pull/3092

There were added some tests that fail with current stable version. Once we release a new stable version, we should enable them again

**Comment by drc-infinyon** [comment]
There is an existing PR. CI failing needs to be investigated.

**Comment by sehz** [comment]
@morenol is this done or need to be done after release is out?

**Comment by morenol** [comment]
This is done
