### ISSUE TITLE
Add CLI tests to `fluvio consume --format "{{offset}} {{partition}}"`

### ISSUE THREAD

**Issue by morenol** [infinyon/fluvio#3118]
Currently, we have CLI tests for `fluvio consume --format` with `value`, `time`, and `key`. We need to add tests for those other options in order to prevent regressions regarding these fields. Example of {{value}} and {{time}} tests are in https://github.com/infinyon/fluvio/blob/18c80fbd0ec5a9162aae5024d327097fb593fd46/tests/cli/fluvio_smoke_tests/e2e-basic.bats#L173

**Comment by k0i** [comment]
@morenol 
Hello!
Can I take this issue?

Since there was no assignee to this issue, 
I did some implementation beforehand.

https://github.com/infinyon/fluvio/pull/3885

Please kindly close the PR if I did something wrong or this issue is already stale.

Thank you for your time!

**Comment by digikata** [comment]
Thank you for your PR @k0i!
