### ISSUE TITLE
Relative paths in auto-generated `package-meta` in `cdk` and `smdk` tools 

### ISSUE THREAD

**Issue by galibey** [infinyon/fluvio#3119]
Currently, when there is no `package-meta.yaml` file, `cdk` and `smdk` auto-generate it on `publish` step. 
Paths there are relative to the current directory, which is no longer valid behaviour. Need to reflect there the way how it works now: paths are relative to the `package-meta.yaml` file.

**Comment by sehz** [comment]
Let's fix this.  This is regression
