### ISSUE TITLE
Correct off-by-one error in partition offsets and add distinction for zero events

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#312]
Right now there is no way for a `FetchOffsetPartitionResponse` to indicate that there are zero events in a partition. When resolving a relative offset in a partition with zero events, the result should be a value that indicates that there are zero events in the partition. Instead, what happens right now is that the resolution happens successfully, but incorrectly returns the absolute offset of `0`. I want to use the rest of this issue to describe what I believe the desired behavior should be.

## Case: Resolving a relative offset into an absolute offset

Suppose I have a topic "test" with a single partition and no events in the partition. If I create a relative offset `Offset::end()` and try to resolve it to an absolute offset, I should receive a value that indicates "there are no events". This could be expressed by returning an `Option` or a `Result` with a specific error type indicating this.

### Current behavior:

Right now, the `fetch_offsets` function returns a `FetchOffsetPartitionResponse` which always contains a `start_offset` and a `last_stable_offset` which are both `i64` values. This expresses that there is no way that a partition may have zero elements in it.

### Reproducing

When partition `("test", 0)` is empty, the following code prints "Absolute offset: 0". This incorrectly tells the user that there is a single event at absolute offset 0.

```rust
let fluvio = Fluvio::connect().await.unwrap();
let replica = ReplicaKey::new("test", 0);
let mut serial_socket = fluvio.spu_pool.create_serial_socket(&replica).await.unwrap();
let last_offset = Offset::end();
let last_offset_absolute = last_offset.to_absolute(&mut serial_socket, "test", 0).await.unwrap();
println!("Absolute offset: {}", last_offset_absolute);
```

**Comment by sehz** [comment]
current behavior is that start_offset = 0 indicates there are no records in the partition

**Comment by nicholastmosher** [comment]
I suppose what I mean is that when the Offset API landed, we gave a new definition for what the behavior _should_ be, and now we need to update the implementation to match the new definition.

**Comment by ajhunyady** [comment]
@sehz @nicholastmosher, how is the progress on this issue? It looks like it's blocking CDC which is needed to release website.

**Comment by nicholastmosher** [comment]
I was able to make a workaround for CDC where I cache the producer offset on local disk. This is still something I want to address, but it's not critical to our OSS release.
