### ISSUE TITLE
[Bug]: CLI consumer & producers fail silently when they are disconnect from the cluster

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/fluvio#3124]
Star 2 CLI sessions, one consumer and one producer to the cloud cluster.
Some some records then leave them idle.

In a while... (I don't know how long)... they get disconnected, but there is no indication that the connection is down.

Consumer example:
```
[6:52](https://infinyon.slack.com/archives/CN1D204C9/p1680789158903939)
 2023-04-05T22:14:47.009Z {"forks":134,"stars":1725}
⠦                                                             
⠖
```

Producer Example:
```
> test
 Ok!
> test
hello world
test
test
```

I would expect to get notified if the client fails to reconnect. 
Furthermore, the CLI should exit interactive mode on error.

**Comment by galibey** [comment]
> My behavior is different, I don't get an error at the CLI

Are you sure the connectivity was lost for more than 5 minutes?

**Comment by ajhunyady** [comment]
I left the computer on overnight, but since there was no message when the connection went down I don't know. All I know is that when I tried to use the producer, it didn't work. After restarting the consumer, I noticed that it didn't receive messages.

I cannot answer this question if I don't get a message when the connection is dropped.

**Comment by ajhunyady** [comment]
I can disconnect the wifi for 5 minutes to see what happens.

**Comment by galibey** [comment]
When you left the computer overnight, was the producer sending any data? If not, it is not relevant. The producer just didn't do anything, that's why no messages or errors. When you send a message, it initiates a new "send operation" and 5 minutes start counting from that time.

**Comment by ajhunyady** [comment]
no, the producer was idle

**Comment by ajhunyady** [comment]
Here is what I got from the Wifi off test:

<img width="643" alt="image" src="https://user-images.githubusercontent.com/26554085/232121383-1453636f-b5c6-40ea-ba8c-7ce1dc1030e9.png">

producer eventually errored out, consumer didn't.

**Comment by galibey** [comment]
> producer eventually errored out, consumer didn't.

That is expected, when connection is up and something will be produced, consumer will recover and consume

**Comment by ajhunyady** [comment]
The consumer didn't recover. I still didn't get `wifi back on`, and it's been almost 10 minutes since I resumed wifi

**Comment by galibey** [comment]
Ok, it is an issue, I will try to reproduce it again.

**Comment by ajhunyady** [comment]
> When you left the computer overnight, was the producer sending any data? If not, it is not relevant. The producer just didn't do anything, that's why no messages or errors. When you send a message, it initiates a new "send operation" and 5 minutes start counting from that time.

We should have a ping mechanism to avoid this situation. But this is not urgent.

**Comment by ajhunyady** [comment]
The `producer` still has an issue. I left the connection on for about 30 minutes, and now I typed `test`... it just sits there:
<img width="402" alt="image" src="https://user-images.githubusercontent.com/26554085/232130350-c7327433-d991-4a92-a37a-47d5e026b74c.png">

I did not receive an OK for a while, then in failed, about 3-4 minutes later. But why did it fail? The connection was OK, I do not have any network issues.

**Comment by ajhunyady** [comment]
producer seems ok, 
[producer.txt](https://github.com/infinyon/fluvio/files/11268952/producer.txt)

**Comment by ajhunyady** [comment]
Consumer didn't react to network down. When the network came back up, the log shows `terminating`, but nothing on the screen. The surprising part is that it waited until I reconnected to check for connection status.

I tried to produce to it, but the consumer is dead but, yet it is still showing the "rotating widget".
[consumer.txt](https://github.com/infinyon/fluvio/files/11268987/consumer.txt)

**Comment by galibey** [comment]
@ajhunyady Thanks. I got useful information from logs.

**Comment by ajhunyady** [comment]
> @ajhunyady Thanks. I got useful information from logs.

Thank you for fixing this.
