### ISSUE TITLE
feature:  string interpolation for connector config

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#3127]
In the connector config, we may need to  inject parameters as constant like:
```
http: 
     intervals: 10s
```

However,  these constants may change depending on context.  We need to give the ability for these parameters to be substituted until like this:

```
http:
     intervals: ${{ env.interval }}
```

It could also be used in secrets like:
```
http:
    headers:
          - "Authorization: ${{ secrets.token}}'
```

This can be anywhere the string values are defined.

ref: https://github.com/infinyon/http-connector/issues/25

**Comment by morenol** [comment]
So, from the examle I see that we should resolve `secrets.token`  using the current `secrets` feature. But not so sure about `env.interval` I think that we don't have a way to inject `envs` in connectors either in cloud or locally

**Comment by sehz** [comment]
done
