### ISSUE TITLE
Pre-install check: Bring tunnel up if context is minikube

### ISSUE THREAD

**Issue by vijaylaxmid** [infinyon/fluvio#314]
If minikibe tunnel is not up and if k8 is minikube, set the tunnel up

**Comment by sehz** [comment]
Make sure to add test step in CI for both Mac & Linux

**Comment by vijaylaxmid** [comment]
To check if `minikube` is up during preinstall we will need to create a dummy service and wait for IP to be assigned. We do a similar check in pre-flight checks that we have
https://github.com/infinyon/fluvio/blob/master/src/cli/src/cluster/check.rs#L328
Do we want to have similar logic in cluster pre-install? This might slow down the install process a little.

**Comment by sehz** [comment]
Or installer can call pre-check?

**Comment by vijaylaxmid** [comment]
Sure we can do that. Just wanted to confirm.
