### ISSUE TITLE
[Bug]: CD_Dev using outdated install.sh input parameter

### ISSUE THREAD

**Issue by digikata** [infinyon/fluvio#3145]
#3117 changed VERSION to FLV_VERSION and CD_Dev checks dev version against stable version as a result - always failing.

**Comment by digikata** [comment]
Analyze .github actions to find uses of VERSION as an input to install.sh

**Comment by morenol** [comment]
Probably we also need to update https://github.com/infinyon/fluvio/blob/66e43d7e8f1c9a3242f156b02973b046bc27952d/actions/action-install-fluvio-cluster.sh#L25

**Comment by digikata** [comment]
This also means we need to really carefully inspect all uses of VERSION too, the core change to FLV_VERSION is a good idea, but VERSION is overloaded.

**Comment by digikata** [comment]
https://github.com/infinyon/fluvio/blob/66e43d7e8f1c9a3242f156b02973b046bc27952d/Makefile#L1 too.

**Comment by digikata** [comment]
VERSION->FLV_VERSION is good to sepearate out, reintroduce the commit after release, while also working through all the parameter name changes.
