### ISSUE TITLE
[Feature]: Add a Redis Connector (Pub-Sub, Stream)

### ISSUE THREAD

**Issue by gkorland** [infinyon/fluvio#3153]
It seems like `fluvio` currently only supports Kafka, HTTP & MQTT.  
Is there a plan to extend the support for Redis?  

Redis support two relevant modes:
1. PubSub - https://redis.io/docs/manual/pubsub/
2. Streams - https://redis.io/docs/data-types/streams/

Also adding support for Redis as Outbound connector can be pretty interesting.

**Comment by ajhunyady** [comment]
Hi @gkorland it would be great to collaborate with the Redis team and build a connector.
