### ISSUE TITLE
[Bug]: Move `x records outputed` from `smdk test` to --verbose

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/fluvio#3169]
Since most of the use cases we are currently facing are `json` it is be useful to pipe the result of `smdk test` to `jq`.

But the `x records outputed` like breaks this functionality.

Add a new flag `--verbose`, to `smdk test` and move `x records outputed` under this flag:

```
smdk test ... --verbose
x records outputed
...
```

**Comment by TanNgocDo** [comment]
so, without "verbose" the output should be :
`
smdk test ...
record_1
record_2
.....

`
with verbose : 
`
smdk test ... --verbose
x records outputed
record_1
record_2
.....
`
right? @ajhunyady  ?

**Comment by ajhunyady** [comment]
Hi @TanNgocDo, yes, the example provided looks right.
Thanks for looking into this.

**Comment by TanNgocDo** [comment]
Thanks @ajhunyady , I have just made a simple PR

**Comment by ajhunyady** [comment]
Thank you for the PR @TanNgocDo! The engineering team will review soon.

**Comment by sehz** [comment]
done
