### ISSUE TITLE
List Fluvio Plugins using `fluvio install` command

### ISSUE THREAD

**Issue by EstebanBorai** [infinyon/fluvio#3171]
As a user it would be awesome to have a way to list available fluvio plugins when
running `fluvio install` straight. A list containing plugin name, description and link to
documentation would help understanding how fluvio CLI could be extended.

## Acceptance Criteria

As a Fluvio user I would run `fluvio install` straight and I would see a list of plugins
available for install.

```bash
fluvio install

Usage `fluvio install <NAME>` where name could be any of the following values.

NAME    DESCRIPTION                             DOCUMENTATION
cdk     Connector Development Kit               https://www.fluvio.io/connectors/cdk/overview/
...
```

**Comment by ajhunyady** [comment]
@EstebanBorai we need a `PRD` for this as there are several other concerns. I'd like to list packages available for installation, the ones I installed, are there new version available, etc.
