### ISSUE TITLE
[Bug]: fluvio cluster start doesn't connect to SC for minikube and kind on mac

### ISSUE THREAD

**Issue by thinkrapido** [infinyon/fluvio#3183]
**What happened**
> fluvio start cluster
doesn't connect connect to SC
timeout after 120 sec 
Happens only on Mac

```
➜  fluvio fluvio cluster start
Current channel: stable
📝 Running pre-flight checks
    ✅ Kubectl active cluster minikube at: https://127.0.0.1:51511 found
    ✅ Supported helm version 3.11.3+g66a969e is installed
    ✅ Supported Kubernetes server 1.26.3 found
    ✅ Fixed: Fluvio Sys chart 0.10.7 is installed
    ✅ Previous fluvio installation not found
🎉 All checks passed!
✅ Installed Fluvio app chart: 0.10.7
🖥️  Trying to connect to SC: localhost:30003 119 seconds elapsed \                                                                                                                                                                                             2023-04-21T13:36:27.449145Z ERROR fluvio_cluster::start::common: fail to connect to sc at: localhost:30003
Timed out when waiting for SC service
```

**Expected behavior**
local fluvio cluster should work

**Describe the setup**
Neither Kind nor MiniKube is working - same bug
kind version 0.18.0

**How to reproduce it (as minimally and precisely as possible)**

> fluvio start cluster

**Log output**
It helps to have logs from Fluvio's SC and SPU processes.
Depending on your setup, here's how you can get the logs:

- For a local Fluvio installation on Mac:
- `ls -la /usr/local/var/log/fluvio` no such file or directory

**Environment (please complete the following information):**
 - OS: [e.g. Linux, Mac]
 
![screenshot](https://user-images.githubusercontent.com/1568087/233656034-d3e08343-3702-46e3-90c2-3910aa0a753f.png)

 - Fluvio Version [e.g. 22]
- kind version 0.18.0
- Kubernetes version: use `kubectl version`
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sehz** [comment]
Our supported K8 cluster is rancher desktop: https://www.fluvio.io/docs/get-started/mac/.  Can you try with that?

**Comment by TanNgocDo** [comment]
hi @sehz , 
I'm using Rancher and even using with proxy is localhost but I can not start the local cluster because of some pre-check :
```
fluvio cluster start --proxy-addr localhost
Current channel: stable
📝 Running pre-flight checks
    ✅ Kubectl active cluster rancher-desktop at: https://127.0.0.1:6443 found
    ✅ Supported helm version 3.11.3+g3232493 is installed
    ✅ Supported Kubernetes server 1.27.1+k3s1 found
    ✅ Fluvio system charts are installed
    ❌ Check Fluvio installation failed Fluvio chart is already installed
```
Not sure if it's a existing problem ?

Even with fluvio cloud, I login sucessfully but can not create topic due to lacking of config:

```
luvio cloud login --use-oauth2
A web browser has been opened at https://infinyon-cloud.us.auth0.com/activate?user_code=CFGF-MKQH.
Please proceed with authentication.
Successfully authenticated with Auth0
Cluster does not exist. Please create a cluster first with `fluvio cloud cluster create` or through Infinyon Cloud UI.
tando@Tans-MacBook-Pro fluvio % fluvio topic create greetings
Config error: config file "/Users/tando/.fluvio/config"
```

Thanks

**Comment by morenol** [comment]
For cloud, please follow this:

```
Please create a cluster first with `fluvio cloud cluster create` or through Infinyon Cloud UI.
```

For local installation, maybe there was a wrong installation first? Could you try `fluvio cluster delete` and then try again `fluvio cluster start`?

**Comment by sehz** [comment]
We need better recovery for check: ` Check Fluvio installation failed Fluvio chart is already installed`.    This says there is old Fluvio cluster components still present.  Fix it so run `fluvio cluster delete`

**Comment by TanNgocDo** [comment]
thanks @sehz , @morenol . It works
