### ISSUE TITLE
Improve Fluvio admin interfaces

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#319]
Continuing the work of #277, in this issue I'd like to brainstorm ideas on how to make the `FluvioAdmin` API simpler and easier to use. Pieces of functionality should be driven by use cases, and we should think about how the interface could be made similar among several clients such as Rust and Node.

- ## Admin Functionality
  - [ ] Create a Topic
    - User Intent: I want to be able to create a topic to send application events over
    - Applicable clients: CLI, Rust, Node

  - [ ] Discover Topics
    - User Intent: I would like to be able to list and inspect the existing Topics in my cluster
    - Applicable clients: CLI, Rust, Node

  - [ ] Configure a Topic
    - User Intent: I would like to configure my Topic with options such as partitions and replicas
    - Applicable clients: CLI, Rust, Node
    - Configuration options:
      - [ ] Create and View Partitions
        - User Intent: I have a Topic, and I would like it to be split into N partitions for parallel streaming
      - [ ] Create and View Replicas
        - User Intent: I have a Topic, and I would like to specify how many copies of the Topic's data are maintained

**Comment by tjtelan** [comment]
The topic configure and create functionality should be written with a Builder pattern
