### ISSUE TITLE
Discord invite isn't working

### ISSUE THREAD

**Issue by athre0z** [infinyon/fluvio#3207]
Clicking the Discord invite link in the documentation currently gives me "unable to accept invite". Did it perhaps expire?

## Screenshot

![Screenshot_20230429_003813](https://user-images.githubusercontent.com/6553158/235265100-735ee72c-7beb-4eee-b708-2bb902fc99b0.png)

**Comment by ajhunyady** [comment]
@athre0z  thanks for reporting. Perhaps there was an issue with the `Discord` server, can you please try this link? https://discordapp.com/invite/bBG2dTz

**Comment by athre0z** [comment]
Thanks for the quick response! 

Hmm. That's the same link that is referenced in the documentation, so I should have the same problem with that one. Funnily enough, this time things worked. Looks like it was some kind of spurious failure on Discord's side -- please consider this resolved and apologize the noise. :)
