### ISSUE TITLE
Remove conditionally skipped test case after v0.10.10 release

### ISSUE THREAD

**Issue by EstebanBorai** [infinyon/fluvio#3223]
Remove conditionally skipped test for stable version on compression
with Zstd Algorithm.

https://github.com/infinyon/fluvio/pull/3185/files/20f88adb48adfaed696762245953f60749768ebb#diff-d2006ab16c455c5fc3dc55ea572b36be5fd8ad09d2d8e808c0f427914ea9af28R226-R228

Refer: #3185

**Comment by EstebanBorai** [comment]
@drc-infinyon this is post-release

**Comment by morenol** [comment]
We moved this to 0.10.11 release
