### ISSUE TITLE
CDK | Build artifacts before publishing and deploy

### ISSUE THREAD

**Issue by EstebanBorai** [infinyon/fluvio#3250]
Regenerate the `.hub` directory and fill up with artifacts from the latest
changes before running `publish` and/or `deploy`

**Comment by sehz** [comment]
.hub directory should be removed after publishing

**Comment by EstebanBorai** [comment]
> .hub directory should be removed after publishing

Sure thing! I just drafted a PR for the first bit, it already includes changes for the `test`, `publish` and `deploy` subcommands.

I will be creating another issue to do cleanup after publishing so PR is not to complex and is atomic!

**Comment by EstebanBorai** [comment]
> .hub directory should be removed after publishing

Here is tracking! https://github.com/infinyon/fluvio/issues/3253

**Comment by EstebanBorai** [comment]
Completed on https://github.com/infinyon/fluvio/pull/3252
