### ISSUE TITLE
CDK | Cleanup after Publishing

### ISSUE THREAD

**Issue by EstebanBorai** [infinyon/fluvio#3253]
After `cdk publish` is done, we must remove the `.hub` directory.

Its important we do this only when the `--pack` argument is **not** present.

**Comment by EstebanBorai** [comment]
@sehz perhaps we could decouple `--pack` into its own command?

Just thinking while writing requirements that perhaps we would like to have these commands separated to keep consistency on side effects?

I think this would be more predictable:

```bash
# performs publishing to hub perhaps on dry run if on
cdk publish

# just produced the `.hub` directory with its contents
cdk pack
```

What do you think?

**Comment by sehz** [comment]
`pack` seems to be only relevant in publishing context and very special case so don't think warrant it's own command.  It should be just flag in the `publish` command

**Comment by EstebanBorai** [comment]
Resolved on https://github.com/infinyon/fluvio/pull/3259
