### ISSUE TITLE
Centralize SmartModule Examples

### ISSUE THREAD

**Issue by EstebanBorai** [infinyon/fluvio#3262]
Migrate SmartModule examples in the now archived repository `fluvio-connectors` to `fluvio` so they are easier to find.

These examples include:

- Jolt
- JSON SQL

**Comment by sehz** [comment]
Please update description with rational

**Comment by EstebanBorai** [comment]
> Please update description with rational

Hi @sehz,

I just updated the description to have better context!

But based on reviewsI think that we actually want to move these to `fluvio-jolt` and `sql-connector` respectively right?

**Comment by EstebanBorai** [comment]
@drc-infinyon closing this due to comments on #3263
