### ISSUE TITLE
`smdk` support for input from stdin

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#3318]
I think it's inconvenient to use `smdk test` if I want to test with dynamic json output. The only options are from  that input is either provided with `--input` or `--file`.

I would like to be able to pipe in input from curl

`curl https://myservice/api | smdk test ...` 

I've seen patterns that use stdin if the file is `-` - e.g. `--file -`

Or  a more verbose `--stdin` flag. I don't have a strong preference for either, but it should be explicit

**Comment by matheus-consoli** [comment]
hi, I would like to take a look at this :slightly_smiling_face:
