### ISSUE TITLE
Support proper WASM backtrace for troubleshooting smartmodules

### ISSUE THREAD

**Issue by drc-infinyon** [infinyon/fluvio#3327]
https://blog.logrocket.com/how-to-debug-wasm-and-achieve-a-reliable-stack-trace.

In addition, WASM provides way to stack trace: https://docs.rs/wasmtime/latest/wasmtime/struct.WasmBacktrace.html

**Comment by digikata** [comment]
Related to #3367 and #2190

**Comment by matheus-consoli** [comment]
hi, I would like to take a look into this :)

**Comment by EstebanBorai** [comment]
> hi, I would like to take a look into this :)

Great! Go ahead! Ask any questions!

**Comment by matheus-consoli** [comment]
I took some time to investigate this today, and to my surprise, SmartModules already emits backtraces. It just happens that the default configuration strips the symbols. This config was introduced in #2774 to reduce the SmartModule size.

Which path do you wanna me to take with this? from what I can see in the thread, the options are:
1. have a separate build profile for testing
2. add flags to `smdk build` to control the symbols
3. ask about this on `smdk generate`
4. just revert the default parameter and don't strip the symbols

**Comment by EstebanBorai** [comment]
> I took some time to investigate this today, and to my surprise, SmartModules already emits backtraces. It just happens that the default configuration strips the symbols. This config was introduced in #2774 to reduce the SmartModule size.
> 
> 
> 
> Which path do you wanna me to take with this? from what I can see in the thread, the options are:
> 
> 1. have a separate build profile for testing
> 
> 2. add flags to `smdk build` to control the symbols
> 
> 3. ask about this on `smdk generate`
> 
> 4. just revert the default parameter and don't strip the symbols

In my opinion the second option is the better.

I would keep current behavior for `smdk build` and if we wanted to keep symbols in the binary, we could use `smdk build --debug`.

WDYT?

**Comment by sehz** [comment]
This can be controlled thru cargo profile: https://doc.rust-lang.org/cargo/reference/profiles.html.   `smdk`  support building using `--release <profile>`

**Comment by matheus-consoli** [comment]
Oh, great! So, I think there's nothing else to do then, right?

**Comment by sehz** [comment]
Not sure what's the original scope of the issue. @drc-infinyon can clarify or close the issue

**Comment by drc-infinyon** [comment]
It seems like this one is already addressed to the extent that we need now. Closing this issue.
