### ISSUE TITLE
Error rework to make errors easier to understand

### ISSUE THREAD

**Issue by ozgrakkurt** [infinyon/fluvio#3353]
Currently most error types are like this: https://github.com/infinyon/fluvio/blob/693a2923a36fe4cd0222d70ef34fcc9a40243009/crates/fluvio-auth/src/error.rs#L8

which hides the underlying error and would just print `io error` in the console.

There is a similar error where `fluvio` prints `socket` into the console in place of an error.

Maybe we can do an error rework to fix these issues?

**Comment by digikata** [comment]
Yes, fixing these a little at a time should improve our errors. Some of the socket errors were already fixed in this release https://github.com/infinyon/fluvio/pull/3324/files
