### ISSUE TITLE
Implement `--no-build` flag on `smdk`

### ISSUE THREAD

**Issue by ozgrakkurt** [infinyon/fluvio#3371]
Currently we have this api on cdk but not on smdk, probably should be implemented?

@sehz @digikata @galibey

**Comment by ajhunyady** [comment]
@ozgrakkurt is this related to `dry-run`? 
We should close if no longer relevant.

**Comment by ozgrakkurt** [comment]
> @ozgrakkurt is this related to `dry-run`? We should close if no longer relevant.

No it is a separate issue actually,

Currently `smdk` never does the compilation of actual code but just packs/pushes it. But `cdk` does compilation of code by default and doesn't if passed `--no-build`. We porbably want to make them have same API so I opened this issue
