### ISSUE TITLE
Create `--dry-run` flag in `smdk` and `cdk` `publish` for testing

### ISSUE THREAD

**Issue by ozgrakkurt** [infinyon/fluvio#3376]
Currently there doesn't seem to be a way to test if `smdk/cdk publish --push` without actually publishing. This is a suggestion to add a `--dry-run` flag which executes everything up to the part where it publishes the package to hub.

**Comment by digikata** [comment]
I could be missing something, but I thought of `--push` as only taking an ipkg file and pushing it to hub.  A smdk/cdk publish should probably have a `--dry-run` flag where does everything but the push.

**Comment by sehz** [comment]
Yes, by default push should send upload to hub unless `--dry-run` is passed.  This is common pattern for similar tools

**Comment by ozgrakkurt** [comment]
It only does `--push`. But that is still pretty involved, and can have errors up to the point there it actually makes http requests.

For example in https://github.com/infinyon/fluvio/pull/3370, it had an issue where it assumed that it was in the project folder when this shouldn't really be the case.

To test that this, we could have a `--dry-run` flag to verify it works up to the point here it makes the http request so it is easier to test with something like `sql-connector` which I don't really want to publish, but just want to test that I can publish it from any folder with just the ipkg.

Without the `--dry-run` option the way to test it might be creating a dummy module and publishing it to dev but it is extra work. Also in a `CI` test we might want to run it with `--dry-run`.
