### ISSUE TITLE
Consider on `smdk build` or smartmodule build in general inject the current API_VERSION supported

### ISSUE THREAD

**Issue by morenol** [infinyon/fluvio#3414]
We should consider to add an API version in the WASM payload of the smartmodule at compile time so we can detect the max supported version in order to avoid issues in the future in changes of the encoding/decoding of the input/output passed to the SmartEngine. 

We can assume the current stable version if the wasm payload does not have that information

**Comment by digikata** [comment]
Check to see if this is done
