### ISSUE TITLE
feature: profile wizard

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#3418]
Currently we generate profile during cluster creation or  download from cloud.  However, it would be nice to easily create or modify existing profile without coupling to cluster administration.  For example when trying to connect to existing cluster.

Here is how it may work:
```
$ fluvio profile list

 PROFILE          CLUSTER          ADDRESS                                                TLS      
  *  local            local            localhost:9003  
```

New command `add` would look like this
```
$ fluvio profile add <new_profile_name>  <endpoint>
```

For example:
```
$ fluvio profile add ec2 ec2-11-11-11-11.us-west-2.compute.amazonaws.com:9003
New profile ec2 is being added
```

```
$ fluvio profile list
 PROFILE          CLUSTER          ADDRESS                                                         TLS      
  *  local            local                 localhost:9003  
      ec2.            ec2                   ec2-11-11-11-11.us-west-2.compute.amazonaws.com:9003
```

The following are optional argument.  If not specified then, default would be used:
```
---spu     <public ip address of SPU>
---cluster-name <cluster name>
---tls-policy  <tls parameters>
```

This command derives cluster name from profile name.

**Comment by digikata** [comment]
Reopening because optional flags could still be added, but the basic case is handled
