### ISSUE TITLE
WatchAPI error: return a better user error when versions are not compatible

### ISSUE THREAD

**Issue by digikata** [infinyon/fluvio#3441]
Currently WatchAPI error is returned the the fluvio client and cluster do not support a common version, user error should probably ask to upgrade either the client or the cluster as well as giving relevant version info for both

The error should be something like:

```
Error: Fluvio Client {client_version} and Cluster {cluster_version} versions are not compatible
Please upgrade client to {cluster_version}
```

**Comment by ajhunyady** [comment]
Marking high priority as it led to customer issue.

**Comment by fraidev** [comment]
https://github.com/infinyon/fluvio/pull/4149 fix it
