### ISSUE TITLE
Validate `VERSION` will be parsable by `semver` at runtime

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#3479]
Related: https://github.com/infinyon/fluvio/issues/2949

Due to how we include the platform version number in the CLI, if there is any leading/trailing whitespace, parsing for semver may fail. We handle this case inconsistently.

https://github.com/infinyon/fluvio/blob/d2b7ccf1cf2237c4999e2f97520ac37f7dea395a/crates/fluvio-cli/src/lib.rs#L16

---

`fluvio version` can handle whitespace
https://github.com/infinyon/fluvio/blob/d2b7ccf1cf2237c4999e2f97520ac37f7dea395a/crates/fluvio-cli/src/version.rs#L23

But `fluvio install/update` (and many other places) do not include `.trim()`
https://github.com/infinyon/fluvio/blob/d2b7ccf1cf2237c4999e2f97520ac37f7dea395a/crates/fluvio-cli/src/install/update.rs#L282

There is no known workaround after compilation, but `VERSION` requirements should also be less strict. We should support basic whitespace trimming and address the root issue.

And rather than handle case-by-case, we should validate that `VERSION` is valid during buildtime. But the CLI build should fail in cases when `VERSION` can't be parsed due to actual semver validity.

**Comment by jamrok** [comment]
Hey @tjtelan, I'd like to work on this. Can you assign it to me?

**Comment by tjtelan** [comment]
Hi @jamrok, thanks for the interest! Sure, I can assign to you
