### ISSUE TITLE
fluvio-channel config should resolve `~` to `$HOME`

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#3481]
Users can create their own channels with `fluvio version create`. However, more advanced users you can also do it directly from the config file.

What isn't obvious is that paths for `binary_location` seem to require absolute paths. If you use `~` to define a path that is local to your homedir, it should resolve, but it just fails silently (which is a separate issue).

**Comment by demfabris** [comment]
@tjtelan Can I take this one?

After a quick investigation I assume the issue could be fixed in `.../fluvio-channel-cli/src/cli/create.rs`?

**Comment by tjtelan** [comment]
> @tjtelan Can I take this one?
> 
> After a quick investigation I assume the issue could be fixed in `.../fluvio-channel-cli/src/cli/create.rs`?

Yes, you can take this. I think that `create.rs` is where the fix will be

**Comment by demfabris** [comment]
@tjtelan Here's what I got so far:

Say the user has this config file:

```my_config
current_channel = "stable"

[channel."0.10.5"]
binary_location = "~/.fluvio/bin/fluvio-0.10.5"
extensions = "~/.fluvio/extensions-0.10.5"
image_tag_strategy = "Version"

...
```
Running:
`$ fluvio version create --config my_config 0.10.5` will fetch this version and overwrite the file with absolute paths.

I might've misunderstood what you meant by "creating channels directly from the config file" tho.

Thoughts to reproduce?
