### ISSUE TITLE
`fluvio cluster delete` should prompt with cluster and endpoint name confirmation

### ISSUE THREAD

**Issue by digikata** [infinyon/fluvio#3493]
Currently the user can delete an unintended cluster with `fluvio cluster delete`  because the cluster the profile is pointing to is not reported. 

Change:
Add an interaction to print the current cluster and endpoint and ask for confirmation. The user is asked to type the name of the cluster.

```
$ fluvio cluster delete
WARNING: You are about to delete CLUSTER/ENDPOINT. This operation is irreversible 
and the data stored in your cluster will be permanently lost.

Please type the cluster name to confirm: CLUSTER <enter> (to confirm) / or CTRL-C (to cancel)
```

```
Your cluster CLUSTER has been deleted
```

**Note:**
* add `-f` \ `--force` option to bypass the prompt for CI and automation tool

reference:
`fluvio profile list` returns a table of PROFILE, CLUSTER, ENDPOINT logic to retrieve current cluster/endpoint can be found with that command logic

**Comment by demfabris** [comment]
Hey @digikata I was dealing with #3481 but I didn't got follow up yet.
Can I take this one meanwhile?

**Comment by ajhunyady** [comment]
@demfabris, feel free to take this item. Please note the update in the issue definition.

**Comment by sehz** [comment]
should add a `--force` option to bypass the prompt for CI and automation tool

**Comment by PanGan21** [comment]
Hi! I tried to contribute on this issue. Please let me know if there is any feedback :)

**Comment by digikata** [comment]
Solved w/ https://github.com/infinyon/fluvio/pull/4034 from @PanGan21
