### ISSUE TITLE
`fluvio uninstall` command

### ISSUE THREAD

**Issue by EstebanBorai** [infinyon/fluvio#3495]
Provide a command to easily uninstall Fluvio from CLI, cleaning up:

1. Kubernetes Objects belonging to Fluvio namespace
2. Fluvio Helm Charts

**Comment by sehz** [comment]
whats diff this command from `fluvio cluster delete` ?

**Comment by sehz** [comment]
it is not possible to delete fluvio itself since `fluvio` binary itself is in the path.   This is only possible if fluvio is installed using third party pkg manager.

**Comment by ajhunyady** [comment]
Just delete the directory ` ~/.fluvio`.

BTW, we are planning to implement `fluvio version manager` which will take care of this. So let's focus our efforts on fvm instead.

**Comment by EstebanBorai** [comment]
Gotcha! Thanks for clarifications! Im cleaning up!
