### ISSUE TITLE
Narrow down de-facto compression algorithms

### ISSUE THREAD

**Issue by EstebanBorai** [infinyon/fluvio#3515]
As of today `fluvio-compression` supports the following compression algorithms by default:

- `flate2`
- `lz4`
- `snappy`
- `zstd`

This results in complexity when building for multiple targets, and also increases maintenance
efforts. In order to reduce the effort and at the same time provide a wide support of compression algorithms, certain algorithms wont be included by default.

Included libraries will be: `flate2`, `lz4` and `snappy`. In the other hand, `zstd` and future
libraries will be supported behind Feature Flags.

**Comment by sehz** [comment]
Can we have a table of the pros/cons of each compression?
