### ISSUE TITLE
Add option to print all `fluvio consume` output longer than terminal width

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#3534]
Currently when I'm debugging, and I have a large json object I want to review, I have to output to a file. No other way to see further in the object.

The output is truncated, and that's not the preferred behavior. The output should be displayed fully by default:

`fluvio consume <topic>` - shows raw output
`fluvio consume <topic> --truncate` - clips the result to 1 line (current default behavior).

The `truncate` keyword is mutually exclusive with `output`.
In addition, I should be able to to use `--output json`

`fluvio consume <topic> --output json` - shows json `beautified`.

@tjtelan's earlier commend (edited):
- Truncate behavior: output gets wrapped onto multiple lines by the terminal. Printing subsequent records will still start on its own line.

**Comment by ajhunyady** [comment]
Related to https://github.com/infinyon/fluvio/issues/3536

**Comment by ajhunyady** [comment]
I suggest the opposite, as it's the most use feature.

Show everything by default.
Add `--truncate` to truncate.

**Comment by digikata** [comment]
I like the idea of leaving the output fairly untouched by default, with the option to add built-in truncation or other formatting.  I think in unix environments like linux/macos, most cli users expect to apply their own pipelined filters anyway. Still built-in formatting options are useful to keep for users that happen to drop into a minimal environment (like containers or embedded envs etc)..

**Comment by sehz** [comment]
Current behavior tries to do too much.  I agree with the sentiment that, by default, we should not touch the output.  We should fix this for 0.10.5

**Comment by ajhunyady** [comment]
One example for json is pipe to `jq` to get proper formatting.

**Comment by ajhunyady** [comment]
Related to https://github.com/infinyon/fluvio/issues/3536
