### ISSUE TITLE
[Bug]: Consumer cuts off large json fields in the terminal.

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/fluvio#3536]
I used github webhooks to write events to a cloud webhook, then consumed from the terminal.
The output is cut off. 

```
% fluvio consume wh -T=1 --output=raw
Consuming records from 'wh' starting 1 from the end of log
{"headers":{"x-github-hook-id":"433430630","x-forwarded-proto":"https","cf-ray":"80645615a5c20830-IAD","host":"infinyon.cloud","cf-worker":"infinyon.cloud","content-type":"application/json","x-github-event":"issues","accept-encoding":"gzip","accept":"*/*","cf-ipcountry":"US","cdn-loop":"cloudflare; subreqs=1","x-amzn-trace-id":"Root=1-65024c8d-021dee372681e3f462d7bd31","content
```

https://github.com/infinyon/fluvio/assets/26554085/e29fb4be-8c29-4472-a630-801ed65aaf18

**Comment by digikata** [comment]
Initial triage suggests an interaction between output formatting and terminal control codes, redirecting binary output to a file correctly consumes the data.
