### ISSUE TITLE
tech debt: migrate `fluvio-cluster` to use anyhow

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#3541]
remove unnecessary specialized error which could be removed by migrating to anyhow

**Comment by jsat97** [comment]
@sehz could you please provide some pointers to help me get started ?

**Comment by sehz** [comment]
Hi.   https://github.com/infinyon/fluvio/blob/master/crates/fluvio-cluster/src/error.rs mostly wrap existing error which could be removed by using anyhow like: https://github.com/infinyon/fluvio/blob/master/crates/fluvio-cluster/src/start/local.rs#L486

**Comment by fraidev** [comment]
Hi! I opened a PR for this issue.

https://github.com/infinyon/fluvio/pull/3853

**Comment by digikata** [comment]
Merged PR and closed!. Thanks @fraidev!
