### ISSUE TITLE
provide CLI plugin framework and move cloud sync out of fluvio

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#355]
We should provide way to extend CLI with extensible plug-in similar to how other platform does.
- helm
- Kubectl

**Comment by sehz** [comment]
Other implementations such as : https://doc.rust-lang.org/book/ch14-05-extending-cargo.html

**Comment by nicholastmosher** [comment]
Clap has a feature to enable "external subcommands", which basically let you capture a subcommand term that you were not expecting, rather than printing the help menu. For example, if we executed `fluvio foo --bar --baz=3`, then we can get back an ArgMatches object with the structured subcommand arguments in it. Then, we can check the PATH for an executable called `fluvio-foo` and forward the arguments to it.

**Comment by sehz** [comment]
nice!

**Comment by sehz** [comment]
If we decided to implement plug-in system.,  We may break apart CLI again rather than in monolithic mode.   Downside of monolithic CLI is that it incur increase of build time which saw in the last release.  It was taking order >10 min to build release version of CLI.  If we have plug-in system, we can still have a single CLI but have flexibility of mix and match features dynamically.   For example, we could have SC and SPU as plug-in and download them as needed.

**Comment by ajhunyady** [comment]
This is also important for the Raspberry PI image. Cross compilation failed and there are so many dependencies, it would be a pain to track them all down.

**Comment by sehz** [comment]
It should have at least following plug-in commands
- `install <new_plugin> -f <force>`
- `uninstall`

Plugin should be downloaded into some area we have permission to write.

**Comment by nicholastmosher** [comment]
I think that having install/uninstall commands is something we would do if we had a public registry and package manager for fluvio plugins, which we don't right now. What are you imagining to happen if a user were to run `fluvio install fluvio-foo` or something? The only possible reasonable thing I can think of it doing would be to invoke cargo to install something, but that would require all users to have Rust installed, which I don't think we want.

I think we should restrict the scope of this to just searching for external subcommands. For reference, this is how Cargo handles external subcommands using clap:
- https://github.com/rust-lang/cargo/blob/master/src/bin/cargo/cli.rs#L216-L228
- https://github.com/rust-lang/cargo/blob/master/src/bin/cargo/main.rs#L142-L179

**Comment by sehz** [comment]
We can also move cluster command as plug-in as well ( #335)
Other commands that can be move out
- SPU and SPG related commands

CLI should be strip down to bare bore minimum eventually.  It should just focus on:
- topic management
- produce/consumer

**Comment by sehz** [comment]
Requirements for plug-in system
- can't rely on Rust's cargo.  It need to be loaded without external compilers/tools.   This probably means, plug-in binary must be built for the platform and published somewhere. 
- some way to search for plug-in.  we can put convention for fluvio plugins.  For others, we can impose certain naming convention to find plug-in binaries.

**Comment by sehz** [comment]
With [helm]( https://helm.sh/docs/topics/plugins/), user can configure where they want to install plug-in.

Also, we don't need modify user's path.  We can (which)[https://crates.io/crates/which] to locate plug-in in our plug-in directory

**Comment by sehz** [comment]
Also, it might make sense to move CLI out of Fluvio repo and into separate repo

**Comment by nicholastmosher** [comment]
The bulk of this was taken care of with #406, and once #410 is merged I think this can be closed.

**Comment by sehz** [comment]
basic plug-in infrastructure is complete.
