### ISSUE TITLE
`smdk version` and `cdk version`

### ISSUE THREAD

**Issue by matheus-consoli** [infinyon/fluvio#3552]
Currently, the only way to know which version we're running is by reinstalling the binary.

We should:

- add a `smdk version` to display the current `smdk` version
- add a `cdk version` command to show the current `cdk` version

**Comment by tjtelan** [comment]
`fluvio version` is useful for short circuiting user error because it includes other build-time and env information like git commit, platform, binary sha. I suggest we re-use that pattern where it is common between the three binaries
