### ISSUE TITLE
In `smdk test`, prototype a better way for errors to be reported

### ISSUE THREAD

**Issue by digikata** [infinyon/fluvio#3572]
In the smartmodule-development-kit crate, prototype how errors can be reported to the user.

It might be nice to provide a way for the application code in the smartmodule to be able to mark some errors as intentional application level errors. 

A way for the user to distinguish general errors vs application errors would also be nice.

**Comment by therealhieu** [comment]
HI, I am starting to resolve this issue.

Would you mind providing me cases that errors are not reported in a good way?

**Comment by digikata** [comment]
Hi Hieu, thanks for spending some time looking at this.  

A test case to look at is:
- `smdk generate`  a smartmodule type (a default filter is fine)
- insert code to produce error or print logs
- build the module
- run `smdk test --text input-text`

This is a little open ended what to improve. There is currently no path to capture and print trace warn/error output from the wasm module in smdk test.  Or if the module panics into the module, the backtrace fairly lowlevel, not referencing function names. The improvements can be in a single focused sub area - just open an issue on the focused area.

**Comment by sehz** [comment]
We could enable WASI context in the SmartEngine dynamically.   This may also need some work on SMDK to generate `wasm32-wasi`  target.

**Comment by ajhunyady** [comment]
I would like to be able to see the output for such statements in the stdout:

```
println!("hello there!");
```
