### ISSUE TITLE
change default log directory for linux

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#361]
In linux, log directory is `/var/log/fluvio`

```
fluvio cluster install --local
Error: 
   0: IO error
   1: Permission denied (os error 13)

Location:
   /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/fluvio-cli-0.1.2/src/root_cli.rs:136
```

we should change so it doesn't require sudo.

**Comment by vijaylaxmid** [comment]
@sehz What should the new log directory location be for Linux?

**Comment by nicholastmosher** [comment]
I don't know if it's a great idea to just dump a bunch of files into `/tmp`. Would it be possible to use a directory like `/usr/local/var/log/fluvio`? Are there more standard non-priveleged places we can put logs?

**Comment by vijaylaxmid** [comment]
For macOS we put in under `/usr/local/var/log/fluvio`, but for Linux, there are privilege issues, hence `/tmp` is a temporary solution I guess.

**Comment by sehz** [comment]
If you can found non privilege directory, please comment here, otherwise we need to use `/tmp`.  Note that this changes CLI option not installer defaults which still using privilege directories.

**Comment by vijaylaxmid** [comment]
We need to use `/tmp` as the default directory as the solution for now.

**Comment by vijaylaxmid** [comment]
Going further we can explore any other option for Linux.
