### ISSUE TITLE
Bug: SPU is sometimes not provisioned upon cluster install

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#362]
Sometimes after running `fluvio cluster install`, the SC comes online as expected but the SPUs are never provisioned, causing the installer to hang in an exponential backoff loop. I have not been able to figure out how to reproduce this, I suspect that it is a timing issue with the "create managed spu group" request being sent before the SC pod is fully up.

**Comment by sehz** [comment]
Hmm.  

Can you paste results of ```fluvio spu list```  and ```fluvio pods ``` if this happens?.

**Comment by sehz** [comment]
Reopen if bug can be reproduced
