### ISSUE TITLE
Allow annotations in fluvio profiles

### ISSUE THREAD

**Issue by nacardin** [infinyon/fluvio#3627]
The Fluvio profile should have an annotations section which allows other tools to "tag" or "label". I imagine this should work just like kubernetes object annotations.

Example 1:
```
[profile.<label>.annotations]
fluvio.io/cluster-type = "local-k8"
```

Example 2:
```
[profile.<label>.annotations]
infinyon.cloud/environment = "infinyon.cloud"
infinyon.cloud/cluster-name = "my-cloud-cluster-name"
```

**Comment by sehz** [comment]
This seems add unnecessary abstraction.  

Whole purpose of TOML is make it easier to express custom overrides.

**Comment by nacardin** [comment]
> This seems add unnecessary abstraction.

Annotations are context that are written and read by tools that manage profiles, not by the client.

> Whole purpose of TOML is make it easier to express custom overrides.

Good point, annotations can be added by external tools without profile structs having the field. But adding it to the profile struct makes it much easier by just setting fields and serializing along with the other config changes.

> This make it harder to parse and make it configurable error prone

Maybe, since they are string kv pairs. But this is not used for anything critical, and can recovered from if parsing fails.

**Comment by matheus-consoli** [comment]
After discussing this, we decided to follow a pattern more idiomatic for the TOML layout.

Instead of `[profile.<name>.annotations]` we should have an extensible metadata path like `[cluster.metadata.type]`.

For reference on how `cargo_metadata` implements a similar feature: https://github.com/oli-obk/cargo_metadata/blob/main/src/lib.rs#L171

**Comment by matheus-consoli** [comment]
Reopening the issue because we reverted the PR

new PR: https://github.com/infinyon/fluvio/pull/3667

**Comment by matheus-consoli** [comment]
Closing as completed, we added metadata support https://github.com/infinyon/fluvio/pull/3667
