### ISSUE TITLE
Investigate and fix CI service account authentication problems

### ISSUE THREAD

**Issue by matheus-consoli** [infinyon/fluvio#3634]
Some smoke tests were trying to connect to the hub service, but the authentication is currently failing.

We need to investigate what the issue is and try to fix it. It may be the case that the CI secret is invalid or ill-formatted.

Related to #3559 and #3612

**Comment by digikata** [comment]
This kind of test should probably get attached to the hourly workflow and not be a potential test failure for a CI merge check.
