### ISSUE TITLE
Revise smartmodule examples to use latest interface

### ISSUE THREAD

**Issue by digikata** [infinyon/fluvio#3639]
resolve warnings for example build

```
cd smartmodule/examples
make build
```

**Comment by MuhtasimTanmoy** [comment]
Working on this issue.

**Comment by digikata** [comment]
Hi @MuhtasimTanmoy, welcome & thanks for picking up this issue!

**Comment by MuhtasimTanmoy** [comment]
Hi, @digikata. 

PR https://github.com/infinyon/fluvio/pull/3661 looks good?

**Comment by MuhtasimTanmoy** [comment]
There is another issue.

Shouldn't this line be `fluvio-smartmodule = { workspace = true }` ?

https://github.com/infinyon/fluvio/blob/d536bbc590323d3f16cfe7cdbcb7d710675074a1/smartmodule/examples/filter_with_param_v1/Cargo.toml#L13

**Comment by digikata** [comment]
Started our CI tests on your submission, thanks!

Good eye re consistency on that one example, but that is likely a set version because it's a test case for an older version of smartmodule (though we may deprecate and remove support for that at some point).
