### ISSUE TITLE
OS details for Linux binary is wrong

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#364]
download [CLI](https://github.com/infinyon/fluvio/releases/download/v0.6.0-alpha.2/fluvio-v0.6.0-alpha.2-x86_64-unknown-linux-musl) for linux.  

```
fluvio version
Fluvio version : 0.6.0-alpha.2
Git Commit     : 9534b85bc34866acf50a13f777ee57ebf43e35fa
OS Details     : Darwin 19.6.0 x86_64
Rustc Version  : 1.46.0 (04488af 2020-08-24)
```

OS details is coming from cross compiler not actual target.

**Comment by nicholastmosher** [comment]
What information should this display? Should it print the target triple? E.g. `arm-unknown-linux-gnueabihf` (for raspi)? Or should it just wrap uname on the client device?

**Comment by sehz** [comment]
I think make sense to print actual runtime info
