### ISSUE TITLE
Remove `fluvio update` in place of `fvm update`

### ISSUE THREAD

**Issue by EstebanBorai** [infinyon/fluvio#3642]
Remove `fluvio update` and replace instances with `fvm update` which installs most
recent Fluvio Version in the `latest` or `stable` channels.

**Comment by ajhunyady** [comment]
@EstebanBorai the PRD has an `update` command. 

https://github.com/infinyon/roadmap/blob/main/prd/fluvio-version-manager.md#usage-after-install

We need that as users don't expect to run `fmv install` for an update.

**Comment by EstebanBorai** [comment]
> @EstebanBorai the PRD has an `update` command.
> 
> https://github.com/infinyon/roadmap/blob/main/prd/fluvio-version-manager.md#usage-after-install
> 
> We need that as users don't expect to run `fmv install` for an update.
> 
> The title should be move `fluvio update` to `fvm update`

Fixed! Thanks for pointing it out!

**Comment by EstebanBorai** [comment]
> @EstebanBorai the PRD has an `update` command.
> 
> https://github.com/infinyon/roadmap/blob/main/prd/fluvio-version-manager.md#usage-after-install
> 
> We need that as users don't expect to run `fmv install` for an update.
> 
> The title should be move `fluvio update` to `fvm update`

Here is the tracking issue: https://github.com/infinyon/fluvio/issues/3644
