### ISSUE TITLE
Remove `fluvio install` Command

### ISSUE THREAD

**Issue by EstebanBorai** [infinyon/fluvio#3646]
By the introduction of FVM, Fluvio Plugins are now introduced using FVM instead.

**Comment by ajhunyady** [comment]
Please review docs and remove "fluvio install smdk" and "fluvio install cdk".
* fluvio.io docs
* infinyon.com blogs
* labs-projects

**Comment by EstebanBorai** [comment]
> Please review docs and remove "fluvio install smdk" and "fluvio install cdk".
> 
> * fluvio.io docs
> 
> * infinyon.com blogs
> 
> * labs-projects
> 
> 

Sure thing! Thanks!
