### ISSUE TITLE
CLI Review Proposal 1

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#367]
As part of the CLI Review (#240), I'm going to make individual proposals for reorganization of CLI subcommands. This first proposal has to do with grouping commands by their _action_ (e.g. "create", "delete", "list") rather than by their _object_ (e.g. "spu", "topic", "partition").

As I was looking at the CLI subcommand structure, I noticed that a lot of the leaf commands were similar. For example, we have the following instances of `create`, `delete`, and `list` commands:

```
# Create commands
01 fluvio spu-group create
02 fluvio topic create
03 fluvio custom-spu register        // A "create" command with a different verb

# Delete commands
04 fluvio spu-group delete
05 fluvio topic delete
06 fluvio custom-spu unregister      // A "delete" command with a different verb

# List commands
07 fluvio spu list
08 fluvio spu-group list
09 fluvio custom-spu list
10 fluvio topic list
11 fluvio partition list
```

I looked closer and noticed that all of the `list` commands do not take any arguments, and that all of the `delete` commands take one argument. I believe that we can condense these commands by reversing the order of the action ("list") and object ("spu", "spu-group", "custom-spu", etc.). If we did this re-ordering, our new set of commands might look like this:

```
# List command
01 fluvio list <args>

# Delete command
02 fluvio delete <type> <args>
```

By rearranging the commands this way, we're able to condense 8 CLI commands into just two commands that take positional arguments. A further benefit of this is that we can compose multiple command invocations at once. For example, we might list our topics and spus at the same time, or we might list all of our objects.

```
$ fluivo list topics spus    # or,
$ fluvio list all
```

### Special case: Create commands

Note that I didn't mention the family of `create` subcommands. That's because the `create` commands have differing options based on the type of object we're trying to create. Something important to note is that this rearrangement of commands does not prevent us from making special cases for the create subcommands. For example, we could have the following special cases for `fluvio create topic` and `fluvio create spu`group`:

```
$ fluvio create topic
Creates a topic

fluvio create topic [FLAGS] [OPTIONS] <name>

FLAGS:
    -i, --ignore-rack-assignment    Ignore racks while computing replica assignment
    -d, --dry-run                   Validates configuration, does not provision

OPTIONS:
    -p, --partitions <partitions>           Number of partitions [default: 1]
    -r, --replication <integer>             Replication factor per partition [default: 1]
    -f, --replica-assignment <file.json>    Replica assignment file

ARGS:
    <name>    Topic name
```

```
$ fluvio create spu-group
Create managed SPU group

fluvio create spu-group [FLAGS] [OPTIONS] <name>

OPTIONS:
    -r, --replicas <integer>           SPU replicas [default: 1]
        --min-id <min-id>              Minimum SPU id (default: 1) [default: 1]
        --rack <string>                Rack name
        --storage-size <string>        storage size

ARGS:
    <name>    Managed SPU group name
```

## Discussion

Please leave feedback for this change in the comments. I believe this change can help streamline our CLI by minimizing the number of top-level commands (actually, the number of total commands) and by making the common set of actions more intuitive (e.g. the `list` command) while not handicapping the needs of the richer commands (e.g. the `create` commands).

**Comment by sehz** [comment]
BTW, I don't think there will be use case for listing multiple types or all types since they are different types.

**Comment by nicholastmosher** [comment]
I can think of one. I like to use the `watch` command to give me status updates on frequent commands in my terminal. It'd be nice to be able to say `watch fluvio list all` or `watch fluvio list topics spus`.

**Comment by nicholastmosher** [comment]
I think I will go ahead and close this, we've had a lot of churn in the CLI since this was opened.
