### ISSUE TITLE
Tracking: Improve the testing experience

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#370]
Right now our tests have some rough edges that make them difficult to write and to run. We should consider investing some time into polishing our testing experience. I've got some initial problem spots I want to highlight and some wishlist items to bring up:

Problem spots:
- When running smoke tests on local minikube cluster, the uninstall command that runs before the test can hang for up to a minute, blocking the test from starting.
- Tests seem to be largely timeout-based. This causes them to be flaky and not always work.
- The integration tests seem very far removed from the actual implementing code, causing tests to not be a forethought but an afterthought.

Wishlist items:
- I think it would be great to have an integration test harness that only runs when a kubernetes environment is available and instantiates a new namespace per test (or group of tests).

**Comment by sehz** [comment]
Sure. lets create separate issue.

**Comment by sehz** [comment]
Re-assign back to @nicholastmosher to update to see if any of these issues are still remaining and generate actional items

**Comment by nicholastmosher** [comment]
This was written before our fluvio-test-derive framework was built, a lot of problems have been solved by it. Closing this, we can open more specific test improvement issues as needed.
