### ISSUE TITLE
FVM - Changing `fluvio` version while running breaks process

### ISSUE THREAD

**Issue by EstebanBorai** [infinyon/fluvio#3729]
Using `fvm` to upgrade Fluvio or change versions while Fluvio is running causes Fluvio process to be killed.

```
$ fvm switch <VERSION>
done: Now using Fluvio version <VERSION>

$ fluvio version
Killed: 9

$ fvm switch stable
done: Now using Fluvio version stable

$ fluvio version
Killed: 9
```

## Steps to Reproduce

1. Install FVM
2. Start Fluvio locally `fluvio cluster start --local-k8`
3. Install a Fluvio version via FVM `fvm install <VERSION>`
4. Attempt to run `fluvio version`
5. Check out output to be `Killed: 9`

**Comment by digikata** [comment]
I found this interesting discussion: https://apple.stackexchange.com/questions/258623/how-to-fix-killed-9-error-in-mac-os
Though there are multiple non-definitive solutions, this comment was interesting: "I solved the Killed: 9 error, by running rm then cp instead of just cp."

**Comment by EstebanBorai** [comment]
Hello @digikata! I just validated #3735 locally and it worked like a charm!


https://github.com/infinyon/fluvio/assets/34756077/ae7f217d-b02c-49fb-86ba-97efc65ed252

Im closing this issue now!
