### ISSUE TITLE
fluvio consume from a topic that does not exist, should return an error

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/fluvio#373]
Just run

`$ fluvio consume topic-abc`

If **topic-abc** does not exist, the command never returns.
It should return an error instead

`Cannot find topic 'topic-abc'`

**Comment by sehz** [comment]
let's add this to smoke test runner.

**Comment by sehz** [comment]
related to #389.  By default, partition look up waits for up to 120 seconds for topic to show up.  This will changed to use try_lookup (new api in the store context) which will immediately fails if topic doesn't exist
