### ISSUE TITLE
Usability Issue: move `--tranforms-file` to `-t --tranforms` and remove inline option.

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/fluvio#3773]
### Problem

In both `fluvio` and `smdk` we have 2 options to test transformations:

```
     --transforms-file <TRANSFORMS_FILE>  (Optional) File path to transformation specification
  -t, --transform <TRANSFORM>              (Optional) Pass transformation specification as JSON formatted string. E.g. smdk test --text '{}'
                                           --transform='{"uses":"infinyon/jolt@0.1.0","with":{"spec":"[{\"operation\":\"default\",\"spec\":{\"source\":\"te...
```

I found myself using the wrong keyword multiple times. That coupled with the error message, leads into confusion and base use experience.

```
$ fluvio consume quotes -B -t ./transforms.yaml
Invalid argument: unable to parse `transform` argument: expected value at line 1 column 1
```

### Solution

In both `smdk` and `fluvio` change transforms flag to use a file:

```
  -t, --transform <TRANSFORM_FILE>          (Optional) File path to transformation specification
```

Remove inline variant:

 <s> -t, --transform <TRANSFORM>              (Optional) Pass transformation specification as JSON formatted string. E.g. smdk test --text '{}'
                                           --transform='{"uses":"infinyon/jolt@0.1.0","with":{"spec":"[{\"operation\":\"default\",\"spec\":{\"source\":\"te...</s>

**Comment by galibey** [comment]
Removing the inline variant is too harsh solution. I use it often when I need to quickly test something simple and be able to quickly change/run/see the result in the command line. And, it is also used in our cli tests. 
We could move the short form `-t` from `--transform` to `--transforms-file` as it seems like the latter is used more frequently. Also, we could improve error messaging: if you pass json when it expects a path, we could say that you probably want to run another command instead.  WDYT @ajhunyady

**Comment by ajhunyady** [comment]
Ok, in that case we should swap, as the `transform` is the much more common variant.
We should call the other `--transforms-line` or something similar.
