### ISSUE TITLE
[Bug]: Why does the echo example only consumes 10 messages regardless of how many messages are sent on Tokio runtime?

### ISSUE THREAD

**Issue by marvin-hansen** [infinyon/fluvio#3778]
**What happened**

Run the echo example.

Change the number of messages to send in the loop to any number greater than 10, say 16.

**Expected behavior**

I would expect to see, well, 16 messages consumed. 

**Actual behavior**

No matter the number, the consumer stops after exactly 10. 

It's a miracle; I have never seen this with any other messaging system.

**Describe the setup**

- Are you using a local Fluvio install? Minikube? Fluvio Cloud?
Local.

- What version of Fluvio are you using? `fluvio version`
Fluvio CLI           : 0.11.2
Fluvio CLI Arch      : aarch64-apple-darwin
Fluvio CLI SHA256    : 2db084880a36e9aeed5b28e67f78fa2df3531558e6d8bd9e36a355ca970654ac
Fluvio channel frontend SHA256 : 2db084880a36e9aeed5b28e67f78fa2df3531558e6d8bd9e36a355ca970654ac
Fluvio Platform      : 0.11.2 (local)
Git Commit           : cddc05388b7a1278837adc506430f339f311212d
OS Details           : Darwin 14.2 (kernel 23.2.0)
=== Plugin Versions ===

**How to reproduce it (as minimally and precisely as possible)**

1) curl -fsS https://hub.infinyon.cloud/install/install.sh | bash
2) echo 'export PATH="${HOME}/.fvm/bin:${HOME}/.fluvio/bin:${PATH}"' >> ~/.bashrc
3) fluvio cluster start
4)  fluvio topic create echo
5) fluvio topic list

fluvio topic list
  NAME  TYPE      PARTITIONS  REPLICAS  RETENTION TIME  COMPRESSION  DEDUPLICATION  STATUS                   REASON
  echo  computed  1           1         7days           any          none           resolution::provisioned

6) Copy the echo example code in a local Cargo project.

The only difference to the example code is that I use the Tokio runtime. 

Full source code here: https://gist.github.com/marvin-hansen/ade251236cfea67c9a8c4099842ef155#file-main-rs

7) Cargo run 

Output:
https://gist.github.com/marvin-hansen/ade251236cfea67c9a8c4099842ef155#file-output-txt

This bug is totally bonkers:
1) Default config -> Same 
2) Custom config -> Same
3) Flush after all send -> Same
4) Flush after each send -> Same
5) No wait after send -> Same
6) Wait after send to let consumer catch-up -> Same
7) Change batch/size or linger -> Same

Why can't the consumer receive more than 10 messages?
 
It's my first time with Fluvio and I can't believe what my eyes are seeing. 
I have never seen anything like this in ZMQ, NATS, or Zenoh. 
You send 10, you get 10. You send 100, you get 100. 

With Fluvio, you send 25, you get 10. You send 100, you get 10. Whatever, you always get 10.

How do you even do that???

**Log output**
It helps to have logs from Fluvio's SC and SPU processes.
Depending on your setup, here's how you can get the logs:

- For a local Fluvio installation on Mac:
  - Run `cat /usr/local/var/log/fluvio/flv_sc.log` for SC logs

cat: /usr/local/var/log/fluvio/flv_sc.log: No such file or directory

  - Run `cat /usr/local/var/log/fluvio/spu_log_XXXX.log` for each SPU
    - E.g. when running 1 SPU, there will be `spu_log_5001.log`
    
ls: /usr/local/var/log/fluvio/: No such file or directory

**Environment (please complete the following information):**
 - OS:  Mac OS 14.2
 - Fluvio Version 0.11.2

**Additional context**

**Comment by morenol** [comment]
Hey @marvin-hansen, thanks for reporting the issue. Could you share the output of `fluvio partition list`?

I wonder if the `echo` topic has old data from a previous run, and since you break the consumer when it receives a `Done` is retrieving the data until that record.

**Comment by marvin-hansen** [comment]
Wait, what?  The topic is persistent by default?

That would explain a lot.

How do I clear this out? Just restart Fluvio?

**Comment by marvin-hansen** [comment]
Here is the output:

`
fluvio partition list
  TOPIC  PARTITION  LEADER  REPLICAS  RESOLUTION  SIZE     HW    LEO   LRS   FOLLOWER OFFSETS
  echo   0          5001    []        Online      35.7 KB  1028  1028  1028  0                 []
`

**Comment by morenol** [comment]
By default it has a retention time of 7 days.  The data is persisted on disk if you are using fluvio locally. So, If you want to clear it, I suggest you to run `fluvio topic delete echo` and `fluvio topic create echo`.

You can also update consumer to start from the end with:
```rust
    let mut stream = consumer.stream(Offset::end()).await?;
```

**Comment by morenol** [comment]
> Here is the output:
> 
> `fluvio partition list TOPIC PARTITION LEADER REPLICAS RESOLUTION SIZE HW LEO LRS FOLLOWER OFFSETS echo 0 5001 [] Online 35.7 KB 1028 1028 1028 0 []`

Yes, it looks like you have `1028` records in your topic. so probably it is breaking the loop after the first 10 records produced from a previous attempt

**Comment by marvin-hansen** [comment]
Solved.

I confirm:

1) Plenty of old data in the pipe.
2) Offset:beginning was the problem.
3) Offset::end() has solved it.

I was simply unaware of the persistent on disk mechanism.

That said, is super awesome because it allows me fine grained recovery in case of an error. 

Thanks a lot for you help. I think this project is a clear winner and will be adopted in no time for my project. 

Closing for good.
