### ISSUE TITLE
CLI Discussion: Terminology

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#379]
Right now when you look at the top-level menu of the CLI, you see this:

```
Fluvio Command Line Interface

fluvio <SUBCOMMAND>

FLAGS:
    -h, --help    Prints help information

SUBCOMMANDS:
    consume       Reads messages from a topic/partition
    produce       Writes messages to a topic/partition
    spu           SPU operations
    spu-group     SPU group operations
    custom-spu    Custom SPU operations
    topic         Topic operations
    partition     Partition operations
    profile       Profile operations
    cluster       Cluster operations
    run           Run cluster component
    version       Prints the current fluvio version information
    help          Prints this message or the help of the given subcommand(s)
```

One of the things that bugs me about this is how there are three different types of SPU commands and as a new user I don't think it would be obvious what each one does. I think there is an opportunity here to streamline the CLI by brainstorming some terminology for expressing related items, then grouping those items together.

There are a few terms I'd like to brainstorm either alternative names or alternative relationships with:

1) SPU groups
2) SPU/Custom SPU
3) Partition

### 1: SPU Groups

Right now the CLI has `spu-group`, but we have referred to an `SPG` as its own noun before, a "Streaming Processing Group". That sounds like a nice term to nail down and get behind. I'd like to commit to using SPG as a proper term we use throughout the product and documentation.

### 2: SPU/Custom SPU

A not-so-clear term is what the CLI now calls `custom-spu`. This is really the same thing as a SPU but with a different configuration. A question in my head now is whether we should describe "SPU" and "Custom SPU" as:

- two separate top-level entities (the way the CLI expresses it now), or more like
- "they are both SPUs, but one is managed and one is custom".

I think that it would make more sense to describe this relationship the second way. If we do decide to do this, we could group all of the operations belonging to SPUs into a single top-level command, then let the subcommands distinguish the difference. For example, right now we have the following command layout:

```
fluvio spu list                          List custom & managed SPUs
fluvio custom-spu register               Create custom SPU
fluvio custom-spu unregister             Delete custom SPU
fluvio custom-spu list                   List custom SPUs
```

I think it may be possible to group them like this instead:

```
fluvio spu list                          List custom & managed SPUs (add --custom or --managed flags to filter the list)
fluvio spu register               Create custom SPU
fluvio spu unregister             Delete custom SPU

// Possible future commands for managed SPUs are not interfered with
fluvio spu add/allocate/provision
fluvio spu delete/drop/deallocate
```

### 3: Partition

Right now, a partition is its own top-level entity in the CLI. This give the impression that it is a top-level entity. I want to ask whether we think that

1) a partition is conceptually its own top-level entity
2) a partition is its own entity, but it belongs to a topic entity, or
3) a partition is nothing more than a configuration parameter of a topic, not an entity at all

I think coming to a good understanding of how these things are conceptually related to each other can help us design the layout of the CLI to introduce these ideas to people in an intuitive way.

---

I'd like to hear discussion about the points above. Note that this is an orthogonal issue to #367 (reversing actions and objects), this is more of a conceptual discussion about the relationship of entities of Fluvio, driven by the need to organize the CLI.

**Comment by sehz** [comment]
One thing we missing is scaling up/down for `spg`.  For example, we may want to:
```
$ fluvio spu-group scale main 5
```

This will scale number of SPU in the SPG group to be 5

**Comment by sehz** [comment]
I like 
 ```
fluvio spu register               Create custom SPU
fluvio spu unregister             Delete custom SPU
```

Also, we can move `run command here` too

**Comment by sehz** [comment]
Also list command can have filter for SPU type as well.

**Comment by nicholastmosher** [comment]
> One thing we missing is scaling up/down for `spg`. For example, we may want to:
> 
> ```
> $ fluvio spu-group scale main 5
> ```
> 
> This will scale number of SPU in the SPG group to be 5

I have a follow-up question: Would you consider a SPU Group to be its own entity? Or would you say that a group is nothing more than a property of an SPU? Can there be an SPG with zero SPUs? Is an SPG just a particular label that you use to refer to all SPUs with that label? What kinds of operations can an SPG do?

**Comment by sehz** [comment]
I would consider `SPG` to be its own entity since it refers to group of SPU.    So managed SPU's are member of SPG. If you look at k8, they have different levels of abstraction.  For example, they differentiate "Pod" vs "Deployment".

SPG can scale be scaled up/down.  We can add rolling update or another deployment workflows.

**Comment by ajhunyady** [comment]
@nicholastmosher, there are some great ideas here. spu/custom SPU consolidation makes sence.
I also think spg should stay top level as it is a wrapper around multiple groups of SPUs that are linked into the same stateful set.

**Comment by sehz** [comment]
Yes, partitions should be able to scale up/down.  But it is fairy complex topic.  For example, in the Kafka, partitions can be only added.  When partitions change, we may need to remap records.

**Comment by nacardin** [comment]
Does it ever make sense to group unmanaged/custom SPUs?

**Comment by ajhunyady** [comment]
No it does not. However, it makes sense to distribute replicas across them.

**Comment by ajhunyady** [comment]
Topics can be replicated based on rack assignment. While that works, the label "rack" is misleading. We'll likely have to redesign that section later.

**Comment by sehz** [comment]
Custom SPU are no different from manage SPU in terms of features.  Only difference is that we don't manage lifecycle.  If customer can write their own provisioning system and group them that make sense for them.

**Comment by ajhunyady** [comment]
`$ fluvio partition` needs the ability to show individual partitions. The list format is difficult to read for replication factor of 3. Also users  in general looking at 1 partition at a time.

**Comment by sehz** [comment]
Let's split this issue for partition from spu related commands

**Comment by nicholastmosher** [comment]
One thing that's confusing me a little bit is that we seem to be mixing two different levels of abstraction together. Here are the two levels that I'm seeing:

# Client-level abstractions

At the top-level, we have the ideas of Topics, Partitions, and, to an extent- Replicas. A Topic is a category which maps closely to the application's domain. There may be Topics such as:

- `accounts`, with events such as "create account", "edit email address", "delete account";
- `chatroom`, with events such as "User X sends 'hello' to User Y", or "User X has read message 1234"

A Partition also lives at this top-level of abstraction, but it is used to enable parallelism. A Partition is a logical division of the events within a single Topic. A Partition is also the unit of ordering: events must be sent to the same partition in order to guarantee that those events are saved and arrive in order to a consumer.

I believe a Replica should be considered at this client-level of abstraction, although I think that it has been mixed and jumbled in the implementation for awhile. I would say that the "replication factor" is a property of a Topic - the property of how many times the data of the Topic is persisted (at minimum). If I had to put it as a noun, I would say that a Replica is an instance of a Partition. I visualize it like this:

```
+===========================================================+
|         |               |  Replica A (Partition 0 Leader) |
|         |               |---------------------------------|
|         |  Partition 0  |  Replica B                      |
|         |               |---------------------------------|
|         |               |  Replica C                      |
|         |=================================================|
|         |               |  Replica D (Partition 1 Leader) |
|         |               |---------------------------------|
|  Topic  |  Partition 1  |  Replica E                      |
|         |               |---------------------------------|
|         |               |  Replica F                      |
|         |=================================================|
|         |               |  Replica G (Partition 2 Leader) |
|         |               |---------------------------------|
|         |  Partition 2  |  Replica H                      |
|         |               |---------------------------------|
|         |               |  Replica I                      |
+===========================================================+
```

Notably here, these relationships form a tree. Any Partition has exactly one parent Topic,
and any Replica has exactly one parent Partition.

# Implementation-level abstractions

At the lower-level of abstraction, we have SPUs and SPU Groups. A single SPU is a process that receives, persists, and delivers events as necessary. We can even say that a single SPU occupies an entire Node in a cluster. I am calling this layer "implementation-level" because the layout and organization of SPU's and SPG's have (or should have) no impact on the domain of events from the user.

# Connecting the abstractions

The place where I start to get confused is when we imagine the mapping between these levels of abstraction. It seems to me that there are some kinds of rules here:

- A single Replica may not be mapped to more than one SPU
- Multiple Replicas belonging to unique partitions may be mapped to a single SPU
- In order to have a replication factor of X, there must exist at least X SPUs
- Having N partitions does not require N SPUs; N partitions may be mapped to 1 SPU

There may be more rules here, also feel free to tell me if I have misinterpreted anything.

With these relationships laid out, what is the purpose of a SPU group? Would a SPU Group belong to a single Topic, or could multiple Topics map their replicas onto SPUs in an SPG? Would an SPG be able to have fewer SPUs than the replication factor of a Topic? Or would the replication factor be a lower-bound on the size of an SPG? What would be the effect of "scaling up" an SPG? These are things that I don't really have an answer for yet in my head.

**Comment by sehz** [comment]
They belong to different levels of concerns.   Topic mapped Partitions which maps To Replicas.   Replicas map to SPU.   That's end of stream mapping.

SPU and SPG are pure infrastructure concerns.   SPG manages group of SPUS.  How SPU manage replicas not really concerns of SPG.  All SPG concern is scaling SPU.
