### ISSUE TITLE
MQTT Connector:  Prefix auto generated Client ID to prevent connection drops

### ISSUE THREAD

**Issue by digikata** [infinyon/fluvio#3825]
Add an option to prefix mqtt client_id with an auto generated identifier.  

Fluvio issue to surface the mqtt-connector issue at https://github.com/infinyon/mqtt-connector/issues/49

Great way to dip you toes into fluvio, rust if you know a little mqtt!

**Comment by deepakprasanna** [comment]
Can I take this?

**Comment by ajhunyady** [comment]
Hi @deepakprasanna, that would be great, thank you.

**Comment by PanGan21** [comment]
Hi! Is this issue still available?
If that is the case could you provide some pointers on the required changes?

**Comment by drc-infinyon** [comment]
@digikata can you please share some additional context.

**Comment by digikata** [comment]
Hi @PanGan21 thanks for looking at this, I'll add some detail to the linked issue, and feel free to ask more questions!
