### ISSUE TITLE
connector: fluvio-http-source, add an option to read data from a websocket

### ISSUE THREAD

**Issue by digikata** [infinyon/fluvio#3829]
The http-source-connector can read data in many forms over http protocols to be produced into a fluvio cluster. But it doesn't understand websockets.

Add the option to read websockets to the connector.

Details at https://github.com/infinyon/http-source-connector/issues/142

**Comment by pranoyk** [comment]
@digikata I would like to pick this up in case no one is working on it.

**Comment by digikata** [comment]
Hi @pranoyk, no one else is currently working on this.  Feel free to give it a try.  We are available for help here or at our [discord](https://discord.com/channels/695712741381636168/695731077406392360)

**Comment by pranoyk** [comment]
Hi @digikata, my apologies for starting late on this issue, I was pulled up at some other tasks.
I would need help running the code locally without installing the binary. I could not find any docs related to it.

**Comment by digikata** [comment]
Hi @pranoyk, no worries, thanks for taking your time to work with this project!

The http source connector project is structured in a cargo workspace so it has multiple crates in a workspace.  You can build and test with `cdk` in the top project dir:

- `cdk build -p http-source`
- `cdk test -p http-source --config crates/http-source/config-example.yaml` 

You still may need to install the dev environment as described in the fluvio connector dev docs [overview](https://www.fluvio.io/connectors/cdk/overview/).  

I'll add this info a developers.md doc in the project too.

**Comment by pranoyk** [comment]
Hey @digikata, I am unable to spend an adequate amount of time on this. Hence, I won't be able to contribute to this for now. Maybe I will pick something else soon to contribute to this project.

**Comment by digikata** [comment]
closed by https://github.com/infinyon/http-source-connector/pull/162
