### ISSUE TITLE
Show Client and Platform version

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#383]
Currently when `version` command is perform in the CLI. It shows following:
```
fluvio version
Fluvio version : 0.6.0-alpha.2
Git Commit     : 9534b85bc34866acf50a13f777ee57ebf43e35fa
OS Details     : Darwin 19.6.0 x86_64
Rustc Version  : 1.46.0 (04488af 2020-08-24)
```

We should separate in terms of client and current server version.  So it should be something like:
```
fluvio version
Fluvio Client version : 0.6.0-alpha.2
Fluvio Platform version : 0.6.0-alpha.3
Git Commit     : 9534b85bc34866acf50a13f777ee57ebf43e35fa
OS Details     : Darwin 19.6.0 x86_64
Rustc Version  : 1.46.0 (04488af 2020-08-24)
```

**Comment by sehz** [comment]
Questions?
- Where to embeds version info? (VERSION API)?

**Comment by nicholastmosher** [comment]
Does the client currently have any way to access the cluster version information? It seems like no. Is that something that would be added to `fluvio-protocol` somewhere? Can we make a specific request type that reports version information? Or could we pack the version information into a header somewhere?

**Comment by sehz** [comment]
We could add server version to  Version Request which is already implemented as part of client to server negotiation

**Comment by nicholastmosher** [comment]
@sehz I'm planning on picking this up as my next task and I'm looking around for a starting point and I've got a few questions about what exists already:

- Is there any interface for a Client (i.e. a component of `Fluvio`, such as `SharedAllMultiplexerSocket`) to access the SC server version information?
- If not, does `fluvio-protocol` already carry the server version information that we could expose through the client? Based on your previous comment it sounds like there is at least a designated place for it in the protocol, but it might not actually be sent yet.
- Does the server component know its own version? Is it the same as from the repo's VERSION file or something different?
- Is there a difference between the protocol version and the server version? Do we want to report both?
- Which files should I start looking at to work on this? I'm not very familiar with the SC and the protocol so I've been sort of blindly searching.

Thanks for any tips you have :)

**Comment by nicholastmosher** [comment]
Alright I'm looking in `src/client/src/client/client.rs` and I'm seeing a `Versions` type wrapped around `fluvio_spu_schema::server::versions::ApiVersions`.

https://github.com/infinyon/fluvio/blob/f7268a5031b2012fc537560bfc3f51b939680360/src/client/src/client/client.rs#L188-L206

What does this "version" information represent? Since it's coming from `spu_schema` it seems like it would be reporting SPU versions. I don't think that's exactly what we want. If I'm not mistaken, this issue is about getting the SC server version. Would we need to simply follow a similar pattern with `fluvio_sc_schema::versions::ApiVersions`?

**Comment by sehz** [comment]
Updated comment to reflect current Fluvio version schema.  Instead of reporting `sc` version which is not well defined now, report `platform version`.   This can be added to `ApiVersionsResponse`

**Comment by ajhunyady** [comment]
How about?

Fluvio Client.    : 0.6.0-alpha.2
Fluvio Platform : 0.6.0-alpha.3

without version.
