### ISSUE TITLE
Build a new python wrapping for the fluvio client crate

### ISSUE THREAD

**Issue by digikata** [infinyon/fluvio#3842]
Fluvio-client-python repo https://github.com/infinyon/fluvio-client-python/issues/358

The ['rust-cpython](https://github.com/dgrunwald/rust-cpython) crate that the fluvio python client is currently built upon is no longer maintained and is EOL for Python 3.11.

Rebuild the fluvio python client on top of the [PyO3](https://pyo3.rs/) rust to python binding framework. For the initial rebuild, a simple wrapping of the fluvio rust crate in order to connect, consume and produce (preferably async) would be a good start.

Edit: clarification, the PyO3 rebuild should run in python 3.12

**Comment by adelinaenache** [comment]
Hey, new here, would like to give this a shot.
/attempt #3842

**Comment by urbit-pilled** [comment]
@algora-pbc Bounty claim doesn't work due to being in a separate repo https://github.com/infinyon/fluvio (this repo) and https://github.com/infinyon/fluvio-client-python (the repo with an open PR)

**Comment by drc-infinyon** [comment]
Let me take a look @urbit-pilled I will fix this.

**Comment by algora-pbc** [comment]
@urbit-pilled we registered your claim :pray: fyi you can always use the full path in your command like `/claim infinyon/fluvio#3842` (as long as the algora app is installed in the PR'd repo)

**Comment by digikata** [comment]
@urbit-pilled  Thanks for your PR https://github.com/infinyon/fluvio-client-python/pull/359, merged.  Nice Work!
