### ISSUE TITLE
fluvio topic how to increase number of partition

### ISSUE THREAD

**Issue by wking1986** [infinyon/fluvio#3843]
hello，fluvio topic how to increase number of partition？
I didn't find the corresponding command in the doc

**Comment by drc-infinyon** [comment]
Hi @wking1986:

Here is the CLI doc with the options - https://www.fluvio.io/cli/cluster/topic/

Here is the API page with the Clients and you can click into the clients for the options - https://www.fluvio.io/api/

Can you check and let me know if this resolves your query, or share more about what you are looking to do, your system config and data pipeline.

**Comment by ajhunyady** [comment]
Hi @wking1986,

Partitions in Fluvio have very low resource consumption, and our users over-provision to avoid partition rebalancing. Therefore, we did not implement this feature. 

However, we realize that in some cases, traffic exceeds estimates, and adding partitions becomes a mandatory requirement. We'll make this feature high priority.

**Comment by wking1986** [comment]
Get！Thanks ～～

**Comment by digikata** [comment]
Just to be clear, specifying the number of partitions on topic create is available on the cli and api.  In the fluvio cli its a flag on `fluvio topic create --partitions <num_partitions>'.   It's adding partitions after the topic is created that would be a new feature.

**Comment by wking1986** [comment]
Is there any progress on this feature?  Thank you

**Comment by bradvoth** [comment]
adding a vote for this

**Comment by ajhunyady** [comment]
@fraidev, this feature is relevant to standalone from mirroring.

**Comment by sehz** [comment]
We are starting to work partition management area.  First step is adding partition.    Would love to get feedback on use cases, edge scenarios and additional requirements.

**Comment by digikata** [comment]
Hi @wking1986 we just added a rfc document describing what we mind for adding partitions.  We would love for you to look through it and give any input you may have.

https://github.com/infinyon/fluvio/blob/master/rfc/add-partition.md

**Comment by wking1986** [comment]
Looks like it will match my needs. 
LGTM，Great!  Thanks～～

**Comment by fraidev** [comment]
https://github.com/infinyon/fluvio/pull/4065 solves it!
