### ISSUE TITLE
Does it support data persistence to object storage? eg S3

### ISSUE THREAD

**Issue by wking1986** [infinyon/fluvio#3847]
Hello，another problem：Does it support data persistence to object storage? eg S3

**Comment by digikata** [comment]
Core fluvio does not currently use S3, but it's straightforward to add a connector for sending topic records to an S3 bucket. We have been looking at adding a reference sink connector with the [opendal](https://crates.io/crates/opendal) which can access S3.

**Comment by wking1986** [comment]
Great！！

**Comment by drc-infinyon** [comment]
What is implicit in @digikata's comment is that we persist all the data in topics. Not on S3. We will share the details on the S3 connector in the [InfinyOn Labs Repo](https://github.com/infinyon/labs-projects)
