### ISSUE TITLE
Python client async and admin upgrade

### ISSUE THREAD

**Issue by digikata** [infinyon/fluvio#3859]
Map missing fluvio rust crate async and admin interfaces to python.

Details in Fluvio-client-python repo https://github.com/infinyon/fluvio-client-python/issues/367

**Comment by urbit-pilled** [comment]
I was trying to implement async without changing the fluvio repo upstream with the Clone modifications, but I think this is a good solution @Shylock-Hg. You can takeover the bounty.

**Comment by digikata** [comment]
Hi @Shylock-Hg , not sure if this helps, but in the core rust fluvio crate, when you generate an async stream, (e.g. https://docs.rs/fluvio/latest/fluvio/consumer/struct.MultiplePartitionConsumer.html#method.stream)  the future delivers a stream that doesn't keep a reference to self of the MultiplePartitionConsumer.

**Comment by drc-infinyon** [comment]
Hey @Shylock-Hg are you done with this. Can you claim the bounty if you are please. :)

**Comment by drc-infinyon** [comment]
@Shylock-Hg - This ticket is resolved.

You need to claim the bounty based on this workflow: https://docs.algora.io/bounties/workflow - 

To claim a bounty on Github, navigate to your pull request that solves the bountied issue and add `/claim <ISSUE_NUMBER>` somewhere in the body of the PR.

**Comment by drc-infinyon** [comment]
@Shylock-Hg it is fixed now. I am paying the bounty.

**Comment by weirdo-github** [comment]
I'd like to work on this. I've submitted a PR here: https://github.com/fluvio-community/fluvio/pull/4672

Let me know if there's anything you'd like me to adjust.
