### ISSUE TITLE
Tracking Issues: Node Chat demo apps

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#386]
Completing [chat](https://github.com/infinyon/fluvio-demo-apps-node/tree/master/chat-app) for oss-1 release

**Comment by Ryanmtate** [comment]
Fixed by https://github.com/infinyon/fluvio-demo-apps-node/pull/4

**Comment by Ryanmtate** [comment]
https://github.com/infinyon/fluvio-website/pull/34 provides update for website chat example

**Comment by Ryanmtate** [comment]
https://github.com/infinyon/fluvio-demo-apps-node/pull/9 provides update for demo apps repository

**Comment by Ryanmtate** [comment]
closed by https://github.com/infinyon/fluvio-demo-apps-node/pull/11
