### ISSUE TITLE
 Have you considered continuing to support the kafka protocol? This is very conducive to migrating the system from kafka to fluvio

### ISSUE THREAD

**Issue by wking1986** [infinyon/fluvio#3870]
I would like to promote fluvio to our business scenarios, but currently we have used apache kafka in large quantities.

Have you considered continuing to support the kafka protocol? This is very conducive to migrating the system from kafka to fluvio.

**Comment by drc-infinyon** [comment]
Currently we have Kafka connectors. We focused on the stream processing and materialization functionality. However this question keeps coming up.

Could you please describe how you see this functioning. Are you looking for a Kafka compatible API in the Fluvio client?

How would it work in an implementation?
How are you going to use it?

**Comment by wking1986** [comment]
Thank you for your reply.
I understand that the kafka connector requires the existence of kafka, that is, it requires two components: kafka+fluvio, but fluvio can already replace the function of kafka, so we want to use only one component of fluvio, which can reduce operation and maintenance and resource costs.
Under this demand, fluvio needs to be compatible with kafka's protocol, so that neither the upstream nor the downstream needs to modify it, such as redpanda

**Comment by drc-infinyon** [comment]
Okay. I see what you are saying. You are looking at the protocol compatibility. Basically a mapping of the APIs, types, and more described here: https://kafka.apache.org/0100/protocol.html

I will shape an issue for Kafka compatibility. This is something that more people have asked for.

We prioritized building the stateful services capability that enables stream processing and materialization based on the signal from the community which is closed to a major release milestone.

Given that this ask is coming up more often. We will follow up on this soon.

**Comment by wking1986** [comment]
Great!
Our project is built using rust, so I really hope to have a stream processing platform based on rust (replacing kafka, pulsar, etc.). Thank you for your follow-up and attention. I hope this feature will be released soon.

**Comment by drc-infinyon** [comment]
It’s awesome to hear that you are using rust. I will look at prioritizing the Kafka protocol compatibility.

We are close to wrapping up our stateful service developer preview(Flink like functionality). A couple more releases to go. Once we get to that milestone we will have a capacity conversation to address this.

In the meantime if you have any specific requirements regarding the Kafka protocol compatibility relevant to your project - please let us know.

**Comment by wking1986** [comment]
Thank you very much for fluvio’s support！！！
