### ISSUE TITLE
[Bug]: Profile not created on cloud login

### ISSUE THREAD

**Issue by bitmage** [infinyon/fluvio#3875]
**What happened**
I log into the cli using `fluvio cloud login --use-oauth2`.  But no cloud profile is created/connected, and I can't access the cloud clusters because the email on them doesn't match the email in my profile.

On successful login I get:

```
Cluster does not exist. Please create a cluster first with `fluvio cloud cluster create` or through Infinyon Cloud UI.
```

I already have a cluster, but I can't delete it or interact with it because the associated email address isn't in my profile.

```
$ fluvio cloud cluster list  
ID                                           ACTIVE  STATE      VERSION  SPU_COUNT    
black-king-1c547d51fa5b6956a9b14aaf19b957fa  true    Installed  0.11.3   1

$ fluvio cloud cluster delete black-king-1c547d51fa5b6956a9b14aaf19b957fa  
Cluster email differs from profile email
```

```
$ cat ~/.fluvio/config  
version = "2.0"  
current_profile = "local"  
  
[profile.local]  
cluster = "local"  
  
[cluster.local]  
endpoint = "127.0.0.1:9003"  
use_spu_local_address = false  
  
[cluster.local.tls]  
tls_policy = "disabled"  
  
[cluster.local.metadata]  
installation = "local"
```

At this point in order to manually add the profile, it looks like I would need to know the web address for the cluster in Infineon Cloud, and I don't see any place to find that information via the web console or the CLI.  I also don't see any example profiles in the source code that contain this information.

Not sure how to proceed with connecting to the cluster at this point.

**Expected behavior**
[This documentation](https://www.fluvio.io/docs/get-started/cloud/) says that after running `fluvio cloud login` I should be able to run `fluvio profile current` and it should print `cloud`.  But I only see local listed, and no cloud configuration has been added to `~/.fluvio/config`.

**Describe the setup**
- Cloud
```
$ fluvio version
 Fluvio CLI                     : 0.11.4                                                           
 Fluvio CLI Arch                : x86_64-unknown-linux-musl                                        
 Fluvio CLI SHA256              : 13ba05c6ef4e37b8c7eb7ea6d703a7cacb5f82fbb31ac28c9b1b617f3884f25b 
 Fluvio Channel Frontend SHA256 : 13ba05c6ef4e37b8c7eb7ea6d703a7cacb5f82fbb31ac28c9b1b617f3884f25b 
 Fluvio Platform                : Not available (local)                                            
 Git Commit                     : 45c0089dbcd57123ba27470dd410c7b00b93e2ed                         
 OS Details                     : Manjaro Linux 23.1.3 (kernel 5.10.206-1-MANJARO)
```

**How to reproduce it (as minimally and precisely as possible)**
1. `fluvio cluster start --local`
2. `fluvio cloud login --use-oauth2`
3. `fluvio profile`

Prints 'local' for me.

I don't know whether this is because I created a local cluster first before I did cloud login.  I tried uninstalling fluvio, fvm, and removing the ~/.fluvio folder and then reinstalling fvm and fluvio.  That succeeded, but cloud login still does not produce a profile or allow me to connect to the cluster.

**Comment by digikata** [comment]
@bitmage Sorry you having trouble, we are taking a look at this right now.

**Comment by digikata** [comment]
It looks like you might be on a older version of our fluvio-cloud client. Can you try the following:

```
$ fvm install stable    # to re-download the latest stable versions
```

Then to either work with the cloud cluster, or delete it:
```
# to get a profile to work with your cloud cluster
$ fluvio cloud cluster sync   

# or with the latest stable, the delete command should work:
$ fluvio cloud cluster delete black-king-1c547d51fa5b6956a9b14aaf19b957fa
```

**Comment by bitmage** [comment]
```
$ fluvio cloud version
Infinyon Cloud CLI : 0.2.17
Git Commit       : fc8c84053cca6acf9448b88038b1bb4dd1fa6365
Sha256 hash      : 5a9ae8646cd0c6370482c22b9c0da3e3a796073c48d89773cd70586b00cab970
OS Details       : Linux 5.10.179-168.710.amzn2.aarch64 aarch64 GNU/Linux
Rustc Version    : 1.76.0 (07dca48 2024-02-04)
```

```
$ fvm install stable
info: Downloading (1/5): fluvio@0.11.4
info: Downloading (2/5): fluvio-cloud@0.2.17
info: Downloading (3/5): fluvio-run@0.11.4
info: Downloading (4/5): cdk@0.11.4
info: Downloading (5/5): smdk@0.11.4
done: Installed fluvio version 0.11.4
done: Now using fluvio version 0.11.4
```

I'm not sure what version numbers changed if any.  But it's working now:

```
~ $ fluvio cloud login --use-oauth2
A web browser has been opened at https://infinyon-cloud.us.auth0.com/activate?user_code=QPBF-RJZL.
Please proceed with authentication.
Successfully authenticated with Auth0
~ $ fluvio profile
no profile can be found
~ $ fluvio cloud cluster delete cold-king-07ff80b3a2e84f1e67626a66b258f722
Cluster deleted
~ $ fluvio cloud cluster delete blue-bush-5f7c184b2e71c59450d1744f35d6860f
Cluster deleted
~ $ fluvio cloud cluster create
Creating cluster...
Done!
Downloading cluster config
Switched to new profile
~ $ fluvio profile
muddy-meadow-2ffbf1428f5cef125d3df63be4449eec
```
