### ISSUE TITLE
[Bug]: Fluvio install k8s docs are out of date

### ISSUE THREAD

**Issue by SecretPocketCat** [infinyon/fluvio#3892]
**What happened**
The [multi instance k8s install docs](https://www.fluvio.io/docs/kubernetes/install/#install-multiple-instances-of-fluvio) start with running  
`fluvio cluster start --k8 --sys`  
which results in
`error: unexpected argument '--sys' found`

**Environment (please complete the following information):**
fluvio version
 Fluvio CLI                     : 0.11.5                                 
 Fluvio CLI Arch                : x86_64-unknown-linux-musl

**Comment by digikata** [comment]
Thanks @SecretPocketCat we appreciate you taking the time to file this issue! We'll take a look at it! or if you have suggested edits, you can send a PR directly to the fluvio-website repo too https://github.com/infinyon/fluvio-website/tree/master/content/docs/kubernetes

**Comment by SecretPocketCat** [comment]
Sorry for creating the issue here - I somehow missed the website repo and thought that bit was not public.  

I'm afraid I'm not really familiar with how the `sys` chart is supposed to work so I don't really know what the docs should say.

**Comment by drc-infinyon** [comment]
No worries @SecretPocketCat I will take a look at this with @digikata and figure out what needs to change.

**Comment by digikata** [comment]
Docs updated at https://fluvio.io/docs/kubernetes/install/

**Comment by ajhunyady** [comment]
@SecretPocketCat can you please let us know if the documentation is adequate for your use case?
https://fluvio.io/docs/kubernetes/install/

**Comment by SecretPocketCat** [comment]
@ajhunyady I encountered this by chance, I had an issue with something else. If the commands are valid, then it's fine with me 🙂
