### ISSUE TITLE
Replace makefiles with cargo-make build configuration

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#390]
We've had success in other repositories using `cargo-make`, I think we should standardize that and use it here as well. One leading motivation is the better support for cross-platform builds, e.g. setting environment variables only when building on a specific platform.

Re-scoping for this issue: Take all common task logic from our Github Actions (CI) and put it into cargo-make Makefiles.

**Comment by sehz** [comment]
move to alpha.  will migrate some of the makefile in opportunity matter

**Comment by nacardin** [comment]
Investigate modularization cargo make files to achieve better isolation

**Comment by sehz** [comment]
closing as we are not moving to `cargo make` since it is not build tool
