### ISSUE TITLE
[Bug]: Fluvio installation failed on GCP/Ubuntu due to lack of unzip

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#3906]
**What happened**
Fluvio installation script fails  on GCP/Ubuntu

**Expected behavior**
Installation should work on any Linux

**Describe the setup**
Open source Fluvio

**How to reproduce it (as minimally and precisely as possible)**
1.  Provision Gcp Ubuntu 6.5 running X86 or any Linux but don't install unzip
2. run installation script: `curl -fsS https://hub.infinyon.cloud/install/install.sh | bash`

**Log output**
```
curl -fsS https://hub.infinyon.cloud/install/install.sh | bash
☁️  Downloading fluvio version manager, fvm
   target arch x86_64-unknown-linux-musl
main: line 56: unzip: command not found
```

**Environment (please complete the following information):**
- OS: [Linux]
- Fluvio Version [0.11.15]

**Comment by sehz** [comment]
Installing unzip using ` sudo apt-get install unzip`  fixed the installation issue.

**Comment by sehz** [comment]
We should probably use either `tar` or `gzip` for Unix

**Comment by digikata** [comment]
Need for zip tar or gzip removed from install.sh (serving fvm from the standard artifact locations instead of gh now).
