### ISSUE TITLE
investigate faster file performance

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#391]
Lots of good [hints](https://www.evanjones.ca/durability-filesystem.html) on improving file performances.  Some thing we should try
- pre-allocate blocks for write

**Comment by sehz** [comment]
@digikata, what do you think about this?

**Comment by digikata** [comment]
I'll take a look and see what can be done

**Comment by digikata** [comment]
Also an interesting reference

https://tanelpoder.com/posts/11m-iops-with-10-ssds-on-amd-threadripper-pro-workstation/
