### ISSUE TITLE
fluvio installation failure on ubuntu

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#3925]
It relies on unzip command

```
curl -fsS https://hub.infinyon.cloud/install/install.sh | bash
☁️  Downloading fluvio version manager, fvm
   target arch aarch64-unknown-linux-musl
main: line 56: unzip: command not found
```

**Comment by digikata** [comment]
hub server updated, caching was holding the old version of install.sh, prod deploy ci was reported successful when deploy did not occur (fixed), the latest version does not require unzip

verified w/ `curl -fsS https://hub.infinyon.cloud/install/install.sh | grep zip`
