### ISSUE TITLE
Custom CA / Self-signed Certificates for Connectors

### ISSUE THREAD

**Issue by pinkforest** [infinyon/fluvio#3944]
For connectors when these use TLS outbound

Should we push them to vault somewhere or is there some provider e.g. in cloud to put them in and pull from ?

e.g.: where either CA root or self-signed crt is in PKCS#10/12

First needs to be added somewhere some way e.g.

$ fluvio certs add ca my-ca my-org-ca.crt

$ fluvio certs del ca my-ca

$ fluvio certs update ca my-ca my-org-ca.crt

$ fluvio certs add cert my-self-sign my-self-signed.crt

And then there needs to be trust established e.g. under connectors

$ fluvio connectors trust cert my-self-signed

Currently the only option is to get cert of public CA which may or may not be in root cert store given PKI impl default stores

**Comment by sehz** [comment]
Self signed certs are only should be used while deployment.   There are many ways to get certs like [Let's Encrypt](https://letsencrypt.org) or use certs from tools like Vault or cloud providers.

**Comment by pinkforest** [comment]
Yeah true it's just with some govt entities / enterprises just have less than ideal proprietary stuff

guess can just give them "String" for injecting PEM trust chain in those cases
