### ISSUE TITLE
mirroring: add authentication for remote (edge) nodes to the SC

### ISSUE THREAD

**Issue by digikata** [infinyon/fluvio#3971]
- reuse existing tls auth infrastructure if possible (likely possible)
- add metadata for edge identity label as part of the certificate

**Comment by fraidev** [comment]
https://github.com/infinyon/fluvio/pull/4016
https://github.com/infinyon/fluvio/pull/4017
https://github.com/infinyon/fluvio/pull/4021
https://github.com/infinyon/fluvio/pull/4022
https://github.com/infinyon/fluvio/pull/4024

Cover it
