### ISSUE TITLE
mirroring: remote mirrored topic should be read-only for local changes

### ISSUE THREAD

**Issue by digikata** [infinyon/fluvio#3973]
- regular accesses to remote (edge) cluster should not be able to modify mirror topics installed by the home cluster
- only the home cluster can change mirror topic configurations

**Comment by fraidev** [comment]
How to change a topic configuration?

**Comment by sehz** [comment]
so can use type permission check.  only home cluster is allowed

**Comment by fraidev** [comment]
I mean, what is changeable in a topic configuration?

**Comment by fraidev** [comment]
https://github.com/infinyon/fluvio/pull/4046 should cover it
