### ISSUE TITLE
[Enahancement]: Add BASE OFFSET to `show partition list`

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/fluvio#3975]
When there is a short retention time, the records are pruned from the beginning of the stream. Users need a way to identify the "base offset" so they identify if their applications may have missed records if they were offline for extended periods of time.

Add BASE to `show partition list` for better visibility:

```bash
$ show partition list
  TOPIC         PARTITION  LEADER  REPLICAS  RESOLUTION  SIZE       BASE       HW          LEO         LRS         FOLLOWER OFFSETS     
  metrics       0          0       []        Online      987.2 MB   124433223  1480618310  1480618310  1480618310  0                 []

**Comment by vaibhawvipul** [comment]
I would like to work on this if no one has taken it up already.

**Comment by drc-infinyon** [comment]
@vaibhawvipul that’s awesome thank you. If you need any clarification or support, let us know.

**Comment by PanGan21** [comment]
Hi @drc-infinyon . Any directions on how to get the `base_offset`? Should it be added on the `PartitionSpec` or it can be retrieved easier?

**Comment by PanGan21** [comment]
Hi. I did some effort implementing this on #4059  but some pipelines are failing. I would appreciate a quick a look on it 🙂

**Comment by EstebanBorai** [comment]
@digikata I think we can close this as completed?
