### ISSUE TITLE
[Bug]: Create same topic for the 2nd time returns timeout instead of err (breaks my script)

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/fluvio#398]
$ fluvio topic create rust-mysql-cdc
topic "rust-mysql-cdc" created
$ fluvio topic create rust-mysql-cdc
Error: 
   0: Fluvio client error
   1: Fluvio socket error
   2: time out in send and request: 3

Location:
   src/cli/src/root_cli.rs:133

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by sehz** [comment]
related to #373.
