### ISSUE TITLE
Fluvio cluster install --local does not install system chart

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#399]
This is a rough edge from cleaning up the installer. The kubernetes installer will install the system chart for you if you don't have it, but on a local installation we still depend on the system chart being installed on minikube for our metadata store. If you don't have that set up, the CLI will panic and the SC will go into a CPU-hungry log loop. We should fix this by moving the remaining installation logic into the cluster crate and integrating things nicely.

**Comment by sehz** [comment]
related to: #335
