### ISSUE TITLE
[Bug]: Error while connecting to local cluster

### ISSUE THREAD

**Issue by jayeshpk1** [infinyon/fluvio#4055]
**What happened**
Getting this error
called `Result::unwrap()` on an `Err` value: Config error: Config has no active profile

**Expected behavior**
Should work

**Describe the setup**
- local fluvios
- What version of Fluvio are you using? 0.11.9-dev (local)

**How to reproduce it (as minimally and precisely as possible)**
1. run the below code

**Environment (please complete the following information):**
- OS: Ubuntu 22 WLS 
- Fluvio Version 0.11.9-dev (local)

Code
```
use async_std::stream::StreamExt;
use chrono::Local;
use fluvio::metadata::topic::TopicSpec;
use fluvio::{consumer::ConsumerConfigExtBuilder, Fluvio, RecordKey};

const TOPIC_NAME: &str = "hello-rust";
const PARTITION_NUM: u32 = 0;
const PARTITIONS: u32 = 1;
const REPLICAS: u32 = 1;

/// This is an example of a basic Fluvio workflow in Rust
///
/// 1. Establish a connection to the Fluvio cluster
/// 2. Create a topic to store data in
/// 3. Create a producer and send some bytes
/// 4. Create a consumer, and stream the data back
#[async_std::main]
async fn main() {
   // Connect to Fluvio cluster
   let fluvio = Fluvio::connect().await.unwrap();

   // Create a topic
   let admin = fluvio.admin().await;
   let topic_spec = TopicSpec::new_computed(PARTITIONS, REPLICAS, None);
   let _topic_create = admin
       .create(TOPIC_NAME.to_string(), false, topic_spec)
       .await;

   // Create a record
   let record = format!("Hello World! - Time is {}", Local::now().to_rfc2822());

   // Produce to a topic
   let producer = fluvio::producer(TOPIC_NAME).await.unwrap();
   producer.send(RecordKey::NULL, record).await.unwrap();
   // Fluvio batches outgoing records by default, so flush producer to ensure all records are sent
   producer.flush().await.unwrap();

   // Consume last record from topic
   let fluvio = Fluvio::connect().await.unwrap();
   let config = ConsumerConfigExtBuilder::default()
       .topic(TOPIC_NAME)
       .partition(PARTITION_NUM)
       .offset_start(fluvio::Offset::from_end(1))
       .build()
       .unwrap();

   let mut stream = fluvio.consumer_with_config(config).await.unwrap();
   if let Some(Ok(record)) = stream.next().await {
       let string = String::from_utf8_lossy(record.value());
       println!("{}", string);
   }
}
```

**Comment by morenol** [comment]
Hey, could you provide more information about: 

1) how did you started the fluvio cluster
2) how did you run the above code
3) can you access the fluvio cluster from the CLI? 'fluvio topic list' works?

**Comment by jayeshpk1** [comment]
1. fluvio cluster start
2. using "cargo run". I created a sample rust application using the example shown in documentation
3. yes. below is the output.
 NAME              TYPE      PARTITIONS  REPLICAS  RETENTION TIME  COMPRESSION  DEDUPLICATION  STATUS
 REASON
  quickstart-topic  computed  1           1         7days           any          none           resolution::provisioned
  my-topic          computed  1           1         7days           any          none           resolution::provisioned

**Comment by ajhunyady** [comment]
The client is looking for a profile file to get information about the cluster.
You should have the following file on the system where the client is running:

```
ls ~/.fluvio/config 
```

can you confirm that the file is available?

**Comment by jayeshpk1** [comment]
Thank you so much. I was running cargo run from windows command line where configuration directory is missing.

**Comment by ajhunyady** [comment]
You can copy/paste it manually.

**Comment by ajhunyady** [comment]
@jayeshpk1, feel free to close if you think this issue has been resolved.
