### ISSUE TITLE
Offset management

### ISSUE THREAD

**Issue by jayeshpk1** [infinyon/fluvio#4089]
I would like to retrieve and start processing from the last offset commit. Is there an API to retrieve the latest offset for a topic/consumerid/partition combination in a distributed environment?

**Comment by digikata** [comment]
Hi @jayeshpk1,  

I'm not 100% clear of what you need. You can start processing from the latest offset from the API by requesting an `Offset::end()` or often you want `Offset::from_end(1)` in the consumer config.  

Or you can process tracking offsets for a given consumer. The documentation for that kind of offset management is here:

https://www.fluvio.io/docs/concepts/producer-consumer/#auto-offset-management
https://www.fluvio.io/docs/concepts/producer-consumer/#manual-offset-management

**Comment by ajhunyady** [comment]
Closing, as no additional action needed.
