### ISSUE TITLE
better developer support for produce config

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#4099]
Make it easier to diagnose producer config while developing client.

- Enable `debug` derive in the TopicProducerConfig
- Add accessor to properties.  Currently they are not public so can't access config once created.

And expose, topic and config in the `TopicProducer`

**Comment by diogopontual** [comment]
Hello @sehz ... I am trying to fix this issue, to get closer to the Fluvio codebase.

Question: Should I bypass the partitioner field?

**Comment by sehz** [comment]
Yes, you can skip `partitioner` field in the debug

**Comment by diogopontual** [comment]
Hello @sehz, just checking if this is the expected result:

![image](https://github.com/user-attachments/assets/77de4917-c94b-44f9-8f51-42693b1c02cb)


![image](https://github.com/user-attachments/assets/50a84a8c-8da9-4e20-b8ac-649d4f1b5c23)

**Comment by sehz** [comment]
perfect!

**Comment by diogopontual** [comment]
I'm going to take out a ton of println! that I did. And create the PR.

**Comment by diogopontual** [comment]
![image](https://github.com/user-attachments/assets/83f0fff4-264f-4bfa-905e-bc1bdb8365e6)

**Comment by ajhunyady** [comment]
Nice work @diogopontual! Thank you for your contribution.

**Comment by ajhunyady** [comment]
@digikata any suggestions?

**Comment by digikata** [comment]
@diogopontual    this issue might be an interesting next issue if you're looking for more practice

https://github.com/infinyon/fluvio/issues/3968
