### ISSUE TITLE
Crate lib-cargo-crate brings in an old version rustls

### ISSUE THREAD

**Issue by nacardin** [infinyon/fluvio#4106]
Consider replacing `lib-cargo-crate`

```
❯ cargo tree --invert rustls@0.21.12
rustls v0.21.12
├── hyper-rustls v0.24.2
│   └── reqwest v0.11.27
│       └── crates_io_api v0.8.2
│           └── lib-cargo-crate v0.2.2
│               └── smartmodule-development-kit v0.0.0 (/home/nacardin/Sources/fluvio/crates/smartmodule-development-kit)
├── reqwest v0.11.27 (*)
└── tokio-rustls v0.24.1
    ├── hyper-rustls v0.24.2 (*)
    └── reqwest v0.11.27 (*)
```

**Comment by morenol** [comment]
Maybe we could try to fork/bump it here? https://github.com/chevdor/cargo-crate/blob/d662167dae92c4421711835fb5b3672162aa20c3/lib/Cargo.toml#L10

**Comment by nacardin** [comment]
> Maybe we could try to fork/bump it here? https://github.com/chevdor/cargo-crate/blob/d662167dae92c4421711835fb5b3672162aa20c3/lib/Cargo.toml#L10

Submitted PR https://github.com/chevdor/cargo-crate/pull/4

**Comment by chevdor** [comment]
Thanks for the PR, CI is running

**Comment by chevdor** [comment]
[v0.2.4](https://crates.io/crates/cargo-crate) is published.
