### ISSUE TITLE
add `fluvio cluster upgrade` subcommand to handle just the version (with a `--force` for ci testing)

### ISSUE THREAD

**Issue by digikata** [infinyon/fluvio#4136]
Use case:
- `fluvio cluster start`
- add cluster data
- `fluvio cluster shutdown`
- upgrade to new fluvio cli version
- `fluvio cluster upgrade` # mark new version
- `fluvio cluster resume` # should succeed

**Comment by fraidev** [comment]
https://github.com/infinyon/fluvio/pull/4138 solves it
