### ISSUE TITLE
`fluvio cluster upgrade` add extended logic for upgrade of metadata when it changes

### ISSUE THREAD

**Issue by digikata** [infinyon/fluvio#4137]
`fluvio cluster upgrade` should update local cluster metadata storage data so that a `fluvio cluster resume` with a the current of fluvio will run and be compatible

Currently common cases for this are handled, but this issue is to cover more intense cases with larger changes (which would also require extra handling w/ k8s)

**Comment by fraidev** [comment]
With https://github.com/infinyon/fluvio/pull/4138 we're checking first if we can read all the metadata, if we can, we can also update them.
