### ISSUE TITLE
[Bug]: Guidelines after bash installation isn't accurate..

### ISSUE THREAD

**Issue by ArnavK-09** [infinyon/fluvio#4142]
**What happened**
I attempted to install Fluvio on GitHub Codespaces and ran the specified command multiple times, but it did not work.

![image](https://github.com/user-attachments/assets/9311436d-47df-48b4-b2fc-641889111417)

Although, a command hidden in long guidelines (not highlighted) worked somehow...

![image](https://github.com/user-attachments/assets/a97c2c91-1502-448d-a3d1-eb2d36f8d948)

**Expected behavior**
Expected, command to setup things to use cli

**Describe the setup**
- Local
```
 Fluvio CLI                     : 0.11.11                                                          
 Fluvio CLI Arch                : x86_64-unknown-linux-musl                                        
 Fluvio CLI SHA256              : dbec9acb5104fd1c71c802b2873e453d21807ed932554f3e1eb423a2695fde6a 
 Fluvio Channel Frontend SHA256 : dbec9acb5104fd1c71c802b2873e453d21807ed932554f3e1eb423a2695fde6a 
 Fluvio Platform                : 0.11.11 (local)                                                  
 Git Commit                     : 98cfc21314c93d4c2898edc9e2160f280622be21                         
 OS Details                     : Debian GNU/Linux 12 (kernel 6.5.0-1022-azure)```
```
**How to reproduce it (as minimally and precisely as possible)**
1. Open GitHub code space. I used https://github.com/ArnavK-09/rust-for-codespaces
2. Follow https://www.fluvio.io/sdf/getting-started

**Environment (please complete the following information):**
 Fluvio CLI Arch                : x86_64-unknown-linux-musl                                        
 Fluvio Platform                : 0.11.11 (local)                                                  
 Git Commit                     : 98cfc21314c93d4c2898edc9e2160f280622be21                         
 OS Details                     : Debian GNU/Linux 12 (kernel 6.5.0-1022-azure)n`

**Additional context**
This issue with reference to https://ptb.discord.com/channels/695712741381636168/695731077406392360/1274430446318391357

**Comment by digikata** [comment]
To clarify these instructions:

`source ${HOME}/.fvm/env` is required if you want `fvm` and `fluvio` and other binaries in the path for your current shell. But this will need to be repeated every time you start a new shell, unless you make the other change:

`echo "source ${HOME}/.fvm/env" >> .bashrc` is required if you want the path to be accessible by default when you start a new shell. (if you shell is not `bash`, you might add to some other shell config file (eg. on macos if you're using zsh `.zshrc` instead).

**Comment by ajhunyady** [comment]
@digikata, our detection algorithm does not do an good job for all OS systems.
We should improve the script to add a `<your startup script>` instead of `.bash` or `.zshrc` for cases that we don't know.

**Comment by morenol** [comment]
We also should mention that in order to make efective `echo "source ${HOME}/.fvm/env" >> .bashrc` we need to create a new bash instance

**Comment by sehz** [comment]
so `echo` worked.  Just that user is not aware that you need to refresh `.bashrc` or re-login.

**Comment by ArnavK-09** [comment]
> so last line `echo source` worked.  Just that user is not aware that you need to refresh `.bashrc` or re-login.  

Umm, cli should've guided, but ty
