### ISSUE TITLE
Checking for max batch size  ignores compression

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#4161]
Steps to reproduce:

1) create a topic:  `fluvio topic create   test`
2) try to send large json greater than 128k but reduces to 4k.
`fluvio produce test --file large.json --raw  --linger 0ms --compression  zstd`

This result in error:
```
the given record is larger than the buffer max_size (16384 bytes). Try increasing the producer batch size or reducing the record size enabling a compression algorithm
```

even thought compressed record is small 4k

**Comment by digikata** [comment]
It might be a good to also modify the batching flow logic a little too in correcting this bug?

If the compressed record is larger than the batch size, send the accumulated batch (w/o the record), and then if the compressed record is still larger than the batch size, send it individually, and start an new batch.
