### ISSUE TITLE
[Bug]: Unexpected character while parsing helm version number

### ISSUE THREAD

**Issue by robbje** [infinyon/fluvio#4165]
While trying to install fluvio on a k8 cluster, I encountered the following error:
```
[admin@k8s ~]$ RUST_LOG=debug fluvio cluster start --k8
[...]
    📝 Checking Helm -                                                                                                                                                        2024-09-04T08:23:07.694033Z DEBUG install_fluvio{namespace="default"}:preflight_check{fix=true}: fluvio_command: Executing> helm version
unexpected character '.' while parsing major version number
```

```
[admin@k8s ~]$ helm version --short
3.15.4+gfa9efb0

[admin@k8s ~]$ fluvio version
 Fluvio CLI                     : 0.11.11
 Fluvio CLI Arch                : x86_64-unknown-linux-musl
 Fluvio CLI SHA256              : dbec9acb5104fd1c71c802b2873e453d21807ed932554f3e1eb423a2695fde6a
 Fluvio Channel Frontend SHA256 : dbec9acb5104fd1c71c802b2873e453d21807ed932554f3e1eb423a2695fde6a
 Fluvio Platform                : Not available
 Git Commit                     : 98cfc21314c93d4c2898edc9e2160f280622be21
```

I had a quick glance at the code.

https://github.com/infinyon/fluvio-helm/blob/main/src/lib.rs#L365

The line here seems to skip the first character, which would then return ".15.4+gfa9efb0" as version string, which causes the error to surface in `semver::Version::parse()`. I would have sent a PR to not skip the first character, but this seems so odd and may break things I'm not aware of (I'm sure people are using this without issues? Maybe the code intends to skip a leading 'v'?)
and there are also no tests. I know this is a different crate. If you would like me to report the issue there instead, let me know.

**Comment by digikata** [comment]
Hi @robbje thanks for the bug report, we're taking a look

**Comment by sehz** [comment]
Yes, it is intended to skip `v` so version would be compatible with SemVer.   It would be good to add tests here.  Contribution is welcome

**Comment by digikata** [comment]
We run ci/cd tests on every checking that verify `fluvio cluster start --k8`, and it seems operate so we need maybe more information about your helm?   It seems like my local `helm version --short` reports `v3.15.0+gc4e37b3`

**Comment by robbje** [comment]
I installed helm from the official Fedora 40 repository. Very curious.

**Comment by digikata** [comment]
I have checked both the brew macos helm 0.15.4 release, as well as the helm project github binaries for Linux x86_64, from here https://github.com/helm/helm/releases/tag/v3.15.4.  They both report version with a leading `v`.   I would guess that the `v` is removed or not applied somewhere along the way of the Fedora RPM package.  

For fluvio, modified logic to check for a leading 'v' before removing it would be a welcome contrib if you're still interested in submitting a PR.

**Comment by sehz** [comment]
office doc says all helm version should have `v`:  https://helm.sh/docs/helm/helm_version/

**Comment by digikata** [comment]
Thanks @robbje for the PR!
