### ISSUE TITLE
[Bug]: Typo in Connector docs

### ISSUE THREAD

**Issue by Borderliner** [infinyon/fluvio#4180]
**What happened**
It says `sdk` while it means to say `cdk` in the first line of the description.

[Connector docs](https://www.fluvio.io/docs/connectors/cdk/)

**Comment by ajhunyady** [comment]
Good catch @Borderliner. Can you please issue a pull request for a fix in https://github.com/infinyon/fluvio-docs

**Comment by Borderliner** [comment]
Sure.
