### ISSUE TITLE
Typo in docker example

### ISSUE THREAD

**Issue by sagoez** [infinyon/fluvio#4232]
When running the example I get:

```bash
Unable to find plugin 'fluvio-topics'. Make sure it is installed in "/Users/samuel/.fluvio/extensions".
```

The CLI doc referes to `fluvio topic list` without the `s`. Let me know if you want me to create quick MR to fix this.

**Comment by sehz** [comment]
Done.  Updated in the doc

**Comment by ajhunyady** [comment]
Thanks for reporting @sagoez
