### ISSUE TITLE
Support producing to specific partition

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#4234]
With mirroring, we need ability to specify produce to specific partition rather than default random.

```
$ fluvio produce --partition <partition_number> my__topic
```

This will send to data to specific partition.

This parallel existing consume command:
```
$ fluvio consume  -p, --partition <integer>
          Partition id
```

**Comment by ajhunyady** [comment]
We should map to the partition name.

**Comment by sehz** [comment]
We don't have named partition yet

**Comment by fraidev** [comment]
Fixed by https://github.com/infinyon/fluvio/pull/4241
