### ISSUE TITLE
How does Fluvio self-update work when CLI is installed via Cargo?

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#430]
Right now, our installation flow is looking like it will be a cross-platform bash script that downloads the appropriate platform's build of the Fluvio CLI and installs it into `~/.fluvio/bin/`. This is also where all bin plugins will be installed. To self-update, the Fluvio CLI simply downloads a new version of itself and overwrites the file in `~/.fluvio/bin/`, but what happens to the copy in `~/.cargo/bin`? This is an open question that we should discuss in this issue.

**Comment by sehz** [comment]
One thought is that we treat these two binaries as separately.  Since this is installed thru `cargo`, developer is assumed to know what they were doing.   This is no different from installing from package manager and trying to install directly from project site.

**Comment by sehz** [comment]
It is unlikely to we will do something about this.  Re-open situation changes.
