### ISSUE TITLE
[Bug]: Fluvio without `openssl` but `rustls` does not compile

### ISSUE THREAD

**Issue by TheSamsa** [infinyon/fluvio#4304]
**What happened**
Using fluvio as dependency like this: `fluvio = { version = "0.24.0", features = ["compress", "rustls"], default-features = false }`
Fails to build complaining `IoError` not existent in (fluvio) `src/config/tls.rs:247`

**Expected behavior**
I expect it to build the same as I would use the `openssl` feature

**Describe the setup**
- I am using a local fluvio running in a docker container

**How to reproduce it (as minimally and precisely as possible)**
1. `cargo init fluvio-rustls`
2. `cd fluvio-rustls`
3. `cargo add fluvio -F rustls,compress --no-default-features`
4. `cargo build`

**Log output**
It is rather an error output while building:
```
error[E0412]: cannot find type `IoError` in this scope
   --> ../.cargo/registry/src/index.crates.io-6f17d22bba15001f/fluvio-0.24.0/src/config/tls.rs:247:26
    |
247 |             type Error = IoError;
    |                          ^^^^^^^ not found in this scope
    |
help: there is an enum variant `crate::dataplane::types::config_file::LoadConfigError::IoError` and 6 others; try using the variant's enum
    |
247 |             type Error = crate::dataplane::types::config_file::LoadConfigError;
    |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
247 |             type Error = fluvio_compression::CompressionError;
    |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
247 |             type Error = fluvio_protocol::types::config_file::LoadConfigError;
    |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
247 |             type Error = fluvio_smartmodule::dataplane::core::types::config_file::LoadConfigError;
    |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      and 2 other candidates
```

**Environment (please complete the following information):**
output of `fluvio version`:
```
 Fluvio CLI                     : 0.13.0
 Fluvio CLI Arch                : x86_64-unknown-linux-musl
 Fluvio CLI SHA256              : 786e2fa4d98215b0359e490ca00a413fa9e7a3d59663712b49f15eb6686b73d1
 Fluvio Channel Frontend SHA256 : 786e2fa4d98215b0359e490ca00a413fa9e7a3d59663712b49f15eb6686b73d1
 Fluvio Platform                : 0.13.0 (docker)
 Git Commit                     : 91c742927645f3790b3c7092e9fb08d5c6e3b6fd
 OS Details                     : Linux Mint 22 (kernel 6.8.0-51-generic)
```

**Optional Debugging:**
Another trace which may be useful is re-running the command with RUST_LOG specified at a higher level
`RUST_LOG=info fluvio ...` or `RUST_LOG=debug fluvio ...`

**Additional context**
I looked into https://github.com/infinyon/fluvio/blob/4e6db82697c43e8ab13e3d763799b4e43852dd36/crates/fluvio/src/config/tls.rs#L247 and changed the line to `type Error = anyhow::Error;`, it did build. (sometimes not, but it probably had something to do with build cache etc)

Do I miss something, is this even intended to run without openssl?

**Comment by ajhunyady** [comment]
@TheSamsa, thanks for tracking this down. Can you please submit a PR with the possible fix for the team to analyze?

**Comment by TheSamsa** [comment]
Sure, when Inget back home I'll create a PR.

-------- Ursprüngliche Nachricht --------
Am 18.12.24 15:49 um A.J. Hunyady schrieb :

**Comment by TheSamsa** [comment]
@ajhunyady I provided a PR with the changed file.
The 'crate-version' check failed, do I have to bump the `crates/fluvio/Cargo.toml` version for this?
Sorry for the stupid question, this was just a quick write down since my time is limited today.

**Comment by morenol** [comment]
Yes, bump the version on fluvio crate plase
