### ISSUE TITLE
Bug: flv_tls_proxy::rustls: error handshaking

### ISSUE THREAD

**Issue by nacardin** [infinyon/fluvio#440]
Error in CI (Kubernetes cluster test) log:
`ERROR flv_tls_proxy::rustls: error handshaking: tls handshake eof from source: 10.1.0.4:41636`

See https://github.com/infinyon/fluvio/runs/1322564303?check_suite_focus=true#step:12:396

**Comment by sehz** [comment]
This happens after connection is closed.  It is expected
