### ISSUE TITLE
Merge `spu` and `custom-spu` terms

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#463]
So I'm documenting the CLI, and wanted to pitch an idea. Right now we have these commands:

```
fluvio spu list                  List custom & managed SPUs
fluivo custom-spu register       Create custom SPU
fluvio custom-spu unregister     Delete custom SPU
fluvio custom-spu list           List custom SPUs
```

I was thinking we could lay them out like this instead:

```
fluvio spu register                    Register a custom (out-of-band) SPU
fluvio spu unregister                  Unregister a custom (out-of-band) SPU
fluvio spu list [--managed|--custom]   List all SPUs (or only --managed or --custom)
```

To make things consistent, we should find all instances of SPU vs Custom SPU and consolidate them to SPU.

- [x] Rename in CLI
~Rename in Documentation~ covered by (#63)
~Rename in ControlPlane API~ future issue (#538)
~Rename in Admin API~ future issue (#538)
~Rename in SC~ future issue (#538)

**Comment by sehz** [comment]
I think this makes sense.  Instead of creating another type, this allow us to consolidate.   In that case, we should change
- Doc/CLI
- ControlPlane API
- Admin API
- SC controller

implementations to conform to this

**Comment by nicholastmosher** [comment]
Remaining work was moved to issues for the future.
