### ISSUE TITLE
CLI: change create/delete command to register/unregister

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#5]
1)  Change Spu Group column" NAME" as left justified.
2)  Change create/delete command custom-spu to "register/unregister"

**Comment by djKooks** [comment]
@sehz hope to check out this one~is it okay?

**Comment by sehz** [comment]
yes, it is still good first issue

**Comment by djKooks** [comment]
@sehz I'm currently looking on this part.

Seems function name is also defined to `create/delete` on custom-spu (I'm looking on `src/cli/src/spu/custom/...`). Would it be better to change function name either?

**Comment by sehz** [comment]
Yes, that make sense

**Comment by Ryanmtate** [comment]
I have a draft PR open for this, https://github.com/infinyon/fluvio/pull/27

**Comment by sehz** [comment]
Separating into 2 issue.
