### ISSUE TITLE
[bug] `fluvio cluster start --develop --local` gives client error: 409 Conflict

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#541]
Gives the following error:

```
❯ target/debug/fluvio cluster start --develop --local
Performing pre-flight checks
Error:
   0: Failed to install Fluvio locally
   1: Kubernetes client error
   2: client error: 409 Conflict
```

This may be reproduced by the following:

- On a fresh system:
- Start minikube
- Run minikube tunnel
- Run `fluvio cluster start --develop --local`
- Manually kill the local component processes with `pkill fluvio`
- Run `fluvio cluster start --develop --local` again
- See error

To fix it:

- Run `fluvio cluster delete`
- Run `fluvio cluster start --develop --local`

**Comment by sehz** [comment]
@nicholastmosher does this still happens on master?

**Comment by nicholastmosher** [comment]
I just checked, it does still happen on master.

<img width="490" alt="image" src="https://user-images.githubusercontent.com/4210949/102658073-dad66f80-4144-11eb-867b-8219a3668302.png">

**Comment by sehz** [comment]
In the local cluster, user is responsible for managing (stop/restart) SPU because they are unmanaged SPU.  However, we should still prevent them from starting cluster if it is already started.  This required: https://github.com/infinyon/fluvio/issues/541.

**Comment by nicholastmosher** [comment]
Scope update: Add a suggestion for the user to use `fluvio cluster delete --local` and retry

**Comment by nicholastmosher** [comment]
After a bit of investigating here I don't see an easy way to check whether a local cluster is running or not. Manually I would do something like `ps aux | grep fluvio sc` but I don't know if there is an easy/reliable programmatic way to do that. There is the procfs crate but it seems rather low level and when I started reading about it it definitely felt like I was getting into a rabbit hole. I'm open to opinions on this but I think that this issue could be closed by just adding the suggestion.
