### ISSUE TITLE
Cluster installer should use K8 cluster IP, if running inside K8 with Pod Config

### ISSUE THREAD

**Issue by nacardin** [infinyon/fluvio#558]
Currently `discover_sc_address` fails with a minikube install if the tunnel is not up. It returns `None` as if it didn't find the service. If the `flv-sc-public` service is up and only has a cluster IP, and we are running in the same K8 cluster, we should use the cluster IP.

**Comment by sehz** [comment]
Add option to `cluster` installer to use cluster_ip address instead of waiting for LB address
