### ISSUE TITLE
CLI: `fluvio profile view` should print consistently like other outputs (table, yaml, json)

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#608]
Right now, `fluvio profile view` deserializes the TOML file from `~/.fluvio/config` and prints the Rust-Debug formatted version of it to the screen. This is inconsistent with our other commands and also technically reveals the inner code structure (e.g. the names of internal structs are printed). We should print it as a table by default with options to print as yaml, toml, or json

**Comment by ajhunyady** [comment]
There should also be an indicator of the default profile as part of the profile view. @nicholastmosher can you mockup a table format to discuss fields?

**Comment by nicholastmosher** [comment]
Ok, so our old `profile view` looked like this:

```
Config {
    version: "2.0",
    current_profile: Some(
        "minikube",
    ),
    profile: {
        "minikube": Profile {
            cluster: "minikube",
            topic: None,
            partition: None,
        },
    },
    cluster: {
        "minikube": FluvioConfig {
            addr: "10.111.134.218:9003",
            tls: Disabled,
        },
    },
    client_id: None,
}
```

I'm trying to think of how to preserve the most important info in a table. I'm thinking something like this:

```
$ fluvio profile view
  PROFILE      CLUSTER       ADDRESS                  TLS
* minikube     minikube      10.111.134.218:9003      Disabled
  local        local         localhost:9003           Anonymous
  cloud        cloud         https://cloud.fluvio.io  Verified
```

The `*` before the PROFILE column represents the "current" profile. This resembles the familiar `git branch` printout:

```
$ git branch
  minikube
  package-ci
* profile-delete
  profile-tls
```

**Comment by ajhunyady** [comment]
This is great! 

@nicholastmosher  can we also add a `describe` command similar to:
```
$ fluvio topic describe chat-app-users
 Name                    :  chat-app-users 
 Type                    :  computed 
 Partition Count         :  1 
 Replication Factor      :  1 
 Ignore Rack Assignment  :  false 
 Status                  :  provisioned 
 Reason                  :   
 -----------------         
``` 
The purpose of this command would be to show all elements in the JSON printout, including topic, partition. It could also show the certificate if desired.
