### ISSUE TITLE
CLI: `fluvio profile view` should not print TLS certificates to screen

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#609]
Currently, executing `fluvio profile view` may be very noisy because any inline TLS certificates are printed directly to the screen, resulting in large base64 blobs of text that fill up the screen and make things hard to read. The ultimate goal of this issue is to **improve readability of `fluvio profile view`**.

I see two action items which we may take to improve this. We can do one or both of these to improve readability.

1) We could override the implementation of the `Debug` or `Display` trait of the config object so that any inline TLS certificates are simply omitted or truncated, e.g. `<hidden>`.

2) We could make all client code use path-based TLS certs rather than inline certs by convention. Here are the pros and cons I see:
- Pro: This would match the way other similar tools work, e.g. `kubectl config view` shows paths to TLS certs rather than printing them inline.
- Pro: This would make it easier to interact directly with the TLS certificate for other purposes such as debugging. If the TLS certs are in their own files, we can interact with them via curl or openssl, for example.
- Con: We may need to sometimes infer where to place certificates and make sure they are named so they don't clash. E.g. if we do `fluvio cloud login`, we need a strategy for writing the TLS certs to a place where they are uniquely discoverable for that profile.

I think we should apply both of these actions. We don't need to do them all at once or anything but let's discuss.

---

After some discussion, we have decided to pursue 1) as the action item for this issue. If we decide it is necessary in the future, we may revisit point 2).

Action item:

- [ ] Prevent Inline TLS certificate from printing to stdout by overriding `Display` and `Debug` to print inline TLS as `<hidden>`.

**Comment by ajhunyady** [comment]
1) mixes implementation and behavior. My feedback is on behavior. We should have a consistent `profile view` that shows the profile in a table format. One way to solve the certificate issue is to display in `details` command.

**Comment by ajhunyady** [comment]
There should also be an indicator of the `default` profile as part of the `profile view`

**Comment by nacardin** [comment]
We no longer have `fluvio profile view`
