### ISSUE TITLE
Max truncation for the text output in the CLI is too short

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#634]
CLI truncates text output for each record to be: 256:
```
255 of 271: {"sid":"fb7e2971d989070361c30d825bf6a853a406916e","payload":{"kind":"Request","message":
```

Instead put limit when only when environment variable is set

**Comment by sehz** [comment]
updated proposal, set default limit to 16k for text.  if text exceed limit, add `...`

**Comment by ajhunyady** [comment]
ok, but don't add the stuff at the beginning of the line.

**Comment by sehz** [comment]
k
