### ISSUE TITLE
Enable Cluster Install to use cluster_ip instead of LB address

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#635]
Currently, Cluster Installer uses LB's address.  Instead we should have option to use `cluster_ip` address which will avoid installer to wait for LB to produce external IP address which make take while to execute it.

**Comment by nacardin** [comment]
Duplicate of https://github.com/infinyon/fluvio/issues/558 ?

**Comment by sehz** [comment]
Yup.

**Comment by sehz** [comment]
closing in favor of #558
