### ISSUE TITLE
Test: Add test statistics

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#64]
Add statistic for [test runner](https://github.com/infinyon/fluvio/blob/master/doc/TEST.md).

For each run, test runner produce a message.   We need to capture test statistics for each run.
Add basic statistics (mean, max, stdev) for producer message generation.

Possibly candidate for statistic library:  https://bheisler.github.io/criterion.rs/criterion/index.html.
There might be more in crates.io:

We might also leverage the library to generate graph:
* generate gg plot
* generate pdf

**Comment by sehz** [comment]
@vijaylaxmid This could be interested to you

**Comment by tjtelan** [comment]
Test statistics are included in `flv-test` today utilizing [HdrHistogram](https://github.com/HdrHistogram/HdrHistogram_rust)

Simple graph generation, and raw data export is complete. But the code is being integrated in pieces. This progress is tracked by #1380
