### ISSUE TITLE
Creating a consumer via fluvio::consumer results in PartitionNotFound 

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#645]
Using [`fluvio::consume`](https://github.com/infinyon/fluvio/blob/769ba7a8b3f72230abf753c91425ed315e18a58c/src/client/src/lib.rs#L158) results in `PartitionNotFound` errors for topics that already exist however this doesn't happen if you use the exact same code from within `fluvio::consume`.

This for example fails:

```rust
use fluvio::Offset;
const TOPIC: &str = "my-topic";

#[async_std::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let consumer = fluvio::consumer(TOPIC, 0).await?;
    let _ = consumer.stream(Offset::beginning()).await?;

    Ok(())
}
```
However this succeeds:

```rust
use fluvio::Offset;
const TOPIC: &str = "my-topic";

#[async_std::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {

    let client = fluvio::Fluvio::connect().await?;
    let consumer = client.partition_consumer(TOPIC, 0).await?;
    let _ = consumer.stream(Offset::beginning()).await?;

    Ok(())
}
```
I've failed at finding any tools to help show when a given variable is dropped and the deconstructor is called. But the same error happens if you do the following:
```rust
let consumer = fluvio::Fluvio::connect().await?.partition_consumer(TOPIC, 0).await?;
```
I think this happens because `Fluvio::connect().await?` returns a `Fluvio` instance and `partition_consumer` uses it but returns a `PartitionConsumer`, I'm pretty sure a little mini scope is created here to the effect of:
```rust
let consumer = {
    let client = fluvio::Fluvio::connect().await?;
    client.partition_consumer(TOPIC, 0).await?
};
```
`client` is dropped at the ending of the `}`

This is all a long winded way of saying "I think that when the Fluvio client is dropped, it breaks things".

**Comment by simlay** [comment]
Looks like the [`Drop for MultiplexerSocket`](https://github.com/infinyon/fluvio-socket/blob/master/crates/socket/src/multiplexing.rs#L78-L83) is part of the culprit.

**Comment by sehz** [comment]
This is same problem as #655
