### ISSUE TITLE
[Bug]: Echo example causes `PartitionNotFound` error

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#655]
**What happened**
I ran `cargo run --bin echo` and instead of seeing the records being produced and consumed, I saw

```
Sending record 0
Error: Partition not found: echo-0
```

Even using `FLV_METADATA_WAIT=10000` does not help

```
❯ FLV_METADATA_WAIT=10000 cargo run --bin echo
Sending record 0
Error: Partition not found: echo-0
```

This is what I see for topics and partitions

```
❯ fluvio topic list
 NAME       TYPE      PARTITIONS  REPLICAS  IGNORE-RACK  STATUS                   REASON
 echo       computed      1          1                   resolution::provisioned
 example    computed      1          1                   resolution::provisioned
 greetings  computed      1          1                   resolution::provisioned

❯ fluvio partition list
 TOPIC      PARTITION  LEADER  REPLICAS  RESOLUTION  HW  LEO  LSR  FOLLOWER OFFSETS
 example    0          0       []        Online      0   0    0    []
 greetings  0          0       []        Online      7   7    0    []
 echo       0          0       []        Online      0   0    0    []
```

**Expected behavior**
I expected to see the producer printing each record it sends like the documentation says

```
Sending record 0
Got record: Hello Fluvio 0!
Sending record 1
Got record: Hello Fluvio 1!
Sending record 2
Got record: Hello Fluvio 2!
Sending record 3
Got record: Hello Fluvio 3!
Sending record 4
Got record: Hello Fluvio 4!
Sending record 5
Got record: Hello Fluvio 5!
Sending record 6
Got record: Hello Fluvio 6!
Sending record 7
Got record: Hello Fluvio 7!
Sending record 8
Got record: Hello Fluvio 8!
Sending record 9
Got record: Hello Fluvio 9!
Got record: Done!
```

**Describe the setup**
- Are you using a local Fluvio install? Minikube? Fluvio Cloud?
  - Fluvio Cloud
- What version of Fluvio are you using? `fluvio version`

```
Fluvio CLI      : 0.6.0-rc.3
Fluvio Platform : 0.6.0-rc.3
Git Commit      : 769ba7a8b3f72230abf753c91425ed315e18a58c
OS Details      : Darwin 19.6.0 x86_64
Rustc Version   : 1.48.0 (7eac88a 2020-11-16)
```

**How to reproduce it (as minimally and precisely as possible)**
- Connect to Fluvio Cluster
- `fluvio topic create echo`
- `cargo run --bin echo`
- See output described above

**Log output**

**Environment (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - Fluvio Version [e.g. 22] see above
 - Minikube version (if used): use `minikube version`
```
minikube version: v1.16.0
commit: 9f1e482427589ff8451c4723b6ba53bb9742fbb1
```
 - Kubernetes version: use `kubectl version`
```
Client Version: v1.20.1
Server Version: v1.19.6
```

**Comment by sehz** [comment]
was able to reproduce it.  seems like it is similar to smoke-test but doesn't work.  hmm.
