### ISSUE TITLE
add progress status indicator when installing cluster

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#662]
Start with brand new minikube:

Some of these steps may take 10-60 seconds.  While doing that, there is indicator what is doing.  We should put loading indicator after each steps

```
fluvio cluster start --local
Performing pre-flight checks
✅ ok: Supported helm version is installed
✅ ok: Supported kubernetes version is installed
✅ ok: Kubernetes config is loadable
✅ ok: Fluvio system charts are installed
```

**Comment by sehz** [comment]
as part of loading indicator

**Comment by morenol** [comment]
Closed ny https://github.com/infinyon/fluvio/pull/1627
