### ISSUE TITLE
Add CLI regression tests - for `profile` and `partition` subcommands

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#667]
Add regression testing for subcommands and arguments. This should be unit-test level. E.g. test that a given argument string is successfully parsed into a specific instance of a StructOpt.

An example of such a test might look like this:

```rust
#[test]
fn test_profile_view {
    let command = &["fluvio", "profile", "view"];
    let opt = RootOpt::from_iter(command);
    assert!(matches!(opt.cmd, RootCmd::Profile(ProfileCmd::View(_))));
}
```

For this issue, we want basic coverage of the following commands:

- [ ] `fluvio produce`
  - Test all argument options
- [ ] `fluvio consume`
  - Test all argument options
- [ ] `fluvio partition list`
- [ ] `fluvio profile view`
- [ ] `fluvio profile switch`
- [ ] `fluvio profile rename`

In a future issue we can revisit our CLI testing to be more thorough

**Comment by tjtelan** [comment]
This issue is now tracking the addition of the `fluvio partition` and `fluvio profile` subcommands into the cli smoke tests
