### ISSUE TITLE
CLI Design: `fluvio produce`

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#676]
It feels like there is some good opportunity to improve the `fluvio produce` CLI options. Right now there are several ways to do one thing, and the arguments that are available are not really composable. I want to gather some requirements about what capabilities the `fluivo produce` command should have, and what information it should make available to the user.

## Requirements

Please check the boxes below to indicate your thoughts on each requirement:

1) I should be able to provide input from `stdin` or from named files
- This would allow me to pipe each line of some command output as a record
- E.g. `rg "hello" | fluvio produce my-topic [some args]`
  - Each discovered line containing "hello" would be produced as a record
2) When providing input from named files, I should be able to use `xargs`
- E.g. when taking filenames to produce from, all trailing arguments should be accepted
- E.g. `cat record-names.txt | grep ".toml" | xargs fluvio produce my-topic [some args]`
  - Expands to something like `fluvio produce my-topic -f one.toml two.toml three.toml four.toml`
3) I should be able to take the specified input and produce it line-by-line or as a single record
4) I should be able to choose whether to observe confirmation (via e.g. stdout) after each record that is produced
- Today, we observe confirmation with an `Ok!` printout after each record or file is produced
- When observing confirmation, it should be structured in a script-friendly way
  - E.g. when producing one line at a time, confirmation output should be each line produced
  - E.g. when producing one file at a time, confirmation output should be the filename of each file produced
5) I should be able to view human-friendly output without interfering with script-friendly output
- Script-friendly output should go to stdout
- Human-friendly output should go to stderr

Consumer concerns:

1) I should be able to gracefully deal with non-text files, i.e. binary
- Does it make sense to attempt to render non-text content to a terminal?
   - aj: we don't have a good understanding of this use case. Maybe we should remove until users ask. @sehz?
- Should we provide a mechanism to predictably place binary content into files?
  - aj: same as above, I suggest we defer under we understand the use case. @sehz?
  - E.g. instead of attempting to print a `file.jpg` to the terminal, simply place it into a `file-000001.jpg` file.
  - Maybe we can define an argument that takes a file-template-string, e.g `--template=image-{{OFFSET}}.jpg`

@infinyon/dev are there any more requirements you'd like to see here? I will begin writing a proposed interface that hopefully will meet these requirements

---

## Proposed Interface

Here, I'll list out the specific arguments that I think would fulfill each use case above, and demonstrate some example usages and expected output.

```
fluvio-produce

USAGE:
  fluvio produce <topic> [FLAGS] [OPTIONS]

FLAGS:
  --lines   -l    Produces input line-by-line, delimited by newline '\n'
  --verbose -v    Prints each line or each filename as it is produced

OPTIONS:
  --partition -p         Specifies the partition to produce records to [default: 0]
  --file -f   <file...>  Specifies one or more files to read as input
```

### Examples:

Here are a few examples of how I'd expect this to behave:

- Produce one file as one record (multiline record)

```
$ fluvio produce my-topic -f my-file.txt
or
$ fluvio produce my-topic < my-file.txt
```

- Produce one file as one-record-per-line

```
$ fluvio produce my-topic -l -f my-file.txt
or
$ fluvio produce my-topic -l < my-file.txt
```

- Produce multiple files, each file as one record, and print each file as it is produced

```
$ fluvio produce my-topic -v -f one.txt two.txt three.txt
one.txt
two.txt
three.txt
```

- Produce multiple files, each line of each file as one record, and print each line as it is produced

```
$ fluvio produce my-topic -v -l -f one.txt two.txt three.txt
one.txt: Hello one-A
one.txt: Hello one-B
two.txt: Hello two-A
two.txt: Hello two-B
three.txt: Hello three-A
three.txt: Hello three-B
```

- Download a file via curl, then produce that file as a record

```
$ curl -fsS https://packages.fluvio.io/v1/install.sh | fluvio produce my-topic
```

- Read a list of filenames, then produce each file that was named

```
$ cat list.txt | xargs fluvio produce my-topic -f
```

**Comment by ajhunyady** [comment]
@nicholastmosher  I marked the ones I understood with 👍, for the rest I have question or no comment:
2. I'm not familiar with `xargs` and others should provide feedback on this (ok with me).
3.  what constitutes an `end-of-line` ?
4. added `-v` (for verbose).

**Comment by nicholastmosher** [comment]
My apologies, I think we were editing the description at the same time... Do you want to try again?

**Comment by nicholastmosher** [comment]
I will give a better description of what `xargs` does. Suppose you have a bunch of files that you want to produce, and you have a list file that has the names of each of those files you'd like to produce. Something like this:

```
$ ls
A.txt
B.txt
C.txt
D.txt
...
list.txt

$ cat list.txt
A.txt
C.txt
E.txt
...
```

If I wanted to select each of the files that was named in `list.txt`, I could use xargs. xargs will take each line that it receives on `stdin` and it will execute a command, placing each input line as a new argument to that command.

For example we could run

```
cat list.txt | xargs echo
```

which would expand to 

```
echo A.txt C.txt E.txt
```

and therefore you would see this be printed

```
A.txt C.txt E.txt
```

If we wanted to instead produce these few files to Fluvio, we could use `xargs` to create an invocation like this:

```
cat list.txt | xargs fluvio produce my-topic -f
```

Which would expand to this:

```
fluvio produce my-topic -f A.txt C.txt E.txt
```

So the only thing that we need to do in order to make the `fluvio-produce` command compatible with `xargs` is to make our "name your files" argument (in the examples, I used `-f` for this) able to accept multiple arguments at once. This typically means that it will be placed last. This is easy to do, in `StructOpt` it simply amounts to creating a struct field that takes a `Vec`.

**Comment by nacardin** [comment]
stderr should be reserved for errors and warnings messages. Why does a script require a different output than a human?

**Comment by nicholastmosher** [comment]
Stderr is quite often used for output other than warnings and errors. For example, when you run `cargo build`,

```
cargo build
   Compiling fluvio-cloud v0.1.2 (/Users/nick/infinyon/fluvio-cloud-ops/crates/cloud-cli)
   Compiling fluvio-cloud-deployment-operator v0.1.0 (/Users/nick/infinyon/fluvio-cloud-ops/crates/deployment-operator)
   Compiling fluvio-cloud-web-api v0.1.0 (/Users/nick/infinyon/fluvio-cloud-ops/crates/web-api)
```

all of the `Compiling` output is printed on stderr, even though it is clearly not itself an error.

As for why it is useful: For scripts it can be very handy to have structured information readily available on a particular output. For example, we could define that `stdout` will print the name of each file that is produced as it is produced, while `stderr` is used for any additional pretty user-interface printout. That way, scripts may pipe the stdout output of `fluvio produce` to, say, remember which files have already been produced to a topic, without being messed up by the human-facing printouts.

**Comment by sehz** [comment]
https://www.howtogeek.com/435903/what-are-stdin-stdout-and-stderr-on-linux/

**Comment by nicholastmosher** [comment]
@infinyon/dev please make a comment indicating whether, for each requirement (1-5), you believe that it is needed, if it is a nice-to-have, or if you disagree that it should be considered. You can copy the format of my answer below:

Requirements:
1) I should be able to provide input from stdin or from named files
  - Need
2) When providing input from named files, I should be able to use `xargs`
  - Need
3) I should be able to take the specified input and produce it line-by-line or as a single record
  - Need
4) I should be able to choose whether to observe confirmation (via e.g. stdout) after each record that is produced
  - Need
5) I should be able to view human-friendly output without interfering with script-friendly output
  - Need

**Comment by nicholastmosher** [comment]
One potential future use case that @nacardin mentioned is that if we produce files by name (e.g. `fluvio produce my-topic -f my-file.txt`), we might want to add metadata to the new record that describes the origin filename.

**Comment by nacardin** [comment]
I should be able to provide input from stdin or from named files
**need**
When providing input from named files, I should be able to use xargs
**nice-to-have**
I should be able to take the specified input and produce it line-by-line or as a single record
**need**
I should be able to choose whether to observe confirmation (via e.g. stdout) after each record that is produced
**need, we could use either `-q` (quiet) to hide progress messages or `-v <level>` (verbosity) to determine level of detail to show**
I should be able to view human-friendly output without interfering with script-friendly output
**need**

**Comment by sehz** [comment]
Questions
- Does it kept existing other argument?
- What happen if lines is binary?

We should make it flexible to support different separator other than just `\n`'

**Comment by nicholastmosher** [comment]
> Does it kept existing other argument?

My plan with these changes would be to get rid of `--record-per-line` and `--record-file`

> What happens if lines is binary?

The `--lines` argument would be intended just for textual input. If you omit `--lines`, then the entire input (stdin or file) will be sent as one record.

> We should make it flexible to support different separator other than just `\n`

I agree that could be desirable. We could potentially add an argument like `--lines='\r\n'`, or perhaps alternate flags such as `--lines-crlf`

**Comment by sehz** [comment]
This breaks existing CLI `produce` which assume console as primary way to input.

**Comment by nicholastmosher** [comment]
Superseded by new key/value CLI coming in #830
