### ISSUE TITLE
Client Library Metadata

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#683]
Right now we support two clients (Rust and Node) but this will soon change. The tooling documented for [Python](#494) seems deceptively easy (I'm sure it's not that easy).

Anyway, one thing we should keep track of sooner rather than later is some metadata about the client library. A user agent if you will. I'm not sure what all we want to track from the users of fluvio but the following will help us trouble shoot, customer support, and know which client libraries are used most:

* base client language - Right now and because rust uses the LLVM backend, this will be `rust` 
* base client version - the version of whatever the base client is when it's the default base client, it'll just be whatever version came from https://crates.io/crates/fluvio
* client library language - node, rust (dunno how to deal with this duplicate), python, etc.
* client library version - Whatever the build in the [package manager has it published](https://www.npmjs.com/package/@fluvio/client)
* Target OS
* Target Architecture

This should all be optional for connecting to a fluvio cluster.

Given that we plan to use rust as our base client for everything, I think we will be able to do all of this at compile time in when we distribute the rust compiled binaries for the various clients.

I'm not sure what the [`Versions`](https://github.com/infinyon/fluvio/blob/a85e36a43d46677976de61584c20db9c38197e09/src/client/src/client/client.rs#L184-L187) struct is used for in the fluvio rust client but we may be able to leverage that.

Thoughts?

**Comment by nicholastmosher** [comment]
I like the idea of some kind of user-agent setting. I think that even though all of our language bindings will be written on top of Rust, we can provide an API for those bindings to establish their identity. We could have something like a `FluvioUserAgent` struct which is like a config that holds all of the information we want to collect about the client. This would be a field of `Fluvio` itself and have a default value that describes the Rust client library itself. However, we could add an API such that a language-bindings client could add its own identifying information to that. Something like `fluvio.configure_user_agent(FluvioUserAgent)` which is called by the language client when constructing the `Fluvio` Rust client handle. This would be totally transparent to the user, but it would result in us being able to add metadata to all of the requests made by that client.
