### ISSUE TITLE
[Bug]: CLI is silent when producing to non-existing topic

### ISSUE THREAD

**Issue by nacardin** [infinyon/fluvio#697]
When topic `mytopic` does not exist.
```
❯ fluvio produce mytopic
```
does not give any feedback until actually producing a record.

```
❯ fluvio version
Fluvio CLI      : 0.6.1
Fluvio Platform : 0.6.1
Git Commit      : 9f48ca7c14f39fda357932dff59ab9038ee55531
OS Details      : Linux 5.8.0-1017-aws x86_64 GNU/Linux
Rustc Version   : 1.49.0 (e1884a8 2020-12-29)
```

**Comment by ajhunyady** [comment]
We had quite a bit of discussion about this. By default the consumer is waiting for new messages, which seems reasonable but not all that intuitive. For new users it seems like something went wrong and the system hangs.

To main question is who is the user for this command? Is it always users or there could also be scripts?
I would assume, we expect users, in which case we should provide some level of feedback. Maybe read the HOL and say something to the extent "2345 message stored" then "Waiting for message".

At least that would give users a hint that they did no choose the right option if they want to read from some other offset.
@nicholastmosher  @nacardin @sehz @simlay Thoughts?

**Comment by nacardin** [comment]
> We had quite a bit of discussion about this, we all fell into the trap thinking that there is a bug in the system because we forgot to pass -B.
> By default the consumer is waiting for new messages, which seems reasonable but not all that intuitive. For new users it seems like something went wrong and the system hangs.
> 
> The main question is who is the user for this command? Is it always users or there could also be scripts?
> I would assume, we expect users, in which case we should provide some level of feedback. Maybe read the HOL and say something to the extent "2345 records stored" then "Waiting for new records... ".
> 
> At least that would give users a hint that they did no choose the right option if they want to read from some other offset.
> @nicholastmosher @nacardin @sehz @simlay Thoughts?

I agree, when consume is called by a user, it should indicate offset and that it is waiting for new records. Creating separate issue to discuss `consume` cli.
