### ISSUE TITLE
Rust Client: `fluvio.platform_version()` does not update when underlying cluster is upgraded

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#707]
I think that the `VersionedSerialSocket` (or some other related object) checks the cluster version on the first request exchanged with the cluster and then caches it. It is not noticeable if you continuously run `fluvio version` because it instantiates a new `Fluvio` Rust client object each time, but from the Rust client standpoint, if I have `fluvio: Fluvio` and I call `fluvio.platform_version()`, I would expect to always see an up-to-date version.

**Comment by sehz** [comment]
This would be only problem if same TCP connection is maintained during upgrade which is not possible

**Comment by nicholastmosher** [comment]
I suppose the expected behavior then would just be that the low-level client machinery should transparently handle reconnection, or the request should fail completely.

**Comment by sehz** [comment]
Yes

**Comment by nicholastmosher** [comment]
This seems like it would be closely related to https://github.com/infinyon/fluvio/issues/770. Linking so that we remember to re-visit this when that is done.
