### ISSUE TITLE
[Bug]: `fluvio install` fail if `~/.fluvio/` directory does not exist

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#718]
**What happened**

The `fluvio install` command reports an error if the `~/.fluvio/` directory does not exist

```
cargo run --bin fluvio -- install fluvio/fluvio-cloud
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `target/debug/fluvio install fluvio/fluvio-cloud`
🎣 Fetching latest version for package: fluvio/fluvio-cloud...
⏳ Downloading package with latest version: fluvio/fluvio-cloud:0.1.3...
🔑 Downloaded and verified package file
Error:
   0: Fluvio base directory not found
```

This should not happen via the regular curl | bash flow but we should fix it nonetheless.

**Expected behavior**
The `fluvio install` command should create the `~/.fluvio/` directory if it does not exist.

**How to reproduce it (as minimally and precisely as possible)**
1) `rm -rf ~/.fluvio`
2) `cargo run --bin fluvio -- install fluvio/fluvio-cloud`

**Comment by ajhunyady** [comment]
@nicholastmosher I ran into the same issue on Raspberry PI.
 The directory should be created by the fluvio binary rather than the installation script.
