### ISSUE TITLE
Rust Client: Add user-facing Admin API for common use-cases

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#726]
I have brought this up before but we never prioritized it, and I think it's getting close to time that we handle this. Right now, the only way to do things such as create a topic is via the `admin.create` API, which looks like this:

```rust
    let mut admin = fluvio::FluvioAdmin::connect().await?;
    admin.create(
        "foobar".to_string(),
        false,
        fluvio::metadata::topic::TopicSpec::new_computed(1, 1, None),
    ).await?;
```

There are a few problems with this:

1) The API exposes internal machinery, which means that changing anything about any internal Spec layout would break the public interface
2) From a user perspective, it is not at all clear that this is where to go in order to create a topic. We have talked about keeping our interfaces consistent, and while certain CLI commands have API equivalents (e.g. `fluvio produce` corresponds to `fluvio.topicProducer(...).send_record(...)`, we have no direct mapping of `fluvio topic create` onto any client API.

I believe that either of these problems on their own would be enough cause to rework this interface, but together I think it makes this urgent. As of now we have had at least one user report that they were unable to figure out how to create a topic via the Rust API and they had to resort to using `std::process::Command` to invoke the Fluvio CLI.

From `@warycat` on Discord:

```
let my_uuid = Uuid::new_v4();
let topic_id = format!("{}", my_uuid.to_simple());
Command::new("cargo")
    .args(&[
        "run",
        "--bin",
        "fluvio",
        "topic",
        "create",
        topic_id.as_str(),
    ])
    .output()
    .expect("Failed to execute command");
topic_id
```

> [2:15 AM] warycat: I can't figure out how to use the create function call.

Here are the commands from the CLI that I believe should have a direct Rust API equivalent:

- `fluvio topic create`
- `fluvio topic delete`
- `fluvio topic list`
- `fluvio partition list`

I think these should be added to the `Admin` api, and look approximately like this:

```rust
impl FluvioAdmin {
    pub async fn create_topic(&self, config: TopicConfig) -> Result<(), FluvioError> {}
    pub async fn delete_topic(&self, name: &str) -> Result<(), FluvioError> {}
    pub async fn list_topics(&self) -> Result<Vec<TopicInfo>, FluvioError> {}
    pub async fn list_partitions(&self) -> Result<Vec<PartitionInfo>, FluvioError> {}
}
```

For some new public data types `TopicConfig`, `TopicInfo`, and `PartitionInfo`.

Please let me know any feedback about this in the comments.

**Comment by nicholastmosher** [comment]
Related to https://github.com/infinyon/fluvio/issues/319

**Comment by warycat** [comment]
It will improve the usability of the api a lot. A common use case is to create a topic in server middleware, so an async api is preferred.

**Comment by sehz** [comment]
This feels like redundant and verbose version of API.

**Comment by simlay** [comment]
> This feels like redundant and verbose version of API.

It is a bit more verbose but the issue with this part of the API is that it's not very user friendly. Given that the CLI allows you do `fluvio topic list`, you'd expect a similar thing to with `admin.list_topics()` with the rust client. The same argument can be made about `create_topic`, with the cli there's some defaults that the user doesn't always need to know.

`fluvio topic create foobar` -> `admin.create_topic("foobar")`

**Comment by nicholastmosher** [comment]
> This feels like redundant and verbose version of API.

APIs that are similar are not always redundant. I pointed out several reasons that it would be a good idea to have the higher-level API:

- The higher-level API is intended to be easier to use by the Rust client users
- The naming of the high-level functions makes the functionality more discoverable
- The high-level APIs do not expose the `Spec` trait, meaning that it is _less coupled_ to the implementation, and we can change implementation details without breaking client code
- The point of an abstraction is to hide complexity. This is a perfect example of a good abstraction because we are simplifying the information that a client needs to know about in order to use this functionality.

**Comment by sehz** [comment]
Topic Spec and Status  is declarative definition of "Topic" for the Fluvio Platform.   Everything should be built around it.

**Comment by nicholastmosher** [comment]
Then perhaps instead of creating a new `TopicConfig` type, we could try to make a nicer API for `TopicSpec` so it is easier for people to construct it and use the create-topic API

**Comment by simlay** [comment]
After the discussion yesterday, I think a `TopicBuilder` (builder pattern) that gives a `TopicSpec` keeps current functionality and extends the UI of the API for what we want.

**Comment by nicholastmosher** [comment]
Yep. IMO, the key most important thing about this issue is to add special-purpose functions, i.e. `create_topic`. Something that makes it obvious how to do what they want. Right now we just have a `fn create<S>(...) where S: Into<AllCreatableSpec>`. This has a huge conceptual barrier to users, since nobody is going to know what qualifies for `Into<AllCreatableSpec>`. As the developers we know you can throw a `TopicSpec` at it, but there's no way to know that unless you dive into the source and look at what things implement `Into<AllCreatableSpec>`, so it is not a friendly API.

**Comment by sehz** [comment]
> Yep. IMO, the key most important thing about this issue is to add special-purpose functions, i.e. `create_topic`. Something that makes it obvious how to do what they want. Right now we just have a `fn create<S>(...) where S: Into<AllCreatableSpec>`. This has a huge conceptual barrier to users, since nobody is going to know what qualifies for `Into<AllCreatableSpec>`. As the developers we know you can throw a `TopicSpec` at it, but there's no way to know that unless you dive into the source and look at what things implement `Into<AllCreatableSpec>`, so it is not a friendly API.

That's just matter of documentation.  For example, Rust method such as "parse" is not straightforward because it can cover such big use cases because it is generic.  You don't find `parse_int` in the Rust library because it is not much more concise.  

Better way to deal is to as @simlay as suggested to create "builder" or "helper" to make it easier to compose.  For example: https://docs.rs/reqwest/0.11.0/reqwest/  improve `Hyper` api by allowing building request more concise way and allow chaining.    The client library should be focus on efficiency and generality much as possible.  We may need to build another client crates or features, extensions to allow more composable/high level API on top of the client library.  This is because, "higher" library can be opinionated and there probably more than one way to do it.
