### ISSUE TITLE
Ensure doc tests are run during CI

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#735]
We have had breaking API changes lately that caused doc tests to fail, but they were not picked up by CI. We need to make sure that our CI flow is actually running doc tests.

**Comment by tjtelan** [comment]
I added doc tests for both linux and mac hosts. They seem unstable and maybe even Ubuntu-specific. I can't get them to pass locally (Manjaro), but the Linux host has passed CI once. The MacOS doc tests fail in the same place.

**Comment by nicholastmosher** [comment]
This will be closed by #851
