### ISSUE TITLE
Install script should only install latest release version (rather than pre-release)

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#758]
Right now, our installer script (executed via `curl -fsS https://packages.fluvio.io/v1/install.sh | bash`) will install the latest pre-release version of fluvio that has been published. We want to update the package system so that it will only update to the latest full release version.

A pre-release is any version with additional information beyond the version triplet, as in `0.7.0-alpha.1`.

A release is any version that is _only_ a version triplet, as in `0.7.0`.

**Comment by sehz** [comment]
I thought this is done?

**Comment by nicholastmosher** [comment]
@sehz there were sort of 2 steps to this change. The first one was making `fluvio update` only use latest RELEASE version. Second step was making `curl .../install.sh | bash` script only use latest RELEASE. This will be closed when #812 is merged.
