### ISSUE TITLE
Create cluster integration test harness

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#759]
We need more tests in fluvio, and one of the best ways to encourage more tests is to make them easier to write. Currently it is very difficult to write integration tests because it requires setting up and tearing down the environment very precisely every time. If we create a test harness to do this for us, it should make this process easier.

I believe the test harness should be responsible for the following:

- Create a new namespace for each individual test to be run (note this will require running on Kubernetes)
- Install a Fluvio cluster in each test's namespace
- Populate a `config: FluvioConfig` with the cluster connection details for each test's cluster
- Instantiate a `fluvio: Fluvio` client via `Fluvio::connect_with_config(&config)` which will connect to the test's specific cluster
- Pass the `fluvio` client into the body of the test

We can use the `fluvio-cluster` crate to implement this setup, and we can write a procedural macro to hide these details from the test author. Let me illustrate what the non-proc-macro version might look like:

```rust
#[fluvio_future::test_async]
async fn test_create_topic() -> Result<(), ()> {
    let namespace: String = generate_namespace(); // May be UUID or pseudo-random unique english name
    let cluster_config: ClusterConfig = fluvio_cluster::ClusterConfig::builder()
        .namespace(&namespace)
        // .add_any_other_configurations()
        .build()?;
    let installer = ClusterInstaller::from_config(cluster_config)?;
    let status = installer.install_fluvio().await?;
    let fluvio_config = FluvioConfig::new(status.address);
    let fluvio = Fluvio::connect_with_config(&fluvio_config).await?;

    // Enter test body with `fluvio`
}
```

With the help of a procedural macro, we could clean that up to look like this instead:

```rust
#[fluvio_cluster::test]
async fn test_create_topic(fluvio: Fluvio) {
    // Test body
}
```

We could add any of the cluster builder options as arguments to the proc macro, such as:

```rust
#[fluvio_cluster::test(
    namespace = "...",
    image_tag = "...",
    chart_location = "...",
    chart_version = "...",
)]
```

@infinyon/dev I'd like to get your input as to whether any of the ideas here should be changed, added to, or whether you can see any potential problems with it. I have a few unresolved questions already:

- Should this harness live in `fluvio_cluster`? This could create a circular dependency if we added tests to the `fluvio` crate
- Would this harness allow tests to be run in parallel? At first glance it seems like that could work, but I'm not 100% sure
- (bikeshed) are there any other preferred names than `#[fluvio_cluster::test]`?
- Should we add a test timeout? (this could actually be pushed down into the cluster installer itself)

---

Update: This issue is too big to be its own action item, so I'm breaking it down into bite-sized pieces:

- [ ] Clean up test runner to use programmatic fluvio-cluster rather than using `fluvio cluster start` CLI (https://github.com/infinyon/fluvio/issues/774)
- [ ] Parameterize tests to run iteratively or using random data in order to increase confidence (https://github.com/infinyon/fluvio/issues/777)
- [ ] Create proc macros to minimize boilerplate from testing helper methods

**Comment by sehz** [comment]
Please see this issue: this: https://github.com/infinyon/fluvio/issues/566.

Existing smoke test need to be migrated to use this rather than one off.

**Comment by nicholastmosher** [comment]
I just thought of another open question: should we attempt to support a "local" cluster in the test harness? It seems to me that it would be very difficult to isolate individual tests on a local cluster, whereas on Kubernetes it seems almost trivial. For the first revision of this it may be good to scope it to kubernetes-only

**Comment by sehz** [comment]
Tests themselves should not care if it is running "local" or "k8".

**Comment by sehz** [comment]
need to support this: https://github.com/infinyon/fluvio/issues/30

**Comment by sehz** [comment]
@tjtelan Let's review and discuss how much of this goes into #566
