### ISSUE TITLE
Rust Client Reconnect on Network error

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#770]
With infinyon/fluvio-socket#22 disconnect events propagate to the client so we should take advantage of this for to auto reconnecting should the client be configured that way.

Let's default to not auto-reconnecting but make this a parameter (or maybe use a builder pattern).

**Comment by morenol** [comment]
Closed the producer part in https://github.com/infinyon/fluvio/pull/1724, the consumer part will be addressed with  https://github.com/infinyon/fluvio/issues/1514
