### ISSUE TITLE
CLI: Add animated spinner for commands that take a long time

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#772]
We should figure out which commands have the potential to hang for a long period of time and add an animated spinner so that users know that they should expect to wait for a little bit.

We can use a library like https://docs.rs/indicatif/0.15.0/indicatif/ to accomplish this

---

This is being tackled in multiple pieces:

- [ ] https://github.com/infinyon/fluvio/pull/1574

**Comment by nacardin** [comment]
Closed by 
https://github.com/infinyon/fluvio/issues/1635
https://github.com/infinyon/fluvio/issues/1636
