### ISSUE TITLE
[Bug]: Streaming consumer and producer freeze after some time

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#800]
**What happened**
When sending many records via the producer CLI and consuming them via streaming CLI, it will eventually reach a point where the producer and the consumer both appear to freeze.

**Expected behavior**
Producer and consumer should be able to continue producing and consuming records indefinitely

**Describe the setup**
- Fluvio on Minikube 1.16
- What version of Fluvio are you using? `fluvio version`

```
Fluvio CLI        : 0.7.0-alpha.5
Fluvio CLI SHA256 : 9b5387cd498928568d81797a204a0b21da6d5981468f0c6db2cab1aa6490fd09
Fluvio Platform   : Not available
Git Commit        : 146f35e7e4c6e6bae06bd2f8344a82e8efe060de
OS Details        : Darwin 11.2.1 (kernel 20.3.0)
Rustc Version     : 1.50.0 (cb75ad5 2021-02-10)
```

**How to reproduce it (as minimally and precisely as possible)**
1. Start with a fresh minikube installation and open minikube tunnel
2. Build the development docker images via `make minikube_image`
3. Start fluvio in development mode `cargo run --bin fluvio -- cluster start --develop`
4. Create a new topic `cargo run --bin fluvio -- topic create test1`
5. Start streaming CLI consumer `cargo run --bin fluvio -- consume test1 -B`
6. In a different terminal, start producing many records by producing a file line-by-line in a loop
 - `while true; do cargo run --bin fluvio -- produce test1 -l install.sh; done`
 - This is repeatedly producing each line of the `install.sh` file
7. Wait for awhile, eventually the producer will freeze and therefore so will the consumer. It seems like this may be caused by the producer.

**Log output**
[sc.log](https://github.com/infinyon/fluvio/files/6005958/sc.log)
[spu.log](https://github.com/infinyon/fluvio/files/6005961/spu.log)

**Environment (please complete the following information):**
 - OS: MacOS Big Sur
 - Kubernetes version: 1.19.6

**Comment by sehz** [comment]
Fails in the Linux after 32615 iteration in local test
```
Consuming 32612 (size 53084): was produced: 660A799082F9141A1BB3ECD8446B715D, was consumed: 660A799082F9141A1BB3ECD8446B715D
Consuming 32613 (size 1646 ): was produced: 2B75FF9176F3D450D646CE974A7A4D1E, was consumed: 2B75FF9176F3D450D646CE974A7A4D1E
Consuming 32614 (size 20765): was produced: DF5BD88CC7EA29947EB75A1E30A340D8, was consumed: DF5BD88CC7EA29947EB75A1E30A340D8
Consuming 32615 (size 57821): was produced: 914D2615226A265FC4E1FC2AD3F6AC7D, was consumed: 914D2615226A265FC4E1FC2AD3F6AC7D
```

However, SC and SPU still works.  However, `topic-bug` is not working:
```
flvd consume test-bug -B
topic 'test-bug/0': out of range
^Cubuntu@ip-172-31-20-82:~/fluvio$ flvd topic create t2
topic "t2" created
ubuntu@ip-172-31-20-82:~/fluvio$ flvd produce t2
hello world
Ok!
```

```
flvd partition list
 TOPIC     PARTITION  LEADER  REPLICAS  RESOLUTION  HW     LEO    LSR  FOLLOWER OFFSETS 
 test-bug  0          5001    []        Online      32643  32643  0    [] 
ls -la /tmp/spu_log_5001.log 
-rw-r--r-- 1 ubuntu docker 96961721 Feb 20 02:17 /tmp/spu_log_5001.log
```

**Comment by sehz** [comment]
Other topics works
```
ubuntu@ip-172-31-20-82:~/fluvio$ flvd consume t2 -B
hello world
```

**Comment by nicholastmosher** [comment]
This week I will check whether I can still reproduce this

**Comment by nicholastmosher** [comment]
@nicholastmosher check whether this is still present, check if it can be reproduced on Linux and Mac both

**Comment by tjtelan** [comment]
We want a test to run hourly when this is fixed

**Comment by sehz** [comment]
@nicholastmosher , can you confirm if this is still bug?

**Comment by sehz** [comment]
@nicholastmosher can you check if this is still problem in 0.9.5?

**Comment by nicholastmosher** [comment]
I ran this scenario again and let it run for 400,000 records with no problem whatsoever, so I'm going to close this.
