### ISSUE TITLE
Generate latest and nightly release

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#808]
To make it easier to consume fluvio, we should perform following development releases
- nightly (every night)
- latest (every commit)

Difference between regular and development release is that these release won't be added to Github releases.  The release should:
- Generate Fluvio binary
- Generate Helm Chart
- Generate Docker Image

**Comment by tjtelan** [comment]
It appears that most of this is complete.
* Latest docker images are built and pushed to Docker Hub (per commit)
* Nightly docker images are build and pushed to Docker Hub
* Helm charts are published (per commit)

The last piece missing are Fluvio binary per commit. Where should Fluvio development binaries be stored?
