### ISSUE TITLE
Add `fluvio cluster status` command to show "live" info about the active cluster

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#834]
Right now, a CLI user does not have a clear way to get information about the health of a cluster they are connected to. We want a `fluvio cluster status` command that will connect to the active cluster and print status information such as:

- The profile name of the active cluster
- The address of the cluster components (SC and SPUs)
- The uptime of the cluster
- The health status of the cluster

Brainstorming other possible info:
- The number of clients connected to the cluster?
- The utilization of the cluster?

Other suggestions for live info are welcome

**Comment by ajhunyady** [comment]
@nicholastmosher good thought on the 2 questions and we should have that as well. But let's make that phase 2.
We need this command soon as we need information about the health of the SC as well as the SPUs.
