### ISSUE TITLE
Add reference documentation for `fluvio-cloud`

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#835]
`fluvio cloud` is part of the standard Fluvio installation, but we do not have a section for it in the CLI reference documentation yet. We need to add a section showing its purpose and usage.

**Comment by ajhunyady** [comment]
@nicholastmosher we need to explain the pluggable system (listing, downloading, upgrading) and list `fluvio-cloud` as a module that's part of that. A potential blog could focus on building your own pluggable command.

**Comment by sehz** [comment]
Yes, scope of this task should be describe pluggable modules.  Fluvio Cloud CLI should be in Cloud doc
