### ISSUE TITLE
Write introductory blog post for Fluvio Key/Value records

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#836]
We need a short-and-sweet blog post introducing the new Key/Value capabilities of Fluvio. I'm thinking it can focus on two example cases:

- Producing key/value data from a delimited, one-record-per-line input
- Producing key/value data by selecting a key from JSON input data.

We should probably come up with one or two little play-scenarios about some toy application with key/value data and showing how to use it with Fluvio. Some ideas:
- chat messages in JSON, keyed by some kind of `conversation_id`
- simple "bank account transactions", using a format like `transaction_id=balance changes`
- library room-booking where each room has a key and each value is a reservation

**Comment by ajhunyady** [comment]
This is going to be a cool blog, I look forward to it.

**Comment by ajhunyady** [comment]
https://unsplash.com/photos/0sPFjdcRhko - cool pick for a bank transaction

**Comment by nicholastmosher** [comment]
Closed by https://github.com/infinyon/fluvio-website/pull/59
