### ISSUE TITLE
expose various SPU configuration to operator

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#839]
There are various SPU configuration that need to be overridden by operator during installation such as `flush` interval.

**Comment by nicholastmosher** [comment]
What other configuration options are there? Is there a way to turn this issue into a set of action items?

**Comment by sehz** [comment]
see: see:  https://github.com/infinyon/fluvio/blob/master/crates/fluvio-spu/src/config/spu_config.rs.
