### ISSUE TITLE
Investigate performance of producer in Rust client

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#840]
We have had some indications that the producer may not be performing as well as it might be able to. One potential cause of this is that it seems to reconnect to each leader every time a record is sent. We need to check if this is the cause of performance trouble and fix it if it is.

---

Right now, each time a producer sends a record, it opens a virtual socket, sends the record, and then closes that virtual socket, which is inefficient. We should keep the socket open for the lifetime of the producer object.

See https://github.com/infinyon/fluvio/blob/master/src/client/src/producer.rs#L53

**Comment by simlay** [comment]
Oh cool. I was noticing that the `send_record` call in python *felt* like it was taking a long time. Hopefully this will resolve the issue.
