### ISSUE TITLE
Implement Batch Producer

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#847]
Currently, produce api only sends one record at time which is not efficient.  We need to support batch produce which can send groups of record in a batch

Work needed to close this issue:
- [x] Implement batch producer in Rust client (#896)
- [x] Batch producer for Node (https://github.com/infinyon/fluvio-client-node/pull/79)
  - [x] Prerequisite: Implement tuples for node-bindgen (https://github.com/infinyon/node-bindgen/pull/142)
- [x] Batch producer for Python (infinyon/fluvio-client-python#15).
- ~Batch producer for Java~ (scope moved to initial Java client release)

**Comment by nicholastmosher** [comment]
Since we have yet to release the Java client, I propose that we move ahead with the batch producer on the other clients and then Java can simply support this feature upon its release.

**Comment by sehz** [comment]
Yes, we can close this issue
