### ISSUE TITLE
CLI: Check for Minikube tunnel when setting up K8 install for Minikube

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#87]
To improve installation process, check if Minikube tunnel is up for K8

First check if context is minikube
* user name is "minikube" in the kubeconfig)
  
If so, check if tunnel is up (need investigation, may depends on OS)
* if tunnel is not up, bring it up (we may add option to disable that)

**Comment by vijaylaxmid** [comment]
Part 1: First check if the context is `minikube`

The user name in kubeconfig can be extracted using the following command:

-  kubectl config view --minify -o jsonpath='{.users[].name}'

Part 2: If the tunnel is not up, bring it up

Which approach do you suggest is best suited to check tunnel status and bring it up.

1) Check if `minikube` process is running. `ps -ef | grep minikube` -> can use a library to get process by name https://docs.rs/sysinfo/0.3.19/sysinfo/trait.SystemExt.html#tymethod.get_process_by_name

2) Run “kubectl get svc” and check if external IP of flv-sc-public is pending - `kc get svc` -> check external IP

Also , Is it necessary to use `sudo` in `sudo nohup  minikube tunnel  > /tmp/tunnel.out 2> /tmp/tunnel.out &`?

**Comment by sehz** [comment]
For first part, you can use ```k8_config``` crates to check.  You can take look at ```cli::profile::k8```.

For tunnel, using kubectl get svc is ok. You should also perform:
```
minikube tunnel status

💣  error starting tunnel: error creating tunnel: another tunnel is already running, shut it down first: ID { Route: 10.96.0.0/12 -> 172.17.0.3, machineName: minikube, Pid: 14184 }

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
```

Use of ```sudo``` prob depends on platform.  You probably have to experiment to see if is is necessary

**Comment by vijaylaxmid** [comment]
@sehz, I see that we are running logic similar to `kubectl get svc` after the core app is installed. Do you suggest reusing that code to get the load balancer IP instead of manually running command and parsing the output for second part of the issue? 

https://github.com/infinyon/fluvio/blob/master/src/cli/src/cluster/install/k8.rs#L348

**Comment by sehz** [comment]
whole point is to see ensure minikube tunnel is up before we perform install.  Does performing ```minikube tunnel status``` not working?

**Comment by sehz** [comment]
close in favor of #314
