### ISSUE TITLE
Update doc tests to pass CI

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#873]
This is a prerequisite for #735. The tests should pass before they are included in CI on master.

New doc tests added in PR #851 are failing.

* Fail @ `fluvio-command` on the Ubuntu host
* Fail @ `fluvio-protocol-derive` on the MacOS host

It seems reasonable that the doc tests minimally pass on Linux, but I don't know what expectations we want to set for additionally passing the MacOS host.

**Comment by nicholastmosher** [comment]
Doctest fixes have been added to #851, closing this issue
