### ISSUE TITLE
investigate better installation experience with Helm

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#88]
Current pain points:
* Having to install helm
* Various error messages related to helm

Review how other projects have accomplished installation:
* [Istio](https://istio.io/latest/docs/setup/install/istioctl/)
* [gloo](https://docs.solo.io/gloo/latest/installation/gateway/kubernetes)
* [linkderd](https://linkerd.io/2/getting-started)

**Comment by nicholastmosher** [comment]
Once https://github.com/infinyon/fluvio/pull/721 lands, users of the CLI will not have any indication that the install process uses helm at all (it supresses helm stdout output). At that point shoud we call this closed?

**Comment by sehz** [comment]
Sounds good
