### ISSUE TITLE
Spike: Prototype Fluvio wasm client in browser, identify blockers

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#933]
There are many cases for which it would be excellent to have a browser-compatible wasm client for Fluvio. This would allow us to write applications that produce and consume directly from the client to the cluster. However, there are some challenges that we foresee that we don't know how difficult they will be to overcome. For example:

- Can we use websockets as a transparent drop-in replacement for TCP sockets?
- Can we share much of the client code we already have, or will we need a parallel crate just for wasm?
- Can we implement the same client interface using wasm-compatible APIs?

We should spend some time figuring out which potential problems are real, and which ones can be worked through at this time. We need to know whether we can accomplish this in a reasonable amount of time with the current ecosystem or whether we need to wait for more developments to catch up.

**Comment by simlay** [comment]
Currently depends on publishing:
* https://github.com/infinyon/wasm-timer/tree/fluvio-wasm-timer to crates.io as `fluvio-wasm-timer`.
* https://github.com/infinyon/future-aio/pull/63

**Comment by simlay** [comment]
This was closed in #1111.
