### ISSUE TITLE
Deprecate Fluvio platform hosting on mac

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#936]
The macOS builds fail way more often. Let's figure out how to test the macOS client but not hosting on macOS.

To do:

- Add docs on the website stating that cluster components are not officially supported for Mac
- Make sure that none of the Mac workflows are set to block any merging or other productivity

**Comment by tjtelan** [comment]
This was resolved when CI was split into multiple tiers. MacOS testing is in Tier 2 currently.
