### ISSUE TITLE
Save build artifacts from CI on Bors merge, use in release workflows

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#954]
Since we're now using Bors to run the CI workflow on merge commits that land in master, there is an opportunity to improve our release workflow. Right now, our flow is something like this:

- CI builds all of our crates and runs unit tests and cluster tests
- After CI passes, the commit is pushed to master
- When the commit is pushed to master, a separate release workflow builds all of the crates in release mode and publishes them

What we may be able to do instead is:

- When Bors runs CI, it builds all artifacts in release mode and tests them
- When CI passes, upload all of the release artifacts to a cache or store somewhere (GH releases?)
- When the new commit is pushed to master, the release workflows don't rebuild, they just publish artifacts from store

**Comment by tjtelan** [comment]
The process isn't quite as described but it is close and optimized for time.

We are building artifacts first, then having jobs depend on these artifacts. During PR merge, we promote release artifacts to a stable development tag, and then we can further promote the same artifacts to release.
