### ISSUE TITLE
Longevity test use case: Report CI status to Fluvio topic

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#956]
It would be nice if we had some long-running use-cases of Fluvio that we can use to make sure that a cluster is stable over a long period of time and between many different versions when upgrading. I think one good use-case could be to use a Fluvio client in our CI jobs to measure the timing and status of each job and report it to a topic. I think we could make a new plugin to achieve this, perhaps something like `fluvio-ci-reporter` that can have its own repo and Github Action script so we can pull it into the Fluvio CI job. I'm imagining it being a simple producer that just sends messages to a topic with data about the workflow run.

**Comment by tjtelan** [comment]
We want to run this workflow against the cloud environment
