### ISSUE TITLE
Add Producer API for sending keyless records

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#977]
After #965 lands, we will have deprecated the `TopicProducer::send_record` API, which allowed users to send a record without specifying a key for it. This API was deprecated because send_record accepted a partition number as one of the arguments, and we decided that for now, users should not be able to manually specify partitions.

This leaves a gap in our API for a particular use-case, which is sending a single record with no key. Without `send_record`, the only way to send a record with no key involves using the `send_all` function, which forces users to wrap their single record in some kind of iterator before passing it to the producer, e.g. like this:

```rust
producer.send_all(Some( (None, "My record data with no key") )).await?;
```

I believe that this is a workaround that we should not force users to deal with, as it is non-obvious and non-ergonomic. I think we need to introduce a new API method for the "single record with no key" use-case. I originally proposed a `send_keyless` API in #965 (discussion at https://github.com/infinyon/fluvio/pull/965#discussion_r615967714), but we decided to exclude it from that PR in order to discuss it more, which is what this issue is for.

For reference, the `send_keyless` API that I would like to introduce looks like this:

```rust
impl TopicProducer {
    pub async fn send_keyless<V>(&self, value: V) -> Result<(), FluvioError>
    where
        V: Into<Vec<u8>> { ... }
}
```

So the questions I would like to resolve in this discussion are:

1) Do we believe that a new API to fill this use-case is necessary? (I believe it is),
2) Is there a different API that better serves this use-case (I have not thought of one)?
3) Are we happy with the name `send_keyless` or would we prefer something else?

I think it makes sense to put a timeline on this. If nobody has any strong reasons why we should NOT introduce this API, I would like to add this issue to our roadmap as an action item by this Wednesday (4/21/21) to give enough time to ship it with the `0.7.4` release this Thursday.

---

# Discussion Results

After debating the API, we've decided to implement the following:

```rust
pub struct RecordKey(RecordKeyInner);

impl RecordKey {
    pub const NULL: Self = Self(RecordKeyInner::Null);
}

enum RecordKeyInner {
    Null,
    Key(RecordData),
}

impl<K: Into<Vec<u8>>> From<K> for RecordKey {
    fn from(k: K) -> Self {
        Self(RecordKeyInner::Key(RecordData::from(k)))
    }
}

/// A type to hold the contents of a record's value.
pub struct RecordData(bytes::Bytes);

impl<V: Into<Vec<u8>>> From<V> for RecordData {
    fn from(v: V) -> Self {
        let value: Vec<u8> = v.into();
        Self(value.into())
    }
}

fn send<K, V>(key: K, value: V)
    where
        K: Into<RecordKey>,
        V: Into<RecordData>,
{ ... }

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_conversion() {
        send(RecordKey::NULL, vec![2]);
        send(vec![3],vec![4]);
        send("Hello", "world");
        send("Hello".to_string(), "World".to_string());
    }
}
```

**Comment by sehz** [comment]
Instead of creating specialized API, we should generalize much as possible:

In place of this:
```
pub async fn send<K, V>(&self, key: K, value: V) -> Result<(), FluvioError>
    where
        K: Into<Vec<u8>>,
        V: Into<Vec<u8>>,
```

We can abstract out Key and Value as it's own type.  
```
pub async fn send<K, V>(&self, key: K, value: V) -> Result<(), FluvioError>
    where
        K: Into<PartitionKey>,
        V: Into<PartitionValue>,
``

Then you can do this:
```
producer.send(None,"My record data with no key").await?;
```

In many cases, `send` is preferable to `send_all`, since `Record` is abstraction we want to developers to use.  However, we need to integrated to buffer `Partitioning` so that it doesn't immediately router to SPU.

Also, if we are going to update this API, we should create specific Error for Producer rather than use crate wide Error.

**Comment by nicholastmosher** [comment]
I have tried other similar APIs and they have not worked out well. I believe that the API you are describing is essentially equivalent to the following one that I have tried:

```rust
fn send_option<K, MK, V>(maybe_key: MK, value: V) 
    where
        K: Into<Vec<u8>>,
        MK: Into<Option<K>>,
        V: Into<Vec<u8>>,
{
    let key: Option<K> = maybe_key.into();
    let key: Option<Vec<u8>> = key.map(|k| k.into());
    // ...    
}
```

The problem is that you cannot actually call it with a plain-old `None`:

```rust
#[test]
fn test_send_option() {
    // Cannot infer type for type parameter 'K'
    send_option(None, "World");

    // To make this work, you need to manually specify some K:
    send_option(None::<Vec<u8>>, "World");
}
```

I am experimenting now with the `PartitionValue` and `PartitionKey` API that you mentioned before, I want to see whether it has the same drawbacks that I believe it has

**Comment by nicholastmosher** [comment]
I am imagining the `PartitionKey` API you are describing to look something like this:

```rust
struct PartitionKey(Vec<u8>);

impl<T> From<T> for PartitionKey where T: Into<Vec<u8>> {
    fn from(t: T) -> Self {
        let vec: Vec<u8> = t.into();
        Self(vec)
    }
}

impl<T, OPT> From<OPT> for PartitionKey
    where
        T: Into<Vec<u8>>,
        OPT: Into<Option<T>>,
{
    fn from(opt: OPT) -> Self {
        let opt: Option<T> = opt.into();
        let opt_vec: Option<Vec<u8>> = opt.map(|t| t.into());
        Self(opt_vec)
    }
}
```

However this is met with a `T is not constrained` error:

```
error[E0207]: the type parameter `T` is not constrained by the impl trait, self type, or predicates
  --> src/lib.rs:36:6
   |
36 | impl<T, OPT> From<OPT> for PartitionKey
   |      ^ unconstrained type parameter

error: aborting due to previous error

For more information about this error, try `rustc --explain E0207`.
error: could not compile `playground`
```

Is there a different specific set of implementations that you are imagining to make this work?

**Comment by sehz** [comment]
This works:
```
use bytes::Bytes;

pub struct PartitionKey(Bytes);

impl <K> From<Option<K>> for PartitionKey 
    where Bytes: From<K>
{

    fn from(val: Option<K>) -> Self {
        if let Some(inner) = val {
            Self(inner.into())
        } else {
            Self(Bytes::new())
           
        }
    }
}

pub struct PartitionValue(Bytes);

impl From<Vec<u8>> for PartitionValue {
    fn from(val: Vec<u8>) -> Self {
        Self(val.into())
    }
}

fn send<B>(key: Option<B>, value: B)
    where PartitionKey: From<Option<B>>,
        PartitionValue: From<B>
{

}



#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_conversion() {
        send(None,vec![2]);
    }

}
```

**Comment by sehz** [comment]
From inspiration from @tjtelan,  here is simpler version without Option since we just need to indicate absence of Key.

```

pub const NoKey: PartitionKey = PartitionKey(Bytes::new());
pub struct PartitionKey(Bytes);

impl <K> From<K> for PartitionKey 
    where Bytes: From<K>
{

    fn from(val: K) -> Self {
        Self(val.into())
    }
}


pub struct PartitionValue(Bytes);

impl From<Vec<u8>> for PartitionValue {
    fn from(val: Vec<u8>) -> Self {
        Self(val.into())
    }
}

fn send<K,V>(key: K, value: V)
    where PartitionKey: From<K>,
        PartitionValue: From<V>
{

}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_conversion() {
        send(NoKey,vec![2]);
        send(vec![3],vec![4]);
    }

}

```

**Comment by nicholastmosher** [comment]
Ok we're getting there, but I still see two problems:

- One problem with this approach is that when building a request, a record with "No Key" is distinct from a record with a key which is an empty byte slice, so this approach would not cover that case. I think we may be able to tweak it slightly to work:

```rust
pub enum PartitionKey {
    NoKey,
    Bytes(Bytes),
}

impl<K: Into<Vec<u8>>> From<K> for PartitionKey 
{
    fn from(key: K) -> Self {
        let vec: Vec<u8> = key.into();
        Self::Bytes(vec.into())
    }
}
```

This would allow us to convert `PartitionKey::Bytes(key)` into a `Some(key)` in our request-record, and `PartitionKey::NoKey` could convert to `None`.

- The other problem is that we want not just `From<Vec<u8>> for PartitionValue`, we want `impl<T: Into<Vec<u8>>> From<T> for PartitionValue`, so that any type that can convert to a Vec<u8> may be passed (this includes String, &str, etc.)

```rust
pub struct PartitionValue(Bytes);

impl<T: Into<Vec<u8>>> From<T> for PartitionValue {
    fn from(val: T) -> Self {
        let vec: Vec<u8> = val.into();
        Self(vec.into())
    }
}
```

This gives us the following calling patterns:

```rust
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_conversion() {
        send(PartitionKey::NoKey, vec![2]);
        send(vec![3], vec![4]);
        send("Hello", "world");
        send("Hello".to_string(), "World".to_string());
    }
}
```

The one minor problem I have with this is that I am not 100% happy with the names for the `PartitionKey` variants. It seems that `PartitionKey::NoKey` is rather long to type, and `PartitionKey::Bytes` is more specific than it needs to be. I'd like any more feedback about those names. Perhaps `PartitionKey::Present` and `PartitionKey::Absent`? Let me know what you guys think.

**Comment by sehz** [comment]
```
pub enum PartitionKey {
    None,
    Some(Bytes),
}
```

**Comment by nicholastmosher** [comment]
I think it would be a really bad idea to use `Some` and `None` for variants on our own enum, I think it would be very confusing to users. Imagine writing this:

```
producer.send(None, "Hello!").await?;
```

And having it not work. I just tried it out and this is the error it generates:

```
error[E0277]: the trait bound `Vec<u8>: From<Option<_>>` is not satisfied
  --> src/lib.rs:42:9
   |
28 | fn send<K, V>(key: K, value: V)
   |    ---- required by a bound in this
29 |     where
30 |         K: Into<PartitionKey>,
   |            ------------------ required by this bound in `send`
...
42 |         send(None, vec![2]);
   |         ^^^^ the trait `From<Option<_>>` is not implemented for `Vec<u8>`
   |
   = help: the following implementations were found:
             <Vec<T, A> as From<Box<[T], A>>>
             <Vec<T> as From<&[T]>>
             <Vec<T> as From<&mut [T]>>
             <Vec<T> as From<BinaryHeap<T>>>
           and 6 others
   = note: required because of the requirements on the impl of `Into<Vec<u8>>` for `Option<_>`
   = note: required because of the requirements on the impl of `From<Option<_>>` for `PartitionKey`
   = note: 1 redundant requirements hidden
   = note: required because of the requirements on the impl of `Into<PartitionKey>` for `Option<_>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground`
```

This gives us absolutely no help when the solution would be to just use `PartitionKey::None` instead of `None`. I think we should come up with other names that are not as easy to confuse.

**Comment by sehz** [comment]
What's alternatives? Should've some feedback from team @simlay @tjtelan @nacardin

**Comment by nicholastmosher** [comment]
Well one thing to realize is that we have the "Have a key" and "Don't have a key" cases, and users only really need to know about the "Don't have a key case", since the conversions from Vec<u8> are used to construct the "Have a key" case.

Here are some other ideas:

```rust
enum PartitionKey {
    Blank,
    Filled(Bytes),
}

enum PartitionKey {
    Unused,
    Used(Bytes),
}

enum PartitionKey {
    Empty,
    Full(Bytes),
}

enum PartitionKey {
    Unkeyed,
    Keyed(Bytes),
}
```

Out of these options I think I like the first one best:

```rust
enum PartitionKey {
    Blank,
    Filled(Bytes),
}
```

**Comment by sehz** [comment]
Blank:  
```noun
noun: blank; plural noun: blanks; noun: blank cartridge; plural noun: blank cartridges
1.
a space left to be filled in a document.
"leave blanks to type in the appropriate names"```

let's try to use standard software terminology.  In Kafka, it is Null Key.  Closed I can think of is: https://docs.rs/diesel/0.15.2/diesel/types/struct.Nullable.html.  

So we can write as:
```
enum PartitionKey {
    Nullable,
    NotNull(Bytes),
}
```

Of course, we can define
```
const NulllKey = PartitionKey::Nullable;
send(NullKey, vec![2]);
```

**Comment by ajhunyady** [comment]
How about?

> enum PartitionKey {
>     Nullable,
>     Value(Bytes),
> }

**Comment by sehz** [comment]
Only issue with `Value` is that it might confused with `PartitionValue`.  But it might be best fitting

**Comment by nicholastmosher** [comment]
Honestly we could even say `Null` rather than `Nullable`, I quite like that. What about:

```rust
enum PartitionKey {
    Null,
    Full(Bytes),
}
```

Because as a reminder, the user will never need to manually use the `PartitionKey::Full()` variant, it will come automatically via conversions

**Comment by sehz** [comment]
`Null` is fine.  `Full` is confusing

**Comment by ajhunyady** [comment]
Not sure about `Full` as it implies... it's really full. How about `data` or `content`?

**Comment by nicholastmosher** [comment]
What about just `PartitionKey::Key`? I think that is most clear, plus nobody is going to need to type it out so it will not be visually redundant anywhere

**Comment by ajhunyady** [comment]
Is it `Key` or `KeyValue`?

**Comment by nicholastmosher** [comment]
That field contains only the data for the key. Let me post the full version of the API I believe we are proposing now:

```rust
pub enum PartitionKey {
    Null,
    Key(Bytes),
}

impl<K: Into<Vec<u8>>> From<K> for PartitionKey 
{
    fn from(key: K) -> Self {
        let vec: Vec<u8> = key.into();
        Self::Key(vec.into())
    }
}


pub struct PartitionValue(Bytes);

impl<T: Into<Vec<u8>>> From<T> for PartitionValue {
    fn from(val: T) -> Self {
        let vec: Vec<u8> = val.into();
        Self(vec.into())
    }
}

fn send<K, V>(key: K, value: V)
    where
        K: Into<PartitionKey>,
        V: Into<PartitionValue>,
{ ... }

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_conversion() {
        send(PartitionKey::Null, vec![2]);
        send(vec![3],vec![4]);
        send("Hello", "world");
        send("Hello".to_string(), "World".to_string());
    }
}
```

**Comment by ajhunyady** [comment]
@nicholastmosher looks good to me. Nice work!

**Comment by nicholastmosher** [comment]
Thanks! @infinyon/dev are we good on this? If so I am going to convert this issue into an action item for implementing it.

**Comment by nicholastmosher** [comment]
On second thought, I think it makes more sense to name these types `RecordKey` and `RecordValue`. Any thoughts?

**Comment by ajhunyady** [comment]
I see what you mean.... the data structure seems to be more about `Records` than it is about `Partitions`. It's ok by me, but I'm not sure I have sufficient context to pick one vs another.

**Comment by sehz** [comment]
`RecordKey` and `RecordValue` seems fine

**Comment by sehz** [comment]
```
pub struct RecordKey(RecordKeyInner);

impl RecordKey {
    pub const NULL: Self = Self(RecordKeyInner::Null);
}

enum RecordKeyInner {
    Null,
    Key(Bytes),
}
```

Not seeing point in hiding Enum abstraction.    However, I see in point in hiding our internal details.  So this might be good compromise:

```
pub enum RecordKey {
    Null,
    Key(RecordValue),
}

```

**Comment by nicholastmosher** [comment]
> Not seeing point in hiding Enum abstraction

It is the same reason that basically everybody advocates for encapsulation and private data fields: It is to give us the flexibility to change the internal details in the future. When we define structs in Rust and do not annotate fields with `pub`, those fields are private, and cannot be accessed by code outside of the module:

```rust
mod example {
    pub struct PublicStruct {
        private_field: String,
    }
}

// Then, in any other module
public_struct.private_field // compile error, field is not public
```

However, enums work differently from this. When an enum is declared public, all of the variants and all of the data belonging to those variants are public. That means that all of the types used must also be public, and changing any details of this inner layout for an enum would be considered a breaking change.

```rust
mod example {
    pub enum PublicEnum {
        Data(String),
    }
}

// Then, anywhere else

if let PublicEnum::Data(string) = public_enum {
    // Here, the caller knows that the exact type of string is String, and changing it would be a breaking change
}
```

In the case of `RecordKey`, all we want to do is have a type that represents one of two possible situations: "We have a key" or "We don't have a key", however we don't actually need to let users know how we distinguish between these two states. We just need to give them a way to construct either of these two cases. In the `send` API, the two ways to construct a `RecordKey` are the following:

- Use the `Into` conversion trait. Any type that can be converted into a `Vec<u8>` can also be converted to a `RecordKey`
- Or, use the direct constant `RecordKey::NULL` to indicate there is no key data.

The users do not need to know anything else about the `RecordKey` type at all. They don't need to know that we use `Bytes` internally or `Vec<u8>` or anything else. They also never need to inspect the `RecordKey` data, only `send` needs to be able to do that.

This approach will give us the maximum flexibility to update our implementations in the future, leading to fewer breaking changes

**Comment by nicholastmosher** [comment]
After some more discussion, we're now thinking about using the private-enum approach, and additionally using a common `RecordData` struct for the backing data type of both keys and values to a record.

```rust
pub struct RecordKey(RecordKeyInner);

impl RecordKey {
    pub const NULL: Self = Self(RecordKeyInner::Null);
}

enum RecordKeyInner {
    Null,
    Key(RecordData),
}

impl<K: Into<Vec<u8>>> From<K> for RecordKey {
    fn from(k: K) -> Self {
        Self(RecordKeyInner::Key(RecordData::from(k)))
    }
}

/// A type to hold the contents of a record's value.
pub struct RecordData(bytes::Bytes);

impl<V: Into<Vec<u8>>> From<V> for RecordData {
    fn from(v: V) -> Self {
        let value: Vec<u8> = v.into();
        Self(value.into())
    }
}
```

**Comment by ajhunyady** [comment]
Should move the above in the `Discussion Results` as it may be useful when we build the documentation for this feature.

**Comment by nicholastmosher** [comment]
@ajhunyady do you mean to add a label called `Discussion Results`?

**Comment by ajhunyady** [comment]
The API in `Discissions Results` at the top is different from the API described above.
